#!/bin/bash
# Demo: Session-Integrated Chat

echo "=========================================="
echo "Session-Integrated Chat Demo"
echo "=========================================="
echo ""

echo "✅ Feature: Persistent Conversations"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "1. Start chat with auto-save:"
echo "   $ offgrid run llama --save my-project"
echo ""
echo "   - Every message automatically saved"
echo "   - Session survives crashes/restarts"
echo "   - No manual save needed"
echo ""

echo "2. Continue previous conversation:"
echo "   $ offgrid run llama --load my-project"
echo ""
echo "   - Loads full conversation history"
echo "   - Shows previous messages"
echo "   - Continues from where you left off"
echo ""

echo "3. Manage sessions:"
echo "   $ offgrid session list         # View all sessions"
echo "   $ offgrid session show my-project"
echo "   $ offgrid session export my-project notes.md"
echo "   $ offgrid session delete old-session"
echo ""

echo "=========================================="
echo "Usage Examples"
echo "=========================================="
echo ""

echo "📝 Scenario 1: Working on a coding project"
echo "-------------------------------------------"
echo "Day 1:"
echo "  $ offgrid run llama --save refactoring-auth"
echo "  You: How should I refactor the auth module?"
echo "  Assistant: [provides detailed advice]"
echo "  You: exit"
echo ""
echo "Day 2 (resume):"
echo "  $ offgrid run llama --load refactoring-auth"
echo "  [Shows previous conversation]"
echo "  You: I implemented your suggestion, now what about testing?"
echo ""

echo "📚 Scenario 2: Learning session"
echo "-------------------------------------------"
echo "  $ offgrid run llama --save learning-rust"
echo "  You: Explain Rust ownership"
echo "  Assistant: [explains ownership]"
echo "  You: clear                    # Start fresh but keep session"
echo "  You: Now explain borrowing"
echo "  You: exit"
echo ""
echo "Later:"
echo "  $ offgrid session export learning-rust rust-notes.md"
echo "  $ cat rust-notes.md          # Full learning log in markdown"
echo ""

echo "=========================================="
echo "How It Works"
echo "=========================================="
echo ""
echo "🔄 Auto-Save Behavior:"
echo "   • Saves after EVERY user + assistant exchange"
echo "   • Silent background saves (no interruption)"
echo "   • Final save on exit"
echo "   • Works with 'clear' command (clears session too)"
echo ""
echo "💾 Storage:"
echo "   • Location: ~/.offgrid/sessions/"
echo "   • Format: JSON with timestamps"
echo "   • Each message has: role, content, timestamp"
echo ""
echo "🎯 Benefits:"
echo "   • Never lose important conversations"
echo "   • Resume long-running discussions"
echo "   • Export knowledge base/notes"
echo "   • Track decision-making process"
echo "   • Share conversations with team"
echo ""

echo "=========================================="
echo "Commands Reference"
echo "=========================================="
echo ""
echo "Chat Commands:"
echo "  offgrid run <model> --save <name>    # New session (auto-save)"
echo "  offgrid run <model> --load <name>    # Continue session"
echo "  offgrid run <model>                  # No session (temporary)"
echo ""
echo "In-Chat Commands:"
echo "  exit         Exit and save"
echo "  clear        Reset conversation (but keep session)"
echo ""
echo "Session Management:"
echo "  offgrid session list                 # List all sessions"
echo "  offgrid session show <name>          # View session"
echo "  offgrid session export <name> [file] # Export to markdown"
echo "  offgrid session delete <name>        # Remove session"
echo ""

echo "=========================================="
echo "Test the feature:"
echo "=========================================="
echo ""
echo "Try loading the existing test session:"
echo "  $ offgrid run Llama-3.2-3B-Instruct-Q4_K_M --load test-project"
echo ""
echo "Or create a new one:"
echo "  $ offgrid run Llama-3.2-3B-Instruct-Q4_K_M --save demo-session"
echo ""
