/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Explicit online search of public GGUF repositories. Requires model permissions. No hardware size cap. */
        get: operations["searchPublicModels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/search/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listPublicModelFiles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/system": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSystemIdentity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listModels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listCatalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/models/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["downloadModel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/models/download/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getDownloadProgress"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/models/download/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cancelDownload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/models/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteModel"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/models/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["verifyModel"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Lists owned conversations; sessions:all administrators and local single-user mode can also access unowned legacy conversations. */
        get: operations["listSessions"];
        put?: never;
        /** @description Creates a conversation owned by the authenticated caller. Names are installation-wide unique; an existing name returns 409 without overwriting history. Client-supplied ownership is ignored. */
        post: operations["createSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["SessionName"];
            };
            cookie?: never;
        };
        /** @description Returns 404 for an absent conversation or one owned by another user unless the caller has sessions:all. */
        get: operations["getSession"];
        put?: never;
        post?: never;
        /** @description Requires ownership or sessions:all; other users' conversations return 404. Returns 409 immediately while generation or another mutation is active; deletion never waits to erase a newly completed turn. */
        delete: operations["deleteSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{name}/generate": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["SessionName"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Requires session ownership (or sessions:all) and chat permission. Requested knowledge additionally requires rag permission. With stream=true, sends SSE phase and delta events immediately, followed by done only after atomic persistence, or error without saving a partial exchange. Transport closure is not completion. Retrieval failures after SSE starts are error events. JSON generation returns 503 for unavailable retrieval and 422 for no evidence. */
        post: operations["generateSessionTurn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{name}/turn": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["SessionName"];
            };
            cookie?: never;
        };
        get: operations["getSessionTurn"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{name}/turn/events": {
        parameters: {
            query: {
                id: string;
            };
            header?: never;
            path: {
                name: components["parameters"]["SessionName"];
            };
            cookie?: never;
        };
        /** @description Authorized snapshot recovery. Replays the entire current partial output, followed by live deltas. A new attachment must replace its previous partial output, not append a replay. Slow/disconnected readers do not control execution. */
        get: operations["followSessionTurn"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{name}/turn/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["SessionName"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cancelSessionTurn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/documents/source": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Requires knowledge read permission. Returns retained extracted text, not the original file. Available while inference is disabled. */
        get: operations["getDocumentSource"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/chat/completions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Requested knowledge requires rag permission in addition to chat. Disabled/failed retrieval returns 503 and no matching evidence returns 422 before inference or streaming begins. Turn off use_knowledge_base explicitly to request an ordinary answer. */
        post: operations["createChatCompletion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listDocuments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/rag/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Remains available when knowledge storage fails; reports enabled false and stats.storage_available false with an actionable error. No volatile fallback is used. */
        get: operations["getRAGStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/rag/enable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["enableRAG"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/documents/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ingestDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/documents/reindex": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["reindexDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Starts a checkpointed run. Use async for a background task and poll by run ID. New runs cannot contain preapproved tools; approve the pending call on its existing run instead. */
        post: operations["runAgent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAgentTasks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/tasks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get: operations["getAgentRun"];
        put?: never;
        post?: never;
        /** @description Owner-only removal of completed, failed or cancelled history. Active workers, pending approvals, interrupted and uncertain outcomes return 409. A durable scrubbed tombstone prevents event projections restoring history. Separate audit logs, backups and tool-created files are not erased. */
        delete: operations["deleteAgentRun"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/tasks/{id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream durable agent snapshots without owning execution
         * @description Starts with the latest saved snapshot, then sends changed snapshots and heartbeat comments. Reconnect to recover the latest bounded preview; this is not an event-history replay endpoint. Disconnect does not cancel work. Only the run owner can subscribe.
         */
        get: operations["streamAgentProgress"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/tasks/{id}/{action}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                action: "approve" | "deny" | "cancel" | "resume" | "reconcile";
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Requires the initiating actor. Approve/deny require the pending approval_id. Resume never replays an uncertain tool call; reconcile requires its call_id and a human-verified result. Expired approvals can be refreshed with resume. Reconciliation records a result without executing the tool. */
        post: operations["changeAgentRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/tools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAgentTools"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["setAgentToolEnabled"];
        trace?: never;
    };
    "/v1/agents/mcp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listMCPServers"];
        put?: never;
        post: operations["connectMCPServer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/mcp/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["testMCPServer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listCapabilities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/integrations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listExternalAgentIntegrations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/integrations/{id}/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getExternalAgentIntegrationSetup"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/computer/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getComputerStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        DiscoveredModel: {
            id: string;
            author: string;
            name: string;
            downloads: number;
            likes: number;
        };
        DiscoveredFile: {
            id: string;
            file: string;
            size_bytes: number;
            quant: string;
            supported: boolean;
            reason?: string;
        };
        SystemIdentity: {
            /** @constant */
            product: "offgrid";
            version: string;
            revision: string;
            /** @constant */
            api_version: 2;
            /** @description SHA-256 of the served UI index; empty when not installed. */
            ui_build_id: string;
            capabilities: string[];
        };
        /** @enum {string} */
        ChatStreamPhase: "queued" | "retrieving" | "loading" | "processing" | "generating" | "saving";
        ChatTimings: {
            total_ms: number;
            ready_ms: number;
            queue_ms: number;
            load_ms: number;
            prompt_ms: number;
            first_text_ms: number;
            generation_ms: number;
            context_window: number;
            completion_tokens?: number;
            tokens_per_second?: number;
        };
        SessionStreamEvent: {
            /** @enum {string} */
            type: "phase";
            phase: components["schemas"]["ChatStreamPhase"];
        } | {
            /** @enum {string} */
            type: "delta";
            delta: string;
        } | {
            /** @enum {string} */
            type: "done";
            session: components["schemas"]["ChatSession"];
            message: components["schemas"]["SessionMessage"];
            metrics: components["schemas"]["ChatTimings"];
            /** @enum {string} */
            finish_reason: "stop" | "length";
        } | {
            /** @enum {string} */
            type: "error";
            error: string;
        };
        ErrorResponse: {
            error: string | {
                message: string;
                type?: string;
                code?: string;
            };
        };
        Health: {
            status: string;
            version: string;
            uptime?: string;
            /** Format: int64 */
            uptime_seconds?: number;
            models?: {
                [key: string]: unknown;
            };
            inference?: {
                [key: string]: unknown;
            };
            system?: {
                [key: string]: unknown;
            };
        };
        PublicUser: {
            id: string;
            username: string;
            display_name?: string;
            role: string;
        };
        CurrentUser: {
            authenticated: boolean;
            guest?: boolean;
            user: components["schemas"]["PublicUser"] | null;
        };
        LoginRequest: {
            username: string;
            /** Format: password */
            password: string;
        };
        LoginResponse: {
            user: components["schemas"]["PublicUser"];
            token?: string;
            /** Format: date-time */
            expires_at: string;
            auth_method: string;
        };
        Model: {
            id: string;
            object?: string;
            /** Format: int64 */
            created?: number;
            owned_by?: string;
            type?: string;
            /** Format: int64 */
            size?: number;
            size_gb?: string;
            loaded?: boolean;
            context_window?: number;
            /** @description OpenAI-compatible alias for context_window. */
            context_length?: number;
            capabilities?: string[];
            capability_status?: {
                [key: string]: "declared" | "tested" | "unsupported" | "unknown";
            };
        };
        IntegrationStatus: {
            id: string;
            /** @constant */
            provider_id: "offgrid";
            plugin_id: string;
            name: string;
            description: string;
            /** @constant */
            transport: "openai-chat-completions";
            /** Format: uri */
            documentation_url: string;
            minimum_context: number;
            recommended_context: number;
            requires_tools: boolean;
            capabilities: string[];
            ready: boolean;
            /** @enum {string} */
            status: "ready" | "needs_configuration";
            model_id?: string;
            context_window: number;
            warnings: string[];
        };
        IntegrationList: {
            /** @constant */
            provider: "offgrid";
            /** Format: uri */
            base_url: string;
            integrations: components["schemas"]["IntegrationStatus"][];
        };
        IntegrationSetup: {
            /** @constant */
            provider_id: "offgrid";
            plugin_id: string;
            install_command: string;
            format: string;
            config_file: string;
            content: string;
            environment?: {
                [key: string]: string;
            };
            verify: string[];
            notes?: string[];
        };
        IntegrationSetupResponse: {
            integration: components["schemas"]["IntegrationStatus"];
            setup: components["schemas"]["IntegrationSetup"];
        };
        CatalogModel: {
            id: string;
            name: string;
            description: string;
            category: string;
            parameters: string;
            size: string;
            /** Format: int64 */
            size_bytes: number;
            repo: string;
            file: string;
            quant: string;
            min_ram_gb: number;
            recommended: boolean;
            provider: string;
            type: string;
            license: string;
        };
        ModelDownloadRequest: {
            /**
             * @description Requires knowledge management permission as well as model management. Persist activation intent and enable knowledge after installation without relying on an attached page. Empty repository is allowed only for an already installed model.
             * @default false
             */
            enable_knowledge: boolean;
            repository: string;
            file_name?: string;
            quantization?: string;
            /** @description Stable catalog ID used for the collision-free local filename. */
            model_id?: string;
        };
        DownloadProgress: {
            repository?: string;
            source_file?: string;
            model_id?: string;
            quantization?: string;
            enable_knowledge?: boolean;
            file_name: string;
            /** Format: int64 */
            bytes_total: number;
            /** Format: int64 */
            bytes_done: number;
            percent: number;
            speed: number;
            /** Format: int64 */
            started_at: number;
            /** @enum {string} */
            status: "downloading" | "finalizing" | "complete" | "failed" | "cancelled";
            error?: string;
        };
        Verification: {
            model_id: string;
            file_name: string;
            /** Format: int64 */
            size: number;
            size_gb: string;
            sha256: string;
            verified: boolean;
            message?: string;
        };
        ChatMessage: {
            /** @enum {string} */
            role: "system" | "developer" | "user" | "assistant" | "tool";
            content: string;
            tool_call_id?: string;
            tool_calls?: {
                id: string;
                /** @constant */
                type: "function";
                function: {
                    name: string;
                    arguments: string;
                };
            }[];
        };
        SessionMessage: components["schemas"]["ChatMessage"] & {
            /** Format: date-time */
            timestamp: string;
        };
        SessionTurn: {
            id: string;
            prompt: string;
            model: string;
            profile: string;
            knowledge: boolean;
            max_tokens: number;
            /** @enum {string} */
            status: "pending" | "running" | "completed" | "failed" | "cancelled" | "interrupted";
            phase: string;
            output: string;
            error?: string;
            finish_reason?: string;
            metrics?: components["schemas"]["ChatTimings"];
        };
        ChatSession: {
            turn?: components["schemas"]["SessionTurn"];
            name: string;
            /** @description Authenticated owner assigned by the service. Absent for legacy/local sessions, which require sessions:all in authenticated mode. */
            readonly owner_id?: string;
            model_id: string;
            messages: components["schemas"]["SessionMessage"][];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ChatCompletionRequest: {
            model: string;
            /** Format: int64 */
            seed?: number;
            messages: components["schemas"]["ChatMessage"][];
            /** @default false */
            stream: boolean;
            stream_options?: {
                /** @default false */
                include_usage: boolean;
            };
            tools?: {
                /** @constant */
                type: "function";
                function: {
                    name: string;
                    description?: string;
                    parameters?: {
                        [key: string]: unknown;
                    };
                };
            }[];
            tool_choice?: unknown;
            /** @default false */
            use_knowledge_base: boolean;
        };
        ChatCompletionResponse: {
            id: string;
            object: string;
            /** Format: int64 */
            created: number;
            model: string;
            choices: {
                index: number;
                message: components["schemas"]["ChatMessage"];
                finish_reason?: string | null;
            }[];
        };
        Document: {
            id: string;
            name: string;
            content_type: string;
            /** Format: int64 */
            size: number;
            chunk_count: number;
            content_hash?: string;
            index_status?: string;
            last_error?: string;
            /** Format: date-time */
            indexed_at?: string;
            source_retained?: boolean;
            /** Format: date-time */
            created_at: string;
        };
        RAGStatus: {
            enabled: boolean;
            embedding_model?: string;
            stats: {
                [key: string]: unknown;
            };
        };
        ToolApproval: {
            id: string;
            run_id: string;
            call_id: string;
            actor: string;
            tool: string;
            arguments: {
                [key: string]: unknown;
            };
            /** @description Exact canonical JSON for review without JavaScript numeric precision loss. */
            canonical_arguments: string;
            capability?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            expires_at: string;
        };
        AgentRunRequest: {
            model: string;
            prompt: string;
            /** @enum {string} */
            style?: "react" | "cot" | "plan-execute";
            max_iterations?: number;
            /** @default false */
            async: boolean;
            /**
             * @description Streams run status and completed steps; disconnecting does not cancel execution.
             * @default false
             */
            stream: boolean;
            system_prompt?: string;
        };
        AgentStep: {
            id?: number;
            type?: string;
            content?: string;
            tool_name?: string;
            tool_args?: string;
            tool_result?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        AgentProgress: {
            /** @enum {string} */
            phase: "queued" | "loading" | "processing" | "generating" | "preparing_tool" | "tool" | "approval";
            iteration: number;
            tool?: string;
            /** @description Bounded public model response preview */
            preview: string;
            truncated: boolean;
            /** Format: date-time */
            started_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        AgentRunResponse: {
            output: string;
            task_id: string;
            run_id: string;
            /** @enum {string} */
            status: "pending" | "running" | "waiting_for_approval" | "interrupted" | "uncertain" | "completed" | "failed" | "cancelled";
            error?: string;
            pending_approval: components["schemas"]["ToolApproval"] | null;
            /** @description Whether this run has a safe checkpoint for explicit resume. Legacy history without checkpoints is read-only. */
            resumable: boolean;
            /** Format: date-time */
            started_at?: string | null;
            progress?: components["schemas"]["AgentProgress"] | null;
            uncertain_call_id?: string;
            uncertain_call?: {
                tool: string;
                arguments: {
                    [key: string]: unknown;
                };
            };
            steps: components["schemas"]["AgentStep"][];
        };
        AgentTask: {
            /** @description Whether this actor may remove this terminal run; the server rechecks state at deletion time. */
            deletable?: boolean;
            id: string;
            prompt: string;
            status: string;
            model?: string;
            actor?: string;
            pending_approval?: components["schemas"]["ToolApproval"];
            result?: string;
            error?: string;
            steps?: components["schemas"]["AgentStep"][];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            started_at?: string;
            /** Format: date-time */
            completed_at?: string;
        };
        ComputerStatus: {
            available: boolean;
            emergency_stop: boolean;
            active_sessions: number;
        };
    };
    responses: {
        /** @description API error */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Authentication required */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        SessionName: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    searchPublicModels: {
        parameters: {
            query: {
                query: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Repository metadata; file lists are fetched on selection, not for every result. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        total: number;
                        results: components["schemas"]["DiscoveredModel"][];
                    };
                };
            };
            /** @description Invalid search query or limit. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            /** @description Upstream search unavailable; this is not an empty successful search. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listPublicModelFiles: {
        parameters: {
            query: {
                repo: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description GGUF choices with repository-scoped local IDs and exact sizes when available; first 1000 tree entries. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        repo: string;
                        files: components["schemas"]["DiscoveredFile"][];
                    };
                };
            };
            /** @description Invalid repository name. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            /** @description Upstream file discovery unavailable. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getSystemIdentity: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Public product identity and implemented client contracts, without private runtime state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemIdentity"];
                };
            };
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Runtime health */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current authentication state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUser"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Authenticated session */
            200: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session cleared */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status: string;
                    };
                };
            };
        };
    };
    listModels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Installed models */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        object: "list";
                        data: components["schemas"]["Model"][];
                    };
                };
            };
        };
    };
    listCatalog: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Curated model catalog */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        total: number;
                        models: components["schemas"]["CatalogModel"][];
                    };
                };
            };
        };
    };
    downloadModel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelDownloadRequest"];
            };
        };
        responses: {
            /** @description Download accepted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        status: string;
                        file_name: string;
                        message?: string;
                    };
                };
            };
            409: components["responses"]["Error"];
        };
    };
    getDownloadProgress: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Download state keyed by destination filename */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["DownloadProgress"];
                    };
                };
            };
        };
    };
    cancelDownload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    file_name: string;
                };
            };
        };
        responses: {
            /** @description Cancellation result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        cancelled: boolean;
                        message?: string;
                    };
                };
            };
        };
    };
    deleteModel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    model_id: string;
                };
            };
        };
        responses: {
            /** @description Model deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        message?: string;
                    };
                };
            };
        };
    };
    verifyModel: {
        parameters: {
            query: {
                model: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Full-file SHA-256 result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Verification"];
                };
            };
        };
    };
    listSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Durable conversations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        sessions: components["schemas"]["ChatSession"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Error"];
        };
    };
    createSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    model_id?: string;
                };
            };
        };
        responses: {
            /** @description Conversation created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatSession"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["SessionName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Durable conversation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatSession"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    deleteSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["SessionName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Conversation deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        message?: string;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    generateSessionTurn: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["SessionName"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    content: string;
                    model_id?: string;
                    /** @default false */
                    use_knowledge_base?: boolean;
                    /** @default false */
                    stream?: boolean;
                    /**
                     * @description Persist admission and run independently of the stream connection. Reconnect using the turn endpoints.
                     * @default false
                     */
                    durable?: boolean;
                    /** @description Required for durable streaming. Reusing the current ID with identical input attaches to existing work; conflicting or superseded reuse returns 409. */
                    request_id?: string;
                    /**
                     * @description Streaming chat context profile. Interactive uses min(OFFGRID_CHAT_CONTEXT
                     * @default interactive
                     * @enum {string}
                     */
                    profile?: "interactive" | "extended";
                    /**
                     * @description Streaming response token budget.
                     * @default 1024
                     */
                    max_tokens?: number;
                };
            };
        };
        responses: {
            /** @description Complete persisted turn as JSON, or SSE events ending with persisted done or error */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @description Each SSE data field is a SessionStreamEvent JSON object. Heartbeat comments carry no data. */
                    "text/event-stream": string;
                    "application/json": {
                        session: components["schemas"]["ChatSession"];
                        message: components["schemas"]["SessionMessage"];
                    };
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            422: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    getSessionTurn: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["SessionName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Latest saved turn, or null. Restarted work is interrupted, never automatically replayed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        turn: components["schemas"]["SessionTurn"] | null;
                    };
                };
            };
            404: components["responses"]["Error"];
        };
    };
    followSessionTurn: {
        parameters: {
            query: {
                id: string;
            };
            header?: never;
            path: {
                name: components["parameters"]["SessionName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session phase/delta/done/error SSE stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            409: components["responses"]["Error"];
        };
    };
    cancelSessionTurn: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["SessionName"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    id: string;
                };
            };
        };
        responses: {
            /** @description Cancellation requested for this exact turn. Refresh for terminal state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: components["responses"]["Error"];
        };
    };
    getDocumentSource: {
        parameters: {
            query: {
                id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Safe text preview (maximum 200000 Unicode characters) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        document: components["schemas"]["Document"];
                        content: string;
                        truncated: boolean;
                    };
                };
            };
            404: components["responses"]["Error"];
            410: components["responses"]["Error"];
        };
    };
    createChatCompletion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatCompletionRequest"];
            };
        };
        responses: {
            /** @description OpenAI-compatible non-streaming response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatCompletionResponse"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Error"];
            422: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    listDocuments: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Indexed documents */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        documents: components["schemas"]["Document"][];
                        count: number;
                    };
                };
            };
            503: components["responses"]["Error"];
        };
    };
    getRAGStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Retrieval readiness */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RAGStatus"];
                };
            };
        };
    };
    enableRAG: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    embedding_model: string;
                };
            };
        };
        responses: {
            /** @description Knowledge retrieval enabled and activation persisted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        message: string;
                    };
                };
            };
            400: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    ingestDocument: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Document indexed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        document: components["schemas"]["Document"];
                    };
                };
            };
            503: components["responses"]["Error"];
        };
    };
    reindexDocument: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    document_id: string;
                };
            };
        };
        responses: {
            /** @description Document reindexed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        document: components["schemas"]["Document"];
                    };
                };
            };
            503: components["responses"]["Error"];
        };
    };
    runAgent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentRunRequest"];
            };
        };
        responses: {
            /** @description Governed agent run status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentRunResponse"];
                };
            };
            /** @description Persisted background run accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentRunResponse"];
                };
            };
            400: components["responses"]["Error"];
            409: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    listAgentTasks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Durable agent task states */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentTask"][];
                };
            };
            503: components["responses"]["Error"];
        };
    };
    getAgentRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authoritative run snapshot, including pending approval or uncertain tool call */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentRunResponse"];
                };
            };
            404: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    deleteAgentRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed from task and activity history */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                    };
                };
            };
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    streamAgentProgress: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE data frames contain AgentRunResponse plus type=status, done, approval_required or error. A preview is provisional, never a completed answer. Terminal snapshots close the stream. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            /** @description Run not found or not owned by the current actor */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Agent storage unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    changeAgentRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                action: "approve" | "deny" | "cancel" | "resume" | "reconcile";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    approval_id?: string;
                    call_id?: string;
                    result?: string;
                    /** @default false */
                    async?: boolean;
                };
            };
        };
        responses: {
            /** @description Persisted run state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentRunResponse"];
                };
            };
            /** @description Continuation accepted on the same run */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentRunResponse"];
                };
            };
            400: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    listAgentTools: {
        parameters: {
            query?: {
                all?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Agent tool catalog */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    setAgentToolEnabled: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    enabled: boolean;
                };
            };
        };
        responses: {
            /** @description Tool state persisted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listMCPServers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Connected MCP servers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    connectMCPServer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    /** Format: uri */
                    url: string;
                };
            };
        };
        responses: {
            /** @description MCP server connected and persisted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    testMCPServer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uri */
                    url: string;
                };
            };
        };
        responses: {
            /** @description MCP connection test result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listCapabilities: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Governed capability descriptors */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listExternalAgentIntegrations: {
        parameters: {
            query?: {
                /** @description Installed chat model to evaluate for integration readiness. */
                model?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description First-party external agent provider integrations and their runtime readiness. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntegrationList"];
                };
            };
        };
    };
    getExternalAgentIntegrationSetup: {
        parameters: {
            query?: {
                model?: string;
                base_url?: string;
                max_output_tokens?: number;
            };
            header?: never;
            path: {
                id: "hermes" | "openclaw";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ready-to-copy native provider setup. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntegrationSetupResponse"];
                };
            };
            400: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    getComputerStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Computer-use driver and safety-controller status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComputerStatus"];
                };
            };
        };
    };
}
