/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listModels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listCatalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/models/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["downloadModel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/models/download/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getDownloadProgress"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/models/download/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cancelDownload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/models/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteModel"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/models/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["verifyModel"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listSessions"];
        put?: never;
        post: operations["createSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["SessionName"];
            };
            cookie?: never;
        };
        get: operations["getSession"];
        put?: never;
        post?: never;
        delete: operations["deleteSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{name}/generate": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["SessionName"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["generateSessionTurn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/chat/completions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createChatCompletion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listDocuments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/rag/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getRAGStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/rag/enable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["enableRAG"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/documents/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ingestDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/documents/reindex": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["reindexDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["runAgent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAgentTasks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/tools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAgentTools"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["setAgentToolEnabled"];
        trace?: never;
    };
    "/v1/agents/mcp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listMCPServers"];
        put?: never;
        post: operations["connectMCPServer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/mcp/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["testMCPServer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listCapabilities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/integrations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listExternalAgentIntegrations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/integrations/{id}/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getExternalAgentIntegrationSetup"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/computer/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getComputerStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            error: string | {
                message: string;
                type?: string;
                code?: string;
            };
        };
        Health: {
            status: string;
            version: string;
            uptime?: string;
            /** Format: int64 */
            uptime_seconds?: number;
            models?: {
                [key: string]: unknown;
            };
            inference?: {
                [key: string]: unknown;
            };
            system?: {
                [key: string]: unknown;
            };
        };
        PublicUser: {
            id: string;
            username: string;
            display_name?: string;
            role: string;
        };
        CurrentUser: {
            authenticated: boolean;
            guest?: boolean;
            user: components["schemas"]["PublicUser"] | null;
        };
        LoginRequest: {
            username: string;
            /** Format: password */
            password: string;
        };
        LoginResponse: {
            user: components["schemas"]["PublicUser"];
            token?: string;
            /** Format: date-time */
            expires_at: string;
            auth_method: string;
        };
        Model: {
            id: string;
            object?: string;
            /** Format: int64 */
            created?: number;
            owned_by?: string;
            type?: string;
            /** Format: int64 */
            size?: number;
            size_gb?: string;
            loaded?: boolean;
            context_window?: number;
            /** @description OpenAI-compatible alias for context_window. */
            context_length?: number;
            capabilities?: string[];
        };
        IntegrationStatus: {
            id: string;
            /** @constant */
            provider_id: "offgrid";
            plugin_id: string;
            name: string;
            description: string;
            /** @constant */
            transport: "openai-chat-completions";
            /** Format: uri */
            documentation_url: string;
            minimum_context: number;
            recommended_context: number;
            requires_tools: boolean;
            capabilities: string[];
            ready: boolean;
            /** @enum {string} */
            status: "ready" | "needs_configuration";
            model_id?: string;
            context_window: number;
            warnings: string[];
        };
        IntegrationList: {
            /** @constant */
            provider: "offgrid";
            /** Format: uri */
            base_url: string;
            integrations: components["schemas"]["IntegrationStatus"][];
        };
        IntegrationSetup: {
            /** @constant */
            provider_id: "offgrid";
            plugin_id: string;
            install_command: string;
            format: string;
            config_file: string;
            content: string;
            environment?: {
                [key: string]: string;
            };
            verify: string[];
            notes?: string[];
        };
        IntegrationSetupResponse: {
            integration: components["schemas"]["IntegrationStatus"];
            setup: components["schemas"]["IntegrationSetup"];
        };
        CatalogModel: {
            id: string;
            name: string;
            description: string;
            category: string;
            parameters: string;
            size: string;
            /** Format: int64 */
            size_bytes: number;
            repo: string;
            file: string;
            quant: string;
            min_ram_gb: number;
            recommended: boolean;
            provider: string;
            type: string;
            license: string;
        };
        ModelDownloadRequest: {
            repository: string;
            file_name?: string;
            quantization?: string;
            /** @description Stable catalog ID used for the collision-free local filename. */
            model_id?: string;
        };
        DownloadProgress: {
            file_name: string;
            /** Format: int64 */
            bytes_total: number;
            /** Format: int64 */
            bytes_done: number;
            percent: number;
            speed: number;
            /** Format: int64 */
            started_at: number;
            /** @enum {string} */
            status: "downloading" | "complete" | "failed" | "cancelled";
            error?: string;
        };
        Verification: {
            model_id: string;
            file_name: string;
            /** Format: int64 */
            size: number;
            size_gb: string;
            sha256: string;
            verified: boolean;
            message?: string;
        };
        ChatMessage: {
            /** @enum {string} */
            role: "system" | "developer" | "user" | "assistant" | "tool";
            content: string;
            tool_call_id?: string;
            tool_calls?: {
                id: string;
                /** @constant */
                type: "function";
                function: {
                    name: string;
                    arguments: string;
                };
            }[];
        };
        SessionMessage: components["schemas"]["ChatMessage"] & {
            /** Format: date-time */
            timestamp: string;
        };
        ChatSession: {
            name: string;
            model_id: string;
            messages: components["schemas"]["SessionMessage"][];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ChatCompletionRequest: {
            model: string;
            messages: components["schemas"]["ChatMessage"][];
            /** @default false */
            stream: boolean;
            stream_options?: {
                /** @default false */
                include_usage: boolean;
            };
            tools?: {
                /** @constant */
                type: "function";
                function: {
                    name: string;
                    description?: string;
                    parameters?: {
                        [key: string]: unknown;
                    };
                };
            }[];
            tool_choice?: unknown;
            /** @default false */
            use_knowledge_base: boolean;
        };
        ChatCompletionResponse: {
            id: string;
            object: string;
            /** Format: int64 */
            created: number;
            model: string;
            choices: {
                index: number;
                message: components["schemas"]["ChatMessage"];
                finish_reason?: string | null;
            }[];
        };
        Document: {
            id: string;
            name: string;
            content_type: string;
            /** Format: int64 */
            size: number;
            chunk_count: number;
            content_hash?: string;
            index_status?: string;
            last_error?: string;
            /** Format: date-time */
            indexed_at?: string;
            source_retained?: boolean;
            /** Format: date-time */
            created_at: string;
        };
        RAGStatus: {
            enabled: boolean;
            embedding_model?: string;
            stats: {
                [key: string]: unknown;
            };
        };
        ToolApproval: {
            tool: string;
            arguments: {
                [key: string]: unknown;
            };
        };
        AgentRunRequest: {
            model: string;
            prompt: string;
            /** @enum {string} */
            style?: "react" | "cot" | "plan" | "plan-execute";
            max_iterations?: number;
            approved_tool_calls?: components["schemas"]["ToolApproval"][];
        };
        AgentStep: {
            [key: string]: unknown;
        };
        AgentRunResponse: {
            output: string;
            task_id: string;
            run_id: string;
            steps: components["schemas"]["AgentStep"][];
            artifact?: {
                [key: string]: unknown;
            };
        };
        AgentTask: {
            id: string;
            prompt: string;
            status: string;
            result?: string;
            error?: string;
            steps?: components["schemas"]["AgentStep"][];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            started_at?: string;
            /** Format: date-time */
            completed_at?: string;
        };
        ComputerStatus: {
            available: boolean;
            emergency_stop: boolean;
            active_sessions: number;
        };
    };
    responses: {
        /** @description API error */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Authentication required */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        SessionName: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Runtime health */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current authentication state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUser"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Authenticated session */
            200: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session cleared */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status: string;
                    };
                };
            };
        };
    };
    listModels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Installed models */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        object: "list";
                        data: components["schemas"]["Model"][];
                    };
                };
            };
        };
    };
    listCatalog: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Curated model catalog */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        total: number;
                        models: components["schemas"]["CatalogModel"][];
                    };
                };
            };
        };
    };
    downloadModel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelDownloadRequest"];
            };
        };
        responses: {
            /** @description Download accepted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        status: string;
                        file_name: string;
                        message?: string;
                    };
                };
            };
            409: components["responses"]["Error"];
        };
    };
    getDownloadProgress: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Download state keyed by destination filename */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["DownloadProgress"];
                    };
                };
            };
        };
    };
    cancelDownload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    file_name: string;
                };
            };
        };
        responses: {
            /** @description Cancellation result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        cancelled: boolean;
                        message?: string;
                    };
                };
            };
        };
    };
    deleteModel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    model_id: string;
                };
            };
        };
        responses: {
            /** @description Model deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        message?: string;
                    };
                };
            };
        };
    };
    verifyModel: {
        parameters: {
            query: {
                model: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Full-file SHA-256 result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Verification"];
                };
            };
        };
    };
    listSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Durable conversations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        sessions: components["schemas"]["ChatSession"][];
                    };
                };
            };
        };
    };
    createSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    model_id?: string;
                };
            };
        };
        responses: {
            /** @description Conversation created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatSession"];
                };
            };
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["SessionName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Durable conversation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatSession"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    deleteSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["SessionName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Conversation deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        message?: string;
                    };
                };
            };
        };
    };
    generateSessionTurn: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["SessionName"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    content: string;
                    model_id?: string;
                    /** @default false */
                    use_knowledge_base?: boolean;
                };
            };
        };
        responses: {
            /** @description Complete persisted user/assistant turn */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        session: components["schemas"]["ChatSession"];
                        message: components["schemas"]["SessionMessage"];
                    };
                };
            };
        };
    };
    createChatCompletion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatCompletionRequest"];
            };
        };
        responses: {
            /** @description OpenAI-compatible non-streaming response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatCompletionResponse"];
                };
            };
        };
    };
    listDocuments: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Indexed documents */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        documents: components["schemas"]["Document"][];
                        count: number;
                    };
                };
            };
        };
    };
    getRAGStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Retrieval readiness */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RAGStatus"];
                };
            };
        };
    };
    enableRAG: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    embedding_model: string;
                };
            };
        };
        responses: {
            /** @description Knowledge retrieval enabled and activation persisted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        message: string;
                    };
                };
            };
            400: components["responses"]["Error"];
        };
    };
    ingestDocument: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Document indexed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        document: components["schemas"]["Document"];
                    };
                };
            };
        };
    };
    reindexDocument: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    document_id: string;
                };
            };
        };
        responses: {
            /** @description Document reindexed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                        document: components["schemas"]["Document"];
                    };
                };
            };
        };
    };
    runAgent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentRunRequest"];
            };
        };
        responses: {
            /** @description Completed governed agent run */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentRunResponse"];
                };
            };
            409: components["responses"]["Error"];
        };
    };
    listAgentTasks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Durable agent task states */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentTask"][];
                };
            };
        };
    };
    listAgentTools: {
        parameters: {
            query?: {
                all?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Agent tool catalog */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    setAgentToolEnabled: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    enabled: boolean;
                };
            };
        };
        responses: {
            /** @description Tool state persisted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listMCPServers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Connected MCP servers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    connectMCPServer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    /** Format: uri */
                    url: string;
                };
            };
        };
        responses: {
            /** @description MCP server connected and persisted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    testMCPServer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uri */
                    url: string;
                };
            };
        };
        responses: {
            /** @description MCP connection test result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listCapabilities: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Governed capability descriptors */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listExternalAgentIntegrations: {
        parameters: {
            query?: {
                /** @description Installed chat model to evaluate for integration readiness. */
                model?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description First-party external agent provider integrations and their runtime readiness. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntegrationList"];
                };
            };
        };
    };
    getExternalAgentIntegrationSetup: {
        parameters: {
            query?: {
                model?: string;
                base_url?: string;
                max_output_tokens?: number;
            };
            header?: never;
            path: {
                id: "hermes" | "openclaw";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ready-to-copy native provider setup. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntegrationSetupResponse"];
                };
            };
            400: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    getComputerStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Computer-use driver and safety-controller status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComputerStatus"];
                };
            };
        };
    };
}
