import type { LocaleCode } from './index';
type Copy = { offer: string; restore: string; separate: string; failed: string; restored: string; unidentified: string; dismiss: string };
export const missingConversationText: Record<LocaleCode, string> = {
  en: 'This conversation is no longer available. Its draft is kept. Refresh history or choose New chat; nothing will be resent.',
  fr: 'Cette conversation n’est plus disponible. Son brouillon est conservé. Actualisez l’historique ou choisissez Nouvelle conversation ; rien ne sera renvoyé.',
  es: 'Esta conversación ya no está disponible. Su borrador se conserva. Actualiza el historial o elige Nuevo chat; no se reenviará nada.',
  de: 'Diese Unterhaltung ist nicht mehr verfügbar. Ihr Entwurf bleibt erhalten. Verlauf aktualisieren oder Neuer Chat wählen; nichts wird erneut gesendet.',
  ar: 'هذه المحادثة لم تعد متاحة. مسودتها محفوظة. حدّث السجل أو اختر محادثة جديدة؛ لن يُعاد إرسال شيء.',
  sw: 'Mazungumzo haya hayapatikani tena. Rasimu imehifadhiwa. Onyesha historia upya au chagua mazungumzo mapya; hakuna kitakachotumwa tena.',
  sn: 'Hurukuro iyi haichawanikwi. Zvawanyora zvakachengetwa. Vhurazve nhoroondo kana sarudza hurukuro itsva; hapana chinotumirwazve.',
  nd: 'Ingxoxo le ayisatholakali. Okubhalileyo kugciniwe. Vuselela imbali kumbe ukhethe ingxoxo entsha; akukho okuzathunyelwa futhi.',
  zu: 'Le ngxoxo ayisatholakali. Okubhalile kugciniwe. Vuselela umlando noma ukhethe ingxoxo entsha; akukho okuzothunyelwa futhi.',
};
export const draftRecoveryText: Record<LocaleCode, Copy> = {
  en: { offer: 'Previous drafts have no workspace identity. Restore copies here? Originals and newer drafts will be kept. Nothing will be sent.', restore: 'Restore previous drafts here', separate: 'Keep separate', failed: 'Draft restoration could not be saved. Originals are preserved. Check browser storage and try again.', restored: 'Previous drafts copied where no newer draft exists. Originals are preserved; nothing was sent.', unidentified: 'This service has no workspace identity. Drafts stay in this session only; old drafts are not loaded.', dismiss: 'Dismiss' },
  fr: { offer: 'Les anciens brouillons ne sont liés à aucun espace. Restaurer des copies ici ? Les originaux et les brouillons récents seront conservés. Rien ne sera envoyé.', restore: 'Restaurer les anciens brouillons ici', separate: 'Garder séparés', failed: 'Restauration non enregistrée. Les originaux sont conservés. Vérifiez le stockage du navigateur et réessayez.', restored: 'Brouillons copiés si aucun brouillon plus récent n’existe. Originaux conservés ; rien envoyé.', unidentified: 'Ce service n’a pas d’identité d’espace. Les brouillons restent dans cette session ; les anciens ne sont pas chargés.', dismiss: 'Fermer' },
  es: { offer: 'Los borradores anteriores no tienen espacio identificado. ¿Restaurar copias aquí? Se conservarán los originales y los más recientes. No se enviará nada.', restore: 'Restaurar borradores anteriores aquí', separate: 'Mantener separados', failed: 'No se pudo guardar la restauración. Los originales se conservan. Revisa el almacenamiento del navegador y reintenta.', restored: 'Borradores copiados donde no había uno más reciente. Originales conservados; no se envió nada.', unidentified: 'Este servicio no identifica el espacio. Los borradores solo duran esta sesión; no se cargan los anteriores.', dismiss: 'Cerrar' },
  de: { offer: 'Ältere Entwürfe haben keine Arbeitsbereichskennung. Kopien hier wiederherstellen? Originale und neuere Entwürfe bleiben erhalten. Nichts wird gesendet.', restore: 'Ältere Entwürfe hier wiederherstellen', separate: 'Getrennt behalten', failed: 'Wiederherstellung konnte nicht gespeichert werden. Originale bleiben erhalten. Browserspeicher prüfen und erneut versuchen.', restored: 'Entwürfe kopiert, sofern kein neuerer vorhanden ist. Originale erhalten; nichts gesendet.', unidentified: 'Dieser Dienst hat keine Arbeitsbereichskennung. Entwürfe bleiben nur in dieser Sitzung; ältere werden nicht geladen.', dismiss: 'Schließen' },
  ar: { offer: 'المسودات السابقة غير مرتبطة بمساحة عمل. هل تريد استعادة نسخ هنا؟ ستُحفظ الأصول والمسودات الأحدث ولن يُرسل شيء.', restore: 'استعادة المسودات السابقة هنا', separate: 'إبقاؤها منفصلة', failed: 'تعذر حفظ الاستعادة. الأصول محفوظة. تحقق من تخزين المتصفح وحاول مجددًا.', restored: 'نُسخت المسودات التي لا توجد نسخة أحدث منها. الأصول محفوظة ولم يُرسل شيء.', unidentified: 'لا توجد هوية لمساحة عمل هذه الخدمة. تبقى المسودات في هذه الجلسة فقط؛ لا تُحمّل المسودات القديمة.', dismiss: 'إغلاق' },
  sw: { offer: 'Rasimu za awali hazina utambulisho wa eneo la kazi. Urejeshe nakala hapa? Asili na rasimu mpya zitahifadhiwa. Hakuna kitakachotumwa.', restore: 'Rejesha rasimu za awali hapa', separate: 'Ziweke tofauti', failed: 'Urejeshaji haukuhifadhiwa. Asili zimehifadhiwa. Kagua hifadhi ya kivinjari na ujaribu tena.', restored: 'Rasimu zimenakiliwa pale pasipo rasimu mpya. Asili zimehifadhiwa; hakuna kilichotumwa.', unidentified: 'Huduma hii haina utambulisho wa eneo la kazi. Rasimu zinabaki katika kipindi hiki tu; za zamani hazipakuliwi.', dismiss: 'Funga' },
  sn: { offer: 'Zvinyorwa zvekare hazvina nzvimbo yebasa yakatarwa. Dzorera makopi pano? Zvekutanga nezvitsva zvichachengetwa. Hapana chinotumirwa.', restore: 'Dzorera zvinyorwa zvekare pano', separate: 'Zvisiye zvakaparadzana', failed: 'Kudzorera hakuna kuchengetwa. Zvekutanga zviripo. Tarisa kuchengetwa kwebhurawuza woedza zvakare.', restored: 'Zvinyorwa zvakakopwa pasina zvitsva zviripo. Zvekutanga zviripo; hapana chatumirwa.', unidentified: 'Sevhisi iyi haina chitupa chenzvimbo yebasa. Zvinyorwa zvinongogara muchikamu chino; zvekare hazvivhurwi.', dismiss: 'Vhara' },
  nd: { offer: 'Okusalungiswa kwakudala akulandawo yomsebenzi eyaziwayo. Buyisela amakhophi lapha? Okwakuqala lokutsha kuzagcinwa. Akukho okuzathunyelwa.', restore: 'Buyisela okusalungiswa kwakudala lapha', separate: 'Kugcine kwehlukene', failed: 'Ukubuyisela akugcinwanga. Okwakuqala kusekhona. Hlola indawo yesiphequluli uzame futhi.', restored: 'Okusalungiswa kukopishiwe lapho okungelakho okutsha. Okwakuqala kusekhona; akukho okuthunyelweyo.', unidentified: 'Le sevisi ayilabunikazi bendawo yomsebenzi. Okusalungiswa kuhlala kulesi sikhathi kuphela; okudala akuvulwa.', dismiss: 'Vala' },
  zu: { offer: 'Okusalungiswa okudala akunandawo yomsebenzi eyaziwayo. Buyisela amakhophi lapha? Okwasekuqaleni nokusha kuzogcinwa. Akukho okuzothunyelwa.', restore: 'Buyisela okusalungiswa okudala lapha', separate: 'Kugcine kwehlukene', failed: 'Ukubuyisela akugcinwanga. Okwasekuqaleni kugciniwe. Hlola isitoreji sesiphequluli bese uzama futhi.', restored: 'Okusalungiswa kukopishiwe lapho kungekho okusha. Okwasekuqaleni kugciniwe; akukho okuthunyelwe.', unidentified: 'Le sevisi ayinabunikazi bendawo yomsebenzi. Okusalungiswa kuhlala kulesi sikhathi kuphela; okudala akulayishwa.', dismiss: 'Vala' },
};
