import type { LocaleCode } from './index';

export const interaction = {
  en: {"adminOnly":"Administrator access required","refreshHistory":"Refresh history","checkRequest":"Check request status","knowledgeUnavailable":"Knowledge is unavailable. Configure it in Knowledge before enabling it here.","noEvents":"No events recorded for this task.","stopAfterCurrent":"Stop after current item","deleteProgress":"{done} of {total} processed","historyFailed":"History refresh failed","loadingHistory":"Preparing history…"},
  fr: {"adminOnly":"Accès administrateur requis","refreshHistory":"Actualiser l’historique","checkRequest":"Vérifier la demande","knowledgeUnavailable":"La base de connaissances est indisponible. Configurez-la avant de l’activer ici.","noEvents":"Aucun événement enregistré pour cette tâche.","stopAfterCurrent":"Arrêter après l’élément en cours","deleteProgress":"{done} sur {total} traités","historyFailed":"Échec de l’actualisation de l’historique","loadingHistory":"Chargement de l’historique…"},
  de: {"adminOnly":"Administratorzugriff erforderlich","refreshHistory":"Verlauf aktualisieren","checkRequest":"Anfragestatus prüfen","knowledgeUnavailable":"Wissensabruf ist nicht verfügbar. Richten Sie ihn zuerst unter Wissen ein.","noEvents":"Keine Ereignisse für diese Aufgabe gespeichert.","stopAfterCurrent":"Nach aktuellem Eintrag stoppen","deleteProgress":"{done} von {total} verarbeitet","historyFailed":"Verlauf konnte nicht aktualisiert werden","loadingHistory":"Verlauf wird geladen…"},
  es: {"adminOnly":"Se requiere acceso de administrador","refreshHistory":"Actualizar historial","checkRequest":"Comprobar solicitud","knowledgeUnavailable":"La base de conocimiento no está disponible. Configúrela antes de activarla aquí.","noEvents":"No hay eventos registrados para esta tarea.","stopAfterCurrent":"Detener tras el elemento actual","deleteProgress":"{done} de {total} procesados","historyFailed":"No se pudo actualizar el historial","loadingHistory":"Cargando historial…"},
  ar: {"adminOnly":"يلزم وصول المسؤول","refreshHistory":"تحديث السجل","checkRequest":"التحقق من حالة الطلب","knowledgeUnavailable":"المعرفة غير متاحة. قم بإعدادها قبل تفعيلها هنا.","noEvents":"لا توجد أحداث مسجلة لهذه المهمة.","stopAfterCurrent":"التوقف بعد العنصر الحالي","deleteProgress":"تمت معالجة {done} من {total}","historyFailed":"تعذر تحديث السجل","loadingHistory":"جارٍ تحميل السجل…"},
  sw: {"adminOnly":"Ufikiaji wa msimamizi unahitajika","refreshHistory":"Onyesha historia upya","checkRequest":"Angalia hali ya ombi","knowledgeUnavailable":"Maarifa hayapatikani. Yasanidi kabla ya kuyawezesha hapa.","noEvents":"Hakuna matukio yaliyorekodiwa kwa kazi hii.","stopAfterCurrent":"Simama baada ya kipengee hiki","deleteProgress":"{done} kati ya {total} vimeshughulikiwa","historyFailed":"Imeshindwa kuonyesha historia upya","loadingHistory":"Inapakia historia…"},
  sn: {"adminOnly":"Mvumo yemutungamiriri inodiwa","refreshHistory":"Vandudza nhoroondo","checkRequest":"Tarisa mamiriro echikumbiro","knowledgeUnavailable":"Ruzivo haruwaniki. Rwugadzirire usati warubatidza pano.","noEvents":"Hapana zviitiko zvakachengetwa zvebasa iri.","stopAfterCurrent":"Mira kana chinhu ichi chapera","deleteProgress":"{done} pa{total} zvagadziriswa","historyFailed":"Kuvandudza nhoroondo kwakundikana","loadingHistory":"Nhoroondo iri kuiswa…"},
  nd: {"adminOnly":"Kudingeka imvumo yomlawuli","refreshHistory":"Vuselela imbali","checkRequest":"Hlola isimo sesicelo","knowledgeUnavailable":"Ulwazi alutholakali. Lulungise ngaphambi kokuluvula lapha.","noEvents":"Akulazehlakalo ezirekhodiweyo zalumsebenzi.","stopAfterCurrent":"Yima ngemva kwalinto","deleteProgress":"{done} kokungu {total} sekucutshunguliwe","historyFailed":"Ukuvuselela imbali kwehlulekile","loadingHistory":"Kulayitshwa imbali…"},
  zu: {"adminOnly":"Kudingeka ukufinyelela komlawuli","refreshHistory":"Vuselela umlando","checkRequest":"Hlola isimo sesicelo","knowledgeUnavailable":"Ulwazi alutholakali. Lulungise ngaphambi kokuluvula lapha.","noEvents":"Azikho izehlakalo ezirekhodiwe zalo msebenzi.","stopAfterCurrent":"Yima ngemva kwento yamanje","deleteProgress":"{done} kokungu {total} kucutshunguliwe","historyFailed":"Ukuvuselela umlando kuhlulekile","loadingHistory":"Kulayishwa umlando…"},
} satisfies Record<LocaleCode, Record<'adminOnly' | 'refreshHistory' | 'checkRequest' | 'knowledgeUnavailable' | 'noEvents' | 'stopAfterCurrent' | 'deleteProgress' | 'historyFailed' | 'loadingHistory', string>>;
