import type { LocaleCode } from './index';

type Copy = {
  category: string; language: string; embeddings: string; speech_recognition: string; speech_generation: string;
  preview: string; select?: string; variant: string; source: string; license: string; transfer: string; space: string;
  files: string; runtime: string; runtimeNotice?: string; advanced: string; operations: string; retained: string; discard: string;
  discardConfirm: string; repair: string; localRepair: string; emptyVariants: string;
  queued: string; downloading: string; verifying: string; activating: string; cancelling: string;
  complete: string; cancelled: string; failed: string; interrupted: string;
};
export const modelAcquisition: Record<LocaleCode, Copy> = {
  en: { category: 'Model category', language: 'Language', embeddings: 'Embeddings', speech_recognition: 'Speech recognition', speech_generation: 'Speech generation', preview: 'Review download', variant: 'Model variant', source: 'Source revision', license: 'Licenses', transfer: 'Download size', space: 'Required free space', files: 'Package files', runtime: 'Installed package; the matching local speech runtime adapter is not available in this build yet.', advanced: 'Advanced · offline import', operations: 'Downloads', retained: 'Retained data', discard: 'Discard partial data', discardConfirm: 'Remove this operation’s retained download and recovery data? Installed models and user documents are preserved.', repair: 'Repair package', localRepair: 'This package is installed. Repair is only needed after an integrity failure.', emptyVariants: 'No complete supported speech package was found in this repository.', queued: 'Queued', downloading: 'Downloading', verifying: 'Verifying', activating: 'Installing', cancelling: 'Stopping', complete: 'Installed', cancelled: 'Cancelled', failed: 'Needs attention', interrupted: 'Interrupted' },
  fr: { category: 'Catégorie de modèle', language: 'Langage', embeddings: 'Représentations vectorielles', speech_recognition: 'Reconnaissance vocale', speech_generation: 'Synthèse vocale', preview: 'Vérifier le téléchargement', variant: 'Variante', source: 'Révision source', license: 'Licences', transfer: 'Taille du téléchargement', space: 'Espace libre requis', files: 'Fichiers du paquet', runtime: 'Le moteur vocal n’est pas disponible dans cette version. Installer des modèles n’active pas encore la voix.', advanced: 'Avancé · import hors ligne', operations: 'Téléchargements', retained: 'Données conservées', discard: 'Supprimer les données partielles', discardConfirm: 'Supprimer les données de téléchargement et de récupération conservées ? Les modèles installés et les documents sont préservés.', repair: 'Réparer', localRepair: 'Réimportez ce paquet local pour le réparer.', emptyVariants: 'Aucun paquet vocal complet et compatible trouvé.', queued: 'En attente', downloading: 'Téléchargement', verifying: 'Vérification', activating: 'Installation', cancelling: 'Arrêt', complete: 'Installé', cancelled: 'Annulé', failed: 'Intervention requise', interrupted: 'Interrompu' },
  es: { category: 'Categoría del modelo', language: 'Lenguaje', embeddings: 'Representaciones vectoriales', speech_recognition: 'Reconocimiento de voz', speech_generation: 'Síntesis de voz', preview: 'Revisar descarga', variant: 'Variante', source: 'Revisión de origen', license: 'Licencias', transfer: 'Tamaño de descarga', space: 'Espacio libre necesario', files: 'Archivos del paquete', runtime: 'El motor de voz no está disponible en esta versión. Instalar modelos todavía no activa la voz.', advanced: 'Avanzado · importación sin conexión', operations: 'Descargas', retained: 'Datos conservados', discard: 'Descartar datos parciales', discardConfirm: '¿Eliminar los datos de descarga y recuperación conservados? Los modelos instalados y documentos se conservan.', repair: 'Reparar', localRepair: 'Importa de nuevo este paquete local para repararlo.', emptyVariants: 'No se encontró un paquete de voz completo y compatible.', queued: 'En cola', downloading: 'Descargando', verifying: 'Verificando', activating: 'Instalando', cancelling: 'Deteniendo', complete: 'Instalado', cancelled: 'Cancelado', failed: 'Requiere atención', interrupted: 'Interrumpido' },
  de: { category: 'Modellkategorie', language: 'Sprache', embeddings: 'Einbettungen', speech_recognition: 'Spracherkennung', speech_generation: 'Sprachausgabe', preview: 'Download prüfen', variant: 'Modellvariante', source: 'Quellrevision', license: 'Lizenzen', transfer: 'Downloadgröße', space: 'Benötigter freier Speicher', files: 'Paketdateien', runtime: 'Die Sprachlaufzeit ist in dieser Version nicht verfügbar. Die Modellinstallation aktiviert noch keine Sprachfunktionen.', advanced: 'Erweitert · Offline-Import', operations: 'Downloads', retained: 'Aufbewahrte Daten', discard: 'Teildaten verwerfen', discardConfirm: 'Aufbewahrte Download- und Wiederherstellungsdaten entfernen? Installierte Modelle und Dokumente bleiben erhalten.', repair: 'Reparieren', localRepair: 'Dieses lokale Paket zur Reparatur erneut importieren.', emptyVariants: 'Kein vollständiges unterstütztes Sprachpaket gefunden.', queued: 'Wartend', downloading: 'Herunterladen', verifying: 'Prüfen', activating: 'Installieren', cancelling: 'Anhalten', complete: 'Installiert', cancelled: 'Abgebrochen', failed: 'Eingriff erforderlich', interrupted: 'Unterbrochen' },
  ar: { category: 'فئة النموذج', language: 'اللغة', embeddings: 'التضمينات', speech_recognition: 'التعرف على الكلام', speech_generation: 'توليد الكلام', preview: 'مراجعة التنزيل', variant: 'نسخة النموذج', source: 'مراجعة المصدر', license: 'التراخيص', transfer: 'حجم التنزيل', space: 'المساحة الحرة المطلوبة', files: 'ملفات الحزمة', runtime: 'محرك الصوت غير متاح في هذا الإصدار. تثبيت النماذج لا يفعّل الصوت بعد.', advanced: 'متقدم · استيراد دون اتصال', operations: 'التنزيلات', retained: 'البيانات المحفوظة', discard: 'حذف البيانات الجزئية', discardConfirm: 'حذف بيانات التنزيل والاسترداد المحفوظة؟ ستبقى النماذج المثبتة والمستندات محفوظة.', repair: 'إصلاح', localRepair: 'أعد استيراد هذه الحزمة المحلية لإصلاحها.', emptyVariants: 'لم يتم العثور على حزمة صوت كاملة ومدعومة.', queued: 'في الانتظار', downloading: 'جارٍ التنزيل', verifying: 'جارٍ التحقق', activating: 'جارٍ التثبيت', cancelling: 'جارٍ الإيقاف', complete: 'مثبت', cancelled: 'ملغى', failed: 'يحتاج إلى عناية', interrupted: 'متوقف' },
  sw: { category: 'Aina ya modeli', language: 'Lugha', embeddings: 'Uwakilishi wa vekta', speech_recognition: 'Utambuzi wa usemi', speech_generation: 'Uzalishaji wa usemi', preview: 'Kagua upakuaji', variant: 'Toleo la modeli', source: 'Toleo la chanzo', license: 'Leseni', transfer: 'Ukubwa wa upakuaji', space: 'Nafasi huru inayohitajika', files: 'Faili za kifurushi', runtime: 'Injini ya sauti haipatikani katika toleo hili. Kusakinisha modeli bado hakuwashi sauti.', advanced: 'Mahiri · ingiza bila mtandao', operations: 'Vipakuliwa', retained: 'Data iliyohifadhiwa', discard: 'Futa data ya sehemu', discardConfirm: 'Futa data ya upakuaji na urejeshaji iliyohifadhiwa? Modeli na hati zako zitahifadhiwa.', repair: 'Rekebisha', localRepair: 'Ingiza kifurushi hiki cha ndani tena ili kukirekebisha.', emptyVariants: 'Hakuna kifurushi kamili cha sauti kinachotumika kilichopatikana.', queued: 'Kwenye foleni', downloading: 'Inapakua', verifying: 'Inathibitisha', activating: 'Inasakinisha', cancelling: 'Inasimama', complete: 'Imesakinishwa', cancelled: 'Imeghairiwa', failed: 'Inahitaji uangalizi', interrupted: 'Imekatizwa' },
  sn: { category: 'Rudzi rwemodheru', language: 'Mutauro', embeddings: 'Mavekta', speech_recognition: 'Kuziva kutaura', speech_generation: 'Kugadzira kutaura', preview: 'Ongorora kudhaunirodha', variant: 'Vhezheni yemodheru', source: 'Vhezheni yekwakabva', license: 'Marezinesi', transfer: 'Ukuru hwekudhaunirodha', space: 'Nzvimbo isina chinhu inodiwa', files: 'Mafaira epakeji', runtime: 'Injini yezwi haisipo muvhezheni iyi. Kuisa mamodheru hakusati kwabatidza izwi.', advanced: 'Zvepamusoro · pinza pasina dandemutande', operations: 'Zviri kudhaunirodhwa', retained: 'Data yakachengetwa', discard: 'Bvisa data isina kupera', discardConfirm: 'Bvisa data yekudhaunirodha nekudzorera yakachengetwa? Mamodheru akaiswa nemagwaro zvinochengetwa.', repair: 'Gadzirisa', localRepair: 'Pinza pakeji iyi zvakare kuti uigadzirise.', emptyVariants: 'Hapana pakeji yezwi yakazara inotsigirwa yawanikwa.', queued: 'Yakamirira', downloading: 'Iri kudhaunirodha', verifying: 'Iri kuongororwa', activating: 'Iri kuiswa', cancelling: 'Iri kumira', complete: 'Yakaiswa', cancelled: 'Yamiswa', failed: 'Inoda kutariswa', interrupted: 'Yakakanganiswa' },
  nd: { category: 'Uhlobo lwemodeli', language: 'Ulimi', embeddings: 'Amavekta', speech_recognition: 'Ukubona inkulumo', speech_generation: 'Ukwenza inkulumo', preview: 'Hlola ukulanda', variant: 'Inguqulo yemodeli', source: 'Inguqulo yomthombo', license: 'Amalayisensi', transfer: 'Ubukhulu bokulanda', space: 'Isikhala esidingekayo', files: 'Amafayela ephakheji', runtime: 'Injini yelizwi ayitholakali kule inguqulo. Ukufaka amamodeli akukavuli ilizwi.', advanced: 'Okuthuthukileyo · ngenisa ungaxhunyiwe', operations: 'Okulandwayo', retained: 'Idatha egciniweyo', discard: 'Susa idatha engaphelelanga', discardConfirm: 'Susa idatha yokulanda leyokubuyisela egciniweyo? Amamodeli lamadokhumenti kuyagcinwa.', repair: 'Lungisa', localRepair: 'Ngenisa leli phakheji futhi ukuze ulilungise.', emptyVariants: 'Alitholakalanga iphakheji yelizwi epheleleyo esekelwayo.', queued: 'Ilindile', downloading: 'Iyalanda', verifying: 'Iyahlola', activating: 'Iyafaka', cancelling: 'Iyamisa', complete: 'Ifakiwe', cancelled: 'Imisiwe', failed: 'Kudinga ukunakwa', interrupted: 'Iphazamisekile' },
  zu: { category: 'Uhlobo lwemodeli', language: 'Ulimi', embeddings: 'Amavektha', speech_recognition: 'Ukubona inkulumo', speech_generation: 'Ukwenza inkulumo', preview: 'Hlola ukulanda', variant: 'Inguqulo yemodeli', source: 'Inguqulo yomthombo', license: 'Amalayisensi', transfer: 'Usayizi wokulanda', space: 'Isikhala esidingekayo', files: 'Amafayela ephakheji', runtime: 'Injini yezwi ayitholakali kule nguqulo. Ukufaka amamodeli akukavuli izwi.', advanced: 'Okuthuthukile · ngenisa ungaxhunyiwe', operations: 'Okulandwayo', retained: 'Idatha egciniwe', discard: 'Susa idatha engaphelele', discardConfirm: 'Susa idatha yokulanda neyokubuyisela egciniwe? Amamodeli namadokhumenti kuyagcinwa.', repair: 'Lungisa', localRepair: 'Ngenisa leli phakheji futhi ukuze ulilungise.', emptyVariants: 'Alitholakalanga iphakheji yezwi ephelele esekelwayo.', queued: 'Ilindile', downloading: 'Iyalanda', verifying: 'Iyaqinisekisa', activating: 'Iyafaka', cancelling: 'Iyamisa', complete: 'Ifakiwe', cancelled: 'Ikhanseliwe', failed: 'Kudinga ukunakwa', interrupted: 'Iphazamisekile' }
};
