import type { LocaleCode } from './index';

type Copy = { title: string; hint: string; folder: string; import: string; invalid: string; checked: string; unchecked: string; failed: string; runtime: string; remove: string; inUse: string };
export const speechModels: Record<LocaleCode, Copy> = {
  en: { title: 'Speech model packages', hint: 'Choose a reviewed package to download from the catalog, or use offline import when you already have a verified package. Runtime readiness is shown on each package.', folder: 'Choose a package folder', import: 'Import package', invalid: 'Choose a folder with manifest.json and exactly its declared files. Check missing files and sizes.', checked: 'Integrity checked', unchecked: 'Integrity not checked this session', failed: 'Needs repair', runtime: 'Installed package; its local speech runtime adapter is not available in this build yet.', remove: 'Remove this managed package revision? Original imports and user documents are kept.', inUse: 'In use' },
  fr: { title: 'Modèles vocaux', hint: 'En développement : gérez les fichiers locaux. Leur importation n’active pas la voix ; l’intégration des moteurs reste en développement. Aucun code n’est exécuté ni téléchargé.', folder: 'Choisir un dossier de modèle', import: 'Importer le modèle', invalid: 'Choisissez un dossier contenant manifest.json et exactement les fichiers déclarés. Vérifiez les fichiers et leurs tailles.', checked: 'Intégrité vérifiée', unchecked: 'Intégrité non vérifiée pour cette session', failed: 'Réparation nécessaire', runtime: 'Moteur vocal indisponible — non qualifié pour la voix', remove: 'Supprimer cette révision gérée ? Les originaux et documents sont conservés.', inUse: 'En cours d’utilisation' },
  es: { title: 'Paquetes de modelos de voz', hint: 'En desarrollo: gestione archivos locales. Importarlos no activa la voz; la integración de motores sigue en desarrollo. No se ejecuta ni descarga código.', folder: 'Elegir carpeta del paquete', import: 'Importar paquete', invalid: 'Elija una carpeta con manifest.json y exactamente sus archivos declarados. Compruebe los archivos y tamaños.', checked: 'Integridad verificada', unchecked: 'Integridad sin verificar en esta sesión', failed: 'Necesita reparación', runtime: 'Motor de voz no disponible — sin calificación para voz', remove: '¿Eliminar esta revisión? Se conservan los originales y documentos.', inUse: 'En uso' },
  de: { title: 'Sprachmodellpakete', hint: 'In Entwicklung: lokale Modelldateien verwalten. Der Import aktiviert keine Sprachfunktion; die Laufzeitintegration ist noch in Entwicklung. Kein Code wird ausgeführt oder heruntergeladen.', folder: 'Paketordner auswählen', import: 'Paket importieren', invalid: 'Ordner mit manifest.json und genau den angegebenen Dateien wählen. Dateien und Größen prüfen.', checked: 'Integrität geprüft', unchecked: 'Integrität in dieser Sitzung nicht geprüft', failed: 'Reparatur erforderlich', runtime: 'Sprachlaufzeit nicht verfügbar — nicht für Sprache qualifiziert', remove: 'Diese verwaltete Version entfernen? Originale und Dokumente bleiben erhalten.', inUse: 'In Verwendung' },
  ar: { title: 'حزم نماذج الصوت', hint: 'قيد التطوير: إدارة ملفات النماذج المحلية. الاستيراد لا يفعّل الصوت؛ دمج المحركات ما زال قيد التطوير. لا يتم تشغيل أو تنزيل أي شيفرة.', folder: 'اختيار مجلد الحزمة', import: 'استيراد الحزمة', invalid: 'اختر مجلداً يحتوي على manifest.json والملفات المحددة فيه فقط. تحقق من الملفات وأحجامها.', checked: 'تم التحقق من السلامة', unchecked: 'لم تُفحص السلامة في هذه الجلسة', failed: 'تحتاج إلى إصلاح', runtime: 'محرك الصوت غير متاح — لم يتم تأهيل الصوت', remove: 'حذف هذا الإصدار المُدار؟ تُحفظ الملفات الأصلية والمستندات.', inUse: 'قيد الاستخدام' },
  sw: { title: 'Vifurushi vya modeli za sauti', hint: 'Inatengenezwa: dhibiti faili za ndani. Kuziingiza hakuanzishi sauti; ujumuishaji wa injini bado unatengenezwa. Hakuna msimbo unaoendeshwa au kupakuliwa.', folder: 'Chagua folda ya kifurushi', import: 'Ingiza kifurushi', invalid: 'Chagua folda yenye manifest.json na faili zilizotajwa pekee. Kagua faili na ukubwa wake.', checked: 'Uadilifu umethibitishwa', unchecked: 'Uadilifu haujakaguliwa katika kipindi hiki', failed: 'Inahitaji ukarabati', runtime: 'Injini ya sauti haipatikani — haijathibitishwa kwa sauti', remove: 'Ondoa toleo hili? Faili asili na hati zinahifadhiwa.', inUse: 'Inatumika' },
  sn: { title: 'Mapakeji emamodheru ezwi', hint: 'Zvichiri kugadzirwa: gadzirisa mafaera epano. Kuapinza hakubatidzi izwi; injini dzichiri kubatanidzwa. Hapana kodhi inomhanyiswa kana kudhaunirodhwa.', folder: 'Sarudza folda yepakeji', import: 'Pinza pakeji', invalid: 'Sarudza folda ine manifest.json nemafaera akanyorwa mairi chete. Tarisa mafaera nehukuru hwawo.', checked: 'Kutendeseka kwaongororwa', unchecked: 'Hakusati kwaongororwa muchikamu chino', failed: 'Inoda kugadziriswa', runtime: 'Injini yezwi haisipo — haisati yasimbiswa yezwi', remove: 'Bvisa vhezheni iyi? Mafaera ekutanga nemagwaro zvinochengetwa.', inUse: 'Iri kushandiswa' },
  nd: { title: 'Amaphakheji amamodeli elizwi', hint: 'Kusakhiwa: phatha amafayela akule khompyutha. Ukuwangenisa akuqalisi ilizwi; ukuhlanganiswa kwezinjini kusaqhubeka. Akulakhodi esebenzayo loba elandwayo.', folder: 'Khetha ifolda yephakheji', import: 'Ngenisa iphakheji', invalid: 'Khetha ifolda ele-manifest.json lamafayela abhalwe kuyo kuphela. Hlola amafayela lobukhulu bawo.', checked: 'Ubuqotho buhloliwe', unchecked: 'Ubuqotho abuhlolwanga kulesi sigaba', failed: 'Kudinga ukulungiswa', runtime: 'Injini yelizwi ayitholakali — ayikaqinisekiswa', remove: 'Susa le nguqulo? Amafayela okuqala lamadokhumenti kuyagcinwa.', inUse: 'Iyasetshenziswa' },
  zu: { title: 'Amaphakheji amamodeli ezwi', hint: 'Kusakhiwa: phatha amafayela akule khompyutha. Ukuwangenisa akuvuli izwi; ukuhlanganiswa kwezinjini kusaqhubeka. Akukho khodi esetshenziswayo noma elandiwayo.', folder: 'Khetha ifolda yephakheji', import: 'Ngenisa iphakheji', invalid: 'Khetha ifolda ene-manifest.json namafayela abhalwe kuyo kuphela. Hlola amafayela nosayizi bawo.', checked: 'Ubuqotho buhloliwe', unchecked: 'Ubuqotho abukahlolwa kulesi sikhathi', failed: 'Kudinga ukulungiswa', runtime: 'Injini yezwi ayitholakali — ayikaqinisekiswa', remove: 'Susa le nguqulo? Amafayela okuqala namadokhumenti ayagcinwa.', inUse: 'Iyasetshenziswa' }
};
