import type { LocaleCode } from './index';

type Labels = readonly [string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string];
const labels: Record<LocaleCode, Labels> = {
  en: ['This approval has expired. Check the current task; refreshing does not approve or resume it.', 'Expires', 'This tool’s effects are not described here. Review the exact arguments before approving.', 'Exact action', 'Saved answer', 'Generated content is not independent verification. Inspect the files and recorded evidence.', 'Output files', 'File integrity checked', 'Not verified', 'The recorded check covers stored bytes and format, not factual correctness.', 'Download', 'File unavailable. Check task access and refresh its saved state.', 'No inline preview. Download the file to inspect it.', 'Next step', 'This task cannot accept an instruction in its current state. A new draft does not change or rerun this task.', 'Start a new task from this'],
  fr: ['Cette autorisation a expiré. Vérifiez la tâche ; actualiser ne l’approuve ni ne la reprend.', 'Expire', 'Les effets de cet outil ne sont pas décrits ici. Vérifiez les arguments exacts avant d’approuver.', 'Action exacte', 'Réponse enregistrée', 'Le contenu généré n’est pas une vérification indépendante. Consultez les fichiers et les preuves.', 'Fichiers produits', 'Intégrité du fichier vérifiée', 'Non vérifié', 'La vérification porte sur les octets et le format, pas sur l’exactitude des faits.', 'Télécharger', 'Fichier indisponible. Vérifiez l’accès et actualisez la tâche.', 'Aucun aperçu intégré. Téléchargez le fichier pour l’inspecter.', 'Étape suivante', 'Cette tâche ne peut pas recevoir de consigne dans son état actuel. Un nouveau brouillon ne la modifie ni ne la relance.', 'Créer une tâche à partir de celle-ci'],
  es: ['Esta aprobación ha caducado. Comprueba la tarea; actualizar no la aprueba ni reanuda.', 'Caduca', 'Los efectos de esta herramienta no se describen aquí. Revisa los argumentos exactos antes de aprobar.', 'Acción exacta', 'Respuesta guardada', 'El contenido generado no es una verificación independiente. Revisa los archivos y las pruebas.', 'Archivos de salida', 'Integridad del archivo comprobada', 'Sin verificar', 'La comprobación cubre bytes y formato, no la exactitud de los hechos.', 'Descargar', 'Archivo no disponible. Comprueba el acceso y actualiza la tarea.', 'Sin vista previa. Descarga el archivo para inspeccionarlo.', 'Siguiente paso', 'Esta tarea no acepta instrucciones en su estado actual. Un borrador nuevo no la cambia ni la repite.', 'Crear una tarea a partir de esta'],
  de: ['Diese Freigabe ist abgelaufen. Aufgabenstatus prüfen; Aktualisieren genehmigt oder startet nichts.', 'Läuft ab', 'Die Auswirkungen dieses Werkzeugs sind hier nicht beschrieben. Vor der Freigabe die genauen Argumente prüfen.', 'Genaue Aktion', 'Gespeicherte Antwort', 'Generierte Inhalte sind kein unabhängiger Nachweis. Dateien und gespeicherte Belege prüfen.', 'Ergebnisdateien', 'Dateiintegrität geprüft', 'Nicht geprüft', 'Die Prüfung betrifft gespeicherte Bytes und Format, nicht die sachliche Richtigkeit.', 'Herunterladen', 'Datei nicht verfügbar. Aufgabenzugriff prüfen und Status aktualisieren.', 'Keine eingebettete Vorschau. Datei zur Prüfung herunterladen.', 'Nächster Schritt', 'Diese Aufgabe kann derzeit keine Anweisung erhalten. Ein neuer Entwurf ändert oder wiederholt sie nicht.', 'Neue Aufgabe daraus erstellen'],
  ar: ['انتهت صلاحية الموافقة. افحص المهمة؛ التحديث لا يوافق عليها ولا يستأنفها.', 'تنتهي في', 'آثار هذه الأداة غير موضحة هنا. راجع الوسائط الدقيقة قبل الموافقة.', 'الإجراء الدقيق', 'الإجابة المحفوظة', 'المحتوى المولد ليس تحققًا مستقلًا. افحص الملفات والأدلة المسجلة.', 'ملفات المخرجات', 'تم فحص سلامة الملف', 'غير متحقق منه', 'يشمل الفحص البايتات المخزنة والتنسيق، وليس صحة الحقائق.', 'تنزيل', 'الملف غير متاح. افحص صلاحية الوصول وحدّث حالة المهمة.', 'لا توجد معاينة مضمنة. نزّل الملف لفحصه.', 'الخطوة التالية', 'لا تقبل هذه المهمة تعليمات في حالتها الحالية. المسودة الجديدة لا تعدلها ولا تعيد تشغيلها.', 'إنشاء مهمة جديدة من هذه'],
  sw: ['Idhini hii imeisha muda. Kagua kazi; kuonyesha upya hakuidhinishi wala kuendeleza kazi.', 'Inaisha', 'Athari za zana hii hazijaelezwa hapa. Kagua hoja halisi kabla ya kuidhinisha.', 'Kitendo halisi', 'Jibu lililohifadhiwa', 'Maudhui yaliyotengenezwa si uthibitisho huru. Kagua faili na ushahidi uliorekodiwa.', 'Faili za matokeo', 'Uadilifu wa faili umekaguliwa', 'Haijathibitishwa', 'Ukaguzi unahusu baiti na umbizo, si usahihi wa ukweli.', 'Pakua', 'Faili haipatikani. Kagua ruhusa na uonyeshe hali ya kazi upya.', 'Hakuna hakikisho la ndani. Pakua faili ili kuikagua.', 'Hatua inayofuata', 'Kazi hii haiwezi kupokea maelekezo katika hali hii. Rasimu mpya haibadilishi wala kurudia kazi.', 'Anza kazi mpya kutokana na hii'],
  sn: ['Mvumo iyi yapera. Tarisa basa; kuvandudza hakupi mvumo kana kuenderera naro.', 'Inopera', 'Zvinoitwa nechishandiso ichi hazvina kutsanangurwa pano. Ongorora nharo chaidzo usati wabvumidza.', 'Chiito chaicho', 'Mhinduro yakachengetwa', 'Mashoko akagadzirwa haasi humbowo hwakazvimirira. Ongorora mafaira nehumboo hwakanyorwa.', 'Mafaira emhedzisiro', 'Kuvimbika kwefaira kwaongororwa', 'Hazvina kusimbiswa', 'Kuongorora kunobata mabaiti nefomati, kwete chokwadi chemashoko.', 'Dhaunirodha', 'Faira haripo. Tarisa mvumo uye vandudza mamiriro ebasa.', 'Hapana tarisiro yemukati. Dhaunirodha faira kuti uriongorore.', 'Danho rinotevera', 'Basa iri harigamuchiri murayiro mumamiriro aro. Rasimu itsva haichinji kana kudzokorora basa.', 'Tanga basa idzva kubva pane iri'],
  nd: ['Imvumo le isiphelelwe yisikhathi. Hlola umsebenzi; ukuvuselela akuviunywa njalo akuqhubeki lomsebenzi.', 'Iphela', 'Imiphumela yethuluzi leli ayichazwanga lapha. Hlola amapharamitha aqondileyo ungakavumi.', 'Isenzo esiqondileyo', 'Impendulo egciniweyo', 'Okubhaliweyo yimodeli akusibufakazi obuzimeleyo. Hlola amafayela lobufakazi.', 'Amafayela emiphumela', 'Ubuqotho befayela buhloliwe', 'Akuqinisekiswanga', 'Ukuhlola kuhlanganisa amabhayithi lefomethi, hatshi ubuqiniso bendaba.', 'Dawuniloda', 'Ifayela alitholakali. Hlola imvumo uvuselele isimo somsebenzi.', 'Akukho ukubuka ngaphakathi. Dawuniloda ifayela ulihlole.', 'Isinyathelo esilandelayo', 'Umsebenzi lo awukwazi ukwamukela umlayo kulesi simo. Uhlaka olutsha aluwuguquli kumbe luwuphinde.', 'Qala umsebenzi omutsha ngalokhu'],
  zu: ['Le mvume isiphelelwe yisikhathi. Hlola umsebenzi; ukuvuselela akuwuvumeli noma kuwuqhubekisele phambili.', 'Iphela', 'Imiphumela yaleli thuluzi ayichaziwe lapha. Hlola amapharamitha aqondile ngaphambi kokuvuma.', 'Isenzo esiqondile', 'Impendulo egciniwe', 'Okuqukethwe okukhiqiziwe akubona ubufakazi obuzimele. Hlola amafayela nobufakazi oburekhodiwe.', 'Amafayela emiphumela', 'Ubuqotho befayela buhloliwe', 'Akuqinisekisiwe', 'Ukuhlola kumayelana namabhayithi nefomethi, hhayi ukunemba kwamaqiniso.', 'Landa', 'Ifayela alitholakali. Hlola imvume uvuselele isimo somsebenzi.', 'Akukho ukubuka ngaphakathi. Landa ifayela ukuze ulihlole.', 'Isinyathelo esilandelayo', 'Lo msebenzi awukwazi ukwamukela umyalelo kulesi simo. Uhlaka olusha aluwushintshi noma luwuphinde.', 'Qala umsebenzi omusha ngalokhu'],
};
export function taskPresentation(locale: LocaleCode) {
  const [expired, expires, unknown, exact, answer, generated, files, integrity, unverified, integrityHint, download, unavailable, noPreview, next, newTaskHint, newTask] = labels[locale];
  return { expired, expires, unknown, exact, answer, generated, files, integrity, unverified, integrityHint, download, unavailable, noPreview, next, newTaskHint, newTask };
}

const stop: Record<LocaleCode, readonly [string, string]> = {
  en: ['Stop requested. Waiting for confirmation; already dispatched effects may still finish.', 'Stopping is not confirmed. Inspect the task and any connected application before retrying.'],
  fr: ['Arrêt demandé. En attente de confirmation ; les actions déjà lancées peuvent se terminer.', 'L’arrêt n’est pas confirmé. Vérifiez la tâche et l’application connectée avant de réessayer.'],
  es: ['Parada solicitada. Esperando confirmación; las acciones ya enviadas pueden terminar.', 'La parada no está confirmada. Revisa la tarea y la aplicación conectada antes de reintentar.'],
  de: ['Stopp angefordert. Bestätigung ausstehend; bereits ausgelöste Aktionen können noch enden.', 'Stopp nicht bestätigt. Aufgabe und verbundene Anwendung vor einem erneuten Versuch prüfen.'],
  ar: ['تم طلب الإيقاف. بانتظار التأكيد؛ قد تكتمل الإجراءات المرسلة بالفعل.', 'لم يتم تأكيد الإيقاف. افحص المهمة وأي تطبيق متصل قبل المحاولة مجددًا.'],
  sw: ['Kusimamisha kumeombwa. Inasubiri uthibitisho; vitendo vilivyotumwa vinaweza kukamilika.', 'Kusimamisha hakujathibitishwa. Kagua kazi na programu iliyounganishwa kabla ya kujaribu tena.'],
  sn: ['Kumisa kwakumbirwa. Kumirira simbiso; zviito zvakatotumirwa zvinogona kupedza.', 'Kumisa hakuna kusimbiswa. Ongorora basa neapp yakabatana usati waedza zvakare.'],
  nd: ['Ukumisa kuceliwe. Kulindwe ukuqinisekiswa; izenzo ezithunyelweyo zingaqeda.', 'Ukumisa akuqinisekiswanga. Hlola umsebenzi le-app exhunyiweyo ungakazami futhi.'],
  zu: ['Ukumisa kuceliwe. Kulindwe ukuqinisekiswa; izenzo ezithunyelwe zingaqeda.', 'Ukumisa akuqinisekisiwe. Hlola umsebenzi nohlelo oluxhunyiwe ngaphambi kokuzama futhi.'],
};
export function taskStopText(locale: LocaleCode) { return { pending: stop[locale][0], unconfirmed: stop[locale][1] }; }
