export type Messages = {
  history: { searchChats: string; searchTasks: string; clearChats: string; clearTasks: string; deleteTask: string; confirmTitle: string; deleteChatsBody: string; deleteTasksBody: string; partialFailure: string; deleting: string; noMatches: string; showMore: string; protectedTasks: string; removed: string; copyResult: string; draftProtected: string; reuseTask: string };
  agentLive: { live: string; reconnecting: string; reconnectHint: string; preparingTool: string; tool: string; step: string; elapsed: string; lastUpdate: string; showPreview: string; provisional: string; incomplete: string; previewLimit: string };
  chatStreaming: { queued: string; retrieving: string; loading: string; processing: string; generating: string; saving: string; cancelled: string; unsaved: string; options: string; profile: string; interactive: string; extended: string; responseLimit: string; profileHint: string; firstText: string; tokensPerSecond: string; contextTokens: string; limitReached: string };
  recovery: { draftWarning: string; reconcile: string; verifyOutcome: string; uncertain: string; pending: string; running: string; waiting_for_approval: string; completed: string; failed: string; cancelled: string; interrupted: string; };
	knowledgeSetup: { title: string; body: string; model: string; installEnable: string; enable: string; preparing: string; active: string; openModels: string; failed: string };
	agentRuntime: { style: string; react: string; plan: string; reasoning: string; tools: string; enabled: string; history: string; noTasks: string; connectors: string; noConnectors: string; connectorName: string; connectorURL: string; test: string; connect: string; testing: string; connecting: string; computer: string; unavailable: string; available: string; steps: string; noTools: string; risk: string; externalProviders: string; externalProvidersBody: string; providerPluginsTitle: string; noExternalProviders: string; providerReady: string; providerNeedsSetup: string; generateSetup: string; installPlugin: string; configuration: string; provider: string; transport: string; model: string; context: string; environment: string; verification: string; notes: string; copy: string; copied: string };
  product: string;
  privateWorkspace: string;
  shell: { work: string; library: string; system: string; appearance: string; theme: string; systemTheme: string; darkTheme: string; lightTheme: string; storage: string; modelsPath: string; dataPath: string; quickActions: string; searchActions: string; noActions: string };
  nav: { chat: string; knowledge: string; agents: string; models: string; activity: string; settings: string };
  status: { ready: string; offline: string; checking: string; noModel: string };
  auth: { title: string; body: string; username: string; password: string; signIn: string; signOut: string; localNote: string };
  chat: { title: string; subtitle: string; emptyTitle: string; emptyBody: string; placeholder: string; send: string; stop: string; knowledge: string; model: string; selectModel: string; you: string; assistant: string; newChat: string; conversations: string; noConversations: string; deleteConversation: string; showHistory: string; closeHistory: string; copy: string; copied: string; copyResponse: string; copyCode: string; enterHint: string };
  knowledge: { title: string; subtitle: string; add: string; empty: string; chunks: string; disabled: string; retained: string; legacy: string; reindex: string; reindexing: string };
  agents: { title: string; subtitle: string; task: string; placeholder: string; run: string; running: string; result: string; approvalTitle: string; approvalBody: string; approve: string; deny: string; denied: string };
  models: { title: string; subtitle: string; available: string; empty: string; local: string; embedding: string; installed: string; catalog: string; discover: string; recommended: string; download: string; resume: string; cancel: string; delete: string; confirmDelete: string; verify: string };
  activity: { title: string; subtitle: string; uptime: string; requests: string; currentModel: string; version: string; runs: string; noRuns: string; selectRun: string };
  settings: { title: string; subtitle: string; service: string; version: string; inferenceSlots: string; knowledge: string; enabled: string; disabled: string; safety: string; computerUse: string; available: string; unavailable: string; stopped: string; sessions: string; emergencyStop: string; setup: string; showGuide: string };
  onboarding: { title: string; body: string; service: string; models: string; privacy: string; local: string; continue: string; chooseModel: string; startChat: string; retryService: string; modelHint: string; firstReplyHint: string; close: string };
  common: { refresh: string; retry: string; loading: string; error: string; language: string; localProcessing: string; runtime: string; document: string };
};

export type LocaleDefinition = { code: string; label: string; direction: 'ltr' | 'rtl'; messages: Messages };
