import type { LocaleCode } from './index';
type Copy = readonly [string, string, string, string, string, string, string, string, string, string, string, string, string, string, string];
const copy: Record<LocaleCode, Copy> = {
  en: ['Voice settings', 'Recognition model', 'Speech model', 'Automatic', 'Selected model unavailable', 'Unavailable', 'Voice', 'Default voice', 'Saved for this account in this browser. Changes apply to the next recording or playback.', 'Manage speech models', 'Speech models are unavailable.', 'The selected speech model is no longer installed. Choose another in Voice settings.', 'The selected speech model is unavailable. Open Models to check its runtime.', 'No compatible speech model is ready. Open Models to install one.', 'The selected voice is unavailable. Choose another in Voice settings.'],
  fr: ['Réglages vocaux', 'Modèle de reconnaissance', 'Modèle de synthèse', 'Automatique', 'Modèle sélectionné indisponible', 'Indisponible', 'Voix', 'Voix par défaut', 'Enregistré pour ce compte dans ce navigateur. Les changements s’appliquent au prochain enregistrement ou à la prochaine lecture.', 'Gérer les modèles vocaux', 'Les modèles vocaux sont indisponibles.', 'Le modèle vocal sélectionné n’est plus installé. Choisissez-en un autre dans les réglages vocaux.', 'Le modèle vocal sélectionné est indisponible. Vérifiez son moteur dans Modèles.', 'Aucun modèle vocal compatible n’est prêt. Installez-en un dans Modèles.', 'La voix sélectionnée est indisponible. Choisissez-en une autre dans les réglages vocaux.'],
  es: ['Ajustes de voz', 'Modelo de reconocimiento', 'Modelo de síntesis', 'Automático', 'Modelo seleccionado no disponible', 'No disponible', 'Voz', 'Voz predeterminada', 'Guardado para esta cuenta en este navegador. Los cambios se aplican a la próxima grabación o reproducción.', 'Gestionar modelos de voz', 'Los modelos de voz no están disponibles.', 'El modelo de voz seleccionado ya no está instalado. Elige otro en Ajustes de voz.', 'El modelo de voz seleccionado no está disponible. Revisa su motor en Modelos.', 'No hay un modelo de voz compatible listo. Instala uno en Modelos.', 'La voz seleccionada no está disponible. Elige otra en Ajustes de voz.'],
  de: ['Spracheinstellungen', 'Erkennungsmodell', 'Sprachsynthesemodell', 'Automatisch', 'Gewähltes Modell nicht verfügbar', 'Nicht verfügbar', 'Stimme', 'Standardstimme', 'Für dieses Konto in diesem Browser gespeichert. Änderungen gelten ab der nächsten Aufnahme oder Wiedergabe.', 'Sprachmodelle verwalten', 'Sprachmodelle sind nicht verfügbar.', 'Das gewählte Sprachmodell ist nicht mehr installiert. Wählen Sie ein anderes in den Spracheinstellungen.', 'Das gewählte Sprachmodell ist nicht verfügbar. Prüfen Sie seine Laufzeit unter Modelle.', 'Kein kompatibles Sprachmodell ist bereit. Installieren Sie eines unter Modelle.', 'Die gewählte Stimme ist nicht verfügbar. Wählen Sie eine andere in den Spracheinstellungen.'],
  ar: ['إعدادات الصوت', 'نموذج التعرف', 'نموذج توليد الكلام', 'تلقائي', 'النموذج المحدد غير متاح', 'غير متاح', 'الصوت', 'الصوت الافتراضي', 'محفوظ لهذا الحساب في هذا المتصفح. تسري التغييرات على التسجيل أو التشغيل التالي.', 'إدارة نماذج الصوت', 'نماذج الصوت غير متاحة.', 'لم يعد نموذج الصوت المحدد مثبتاً. اختر نموذجاً آخر في إعدادات الصوت.', 'نموذج الصوت المحدد غير متاح. افتح النماذج للتحقق من بيئة تشغيله.', 'لا يوجد نموذج صوت متوافق جاهز. افتح النماذج لتثبيت واحد.', 'الصوت المحدد غير متاح. اختر صوتاً آخر في إعدادات الصوت.'],
  sw: ['Mipangilio ya sauti', 'Modeli ya utambuzi', 'Modeli ya usemi', 'Kiotomatiki', 'Modeli iliyochaguliwa haipatikani', 'Haipatikani', 'Sauti', 'Sauti chaguomsingi', 'Imehifadhiwa kwa akaunti hii katika kivinjari hiki. Mabadiliko yanatumika kwa rekodi au uchezaji unaofuata.', 'Dhibiti modeli za sauti', 'Modeli za sauti hazipatikani.', 'Modeli ya sauti iliyochaguliwa haijasakinishwa tena. Chagua nyingine katika Mipangilio ya sauti.', 'Modeli ya sauti iliyochaguliwa haipatikani. Fungua Modeli kukagua programu yake ya utekelezaji.', 'Hakuna modeli ya sauti inayolingana iliyo tayari. Fungua Modeli kusakinisha moja.', 'Sauti iliyochaguliwa haipatikani. Chagua nyingine katika Mipangilio ya sauti.'],
  sn: ['Zvirongwa zvezwi', 'Modhi yekuziva mazwi', 'Modhi yekutaura', 'Zvega', 'Modhi yakasarudzwa haiwanikwi', 'Haiwanikwi', 'Izwi', 'Izwi rekutanga', 'Zvakachengeterwa akaundi iyi mubhurawuza iri. Shanduko dzinoshanda pakurekodha kana kuridza kunotevera.', 'Tonga modhi dzezwi', 'Modhi dzezwi hadziwanikwi.', 'Modhi yezwi yakasarudzwa haichaiswi. Sarudza imwe muZvirongwa zvezwi.', 'Modhi yezwi yakasarudzwa haiwanikwi. Vhura Modhi uone chirongwa chinoimhanyisa.', 'Hapana modhi yezwi inoenderana yagadzirira. Vhura Modhi kuti uise imwe.', 'Izwi rakasarudzwa hariwanikwi. Sarudza rimwe muZvirongwa zvezwi.'],
  nd: ['Izilungiselelo zezwi', 'Imodeli yokubona amazwi', 'Imodeli yokukhuluma', 'Ngokuzenzakalela', 'Imodeli ekhethiweyo ayitholakali', 'Ayitholakali', 'Izwi', 'Izwi elijwayelekileyo', 'Kugcinelwe le akhawunti kulesi siphequluli. Utshintsho lusebenza ekurekhodeni kumbe ekudlaleni okulandelayo.', 'Phatha amamodeli ezwi', 'Amamodeli ezwi awatholakali.', 'Imodeli yezwi ekhethiweyo kayisafakwanga. Khetha enye kuZilungiselelo zezwi.', 'Imodeli yezwi ekhethiweyo ayitholakali. Vula Amamodeli uhlole uhlelo oluyisebenzisayo.', 'Akulamodeli yezwi ehambelanayo elungileyo. Vula Amamodeli ufake eyodwa.', 'Izwi elikhethiweyo alitholakali. Khetha elinye kuZilungiselelo zezwi.'],
  zu: ['Izilungiselelo zezwi', 'Imodeli yokubona amazwi', 'Imodeli yokukhuluma', 'Ngokuzenzakalelayo', 'Imodeli ekhethiwe ayitholakali', 'Ayitholakali', 'Izwi', 'Izwi elijwayelekile', 'Kulondolozelwe le akhawunti kulesi siphequluli. Izinguquko zisebenza ekurekhodeni noma ekudlaleni okulandelayo.', 'Phatha amamodeli ezwi', 'Amamodeli ezwi awatholakali.', 'Imodeli yezwi ekhethiwe ayisafakiwe. Khetha enye kuZilungiselelo zezwi.', 'Imodeli yezwi ekhethiwe ayitholakali. Vula Amamodeli uhlole uhlelo oluyisebenzisayo.', 'Ayikho imodeli yezwi ehambisanayo elungile. Vula Amamodeli ufake eyodwa.', 'Izwi elikhethiwe alitholakali. Khetha elinye kuZilungiselelo zezwi.'],
};
export function voiceSettingsText(locale: LocaleCode) {
  const [title, recognition, synthesis, automatic, selectedUnavailable, unavailable, voice, defaultVoice, retention, manage, failed, removed, runtime, notReady, voiceUnavailable] = copy[locale];
  return { title, recognition, synthesis, automatic, selectedUnavailable, unavailable, voice, defaultVoice, retention, manage, failed, removed, runtime, notReady, voiceUnavailable };
}
