// Shared workflow copy. Translation structure is checked for every supported locale.
const en = {
 viewSource: 'View source', sourceTitle: 'Retained document text',
 deleteDocument: 'Delete this document and its index? Existing answers are kept, but this source will no longer be available.',
 deleteModel: 'Delete this model file from the service? Saved chats remain. You will need to download the model again to use it.',
 offlineLibrary: 'Your documents are retained. Enable knowledge to index files or use them in answers.',
 sourceTruncated: 'Preview shortened. This is retained extracted text, not the original file.',
 timeout: 'The service took too long to respond. Refresh to check saved state before retrying an operation.',
 downloads: 'Downloads', sourceMissing: 'Source text is unavailable for this document.', disableKnowledge: 'Disable knowledge',
};
export const workflow = {
 en,
 de: { viewSource:'Quelle ansehen',sourceTitle:'Gespeicherter Dokumenttext',deleteDocument:'Dokument und Index löschen? Vorhandene Antworten bleiben erhalten, diese Quelle ist danach nicht mehr verfügbar.',deleteModel:'Modelldatei vom Dienst löschen? Chats bleiben erhalten. Zur erneuten Nutzung muss das Modell wieder heruntergeladen werden.',offlineLibrary:'Ihre Dokumente bleiben erhalten. Aktivieren Sie Wissen zum Indexieren und für belegte Antworten.',sourceTruncated:'Vorschau gekürzt. Dies ist extrahierter Text, nicht die Originaldatei.',timeout:'Der Dienst antwortet zu langsam. Aktualisieren Sie den gespeicherten Zustand, bevor Sie den Vorgang wiederholen.',downloads:'Downloads',sourceMissing:'Für dieses Dokument ist kein Quelltext verfügbar.',disableKnowledge:'Wissensbasis deaktivieren' },
 fr: { viewSource:'Voir la source',sourceTitle:'Texte conservé du document',deleteDocument:'Supprimer ce document et son index ? Les réponses restent, mais cette source ne sera plus disponible.',deleteModel:'Supprimer ce fichier modèle du service ? Les discussions restent. Il faudra télécharger à nouveau le modèle pour l’utiliser.',offlineLibrary:'Vos documents sont conservés. Activez la base de connaissances pour indexer les fichiers et les utiliser dans les réponses.',sourceTruncated:'Aperçu raccourci. Il s’agit du texte extrait conservé, pas du fichier original.',timeout:'Le service met trop de temps à répondre. Actualisez l’état enregistré avant de réessayer.',downloads:'Téléchargements',sourceMissing:'Le texte source de ce document est indisponible.',disableKnowledge:'Désactiver la base de connaissances' },
 es: { viewSource:'Ver fuente',sourceTitle:'Texto conservado del documento',deleteDocument:'¿Eliminar este documento y su índice? Las respuestas se conservan, pero esta fuente dejará de estar disponible.',deleteModel:'¿Eliminar el archivo del modelo del servicio? Los chats se conservan. Tendrás que volver a descargar el modelo para usarlo.',offlineLibrary:'Tus documentos se conservan. Activa la base de conocimiento para indexar archivos y utilizarlos en las respuestas.',sourceTruncated:'Vista previa abreviada. Es texto extraído, no el archivo original.',timeout:'El servicio tarda demasiado. Actualiza el estado guardado antes de reintentar una operación.',downloads:'Descargas',sourceMissing:'El texto fuente de este documento no está disponible.',disableKnowledge:'Desactivar la base de conocimiento' },
 ar: { viewSource:'عرض المصدر',sourceTitle:'نص المستند المحفوظ',deleteDocument:'هل تريد حذف المستند وفهرسه؟ ستبقى الإجابات السابقة لكن لن يتوفر هذا المصدر.',deleteModel:'هل تريد حذف ملف النموذج من الخدمة؟ ستبقى المحادثات وستحتاج إلى تنزيل النموذج مجددًا لاستخدامه.',offlineLibrary:'مستنداتك محفوظة. فعّل قاعدة المعرفة لفهرسة الملفات واستخدامها في الإجابات.',sourceTruncated:'تم اختصار المعاينة. هذا نص مستخرج محفوظ وليس الملف الأصلي.',timeout:'استغرقت استجابة الخدمة وقتًا طويلًا. حدّث الحالة المحفوظة قبل إعادة المحاولة.',downloads:'التنزيلات',sourceMissing:'نص المصدر غير متوفر لهذا المستند.',disableKnowledge:'تعطيل قاعدة المعرفة' },
 sw: { viewSource:'Angalia chanzo',sourceTitle:'Maandishi ya hati yaliyohifadhiwa',deleteDocument:'Ufute hati hii na faharasa yake? Majibu yatabaki, lakini chanzo hiki hakitapatikana tena.',deleteModel:'Ufute faili ya modeli kwenye huduma? Mazungumzo yatabaki. Utahitaji kupakua modeli tena ili kuitumia.',offlineLibrary:'Hati zako zimehifadhiwa. Washa maarifa ili kuorodhesha faili na kuzitumia katika majibu.',sourceTruncated:'Onyesho limefupishwa. Haya ni maandishi yaliyotolewa, si faili asili.',timeout:'Huduma imechukua muda mrefu kujibu. Onyesha hali iliyohifadhiwa upya kabla ya kujaribu tena.',downloads:'Upakuaji',sourceMissing:'Maandishi ya chanzo cha hati hii hayapatikani.',disableKnowledge:'Zima maarifa' },
 sn: { viewSource:'Ona kunobva mashoko',sourceTitle:'Mashoko egwaro akachengetwa',deleteDocument:'Dzima gwaro iri neindekisi yaro? Mhinduro dzicharamba dziripo asi gwaro iri harichawanikwi.',deleteModel:'Dzima faira remodhi kubva pasevhisi? Hurukuro dzichachengetwa. Uchafanira kudhawunirodha modhi zvakare kuti uishandise.',offlineLibrary:'Magwaro ako akachengetwa. Batidza ruzivo kuti uise magwaro muindekisi uye uashandise pamhinduro.',sourceTruncated:'Chiratidziro chapfupiswa. Aya mashoko akatorwa mugwaro, kwete faira rekutanga.',timeout:'Sevhisi yatora nguva yakareba kupindura. Tarisa mamiriro akachengetwa usati waedza zvakare.',downloads:'Zviri kudhawunirodhwa',sourceMissing:'Mashoko ekutanga egwaro iri haawanikwi.',disableKnowledge:'Dzima ruzivo' },
 nd: { viewSource:'Bona umthombo',sourceTitle:'Umbhalo wedokhumenti ogciniweyo',deleteDocument:'Susa idokhumenti le lenkomba yayo? Izimpendulo zizahlala kodwa umthombo lo awusayikutholakala.',deleteModel:'Susa ifayela lemodeli kusevisi? Izingxoxo zizagcinwa. Kuzadingeka ulande imodeli futhi ukuze uyisebenzise.',offlineLibrary:'Amadokhumenti akho agciniwe. Vula ulwazi ukuze ufake amafayela enkombeni futhi uwasebenzise ezimpendulweni.',sourceTruncated:'Ukubuka kufinyeziwe. Lo ngumbhalo okhutshiweyo, hatshi ifayela lokuqala.',timeout:'Isevisi ithatha isikhathi eside ukuphendula. Vuselela isimo esigciniweyo ungakazami futhi.',downloads:'Okulandwayo',sourceMissing:'Umbhalo womthombo wedokhumenti le awutholakali.',disableKnowledge:'Vala ulwazi' },
 zu: { viewSource:'Buka umthombo',sourceTitle:'Umbhalo wedokhumenti ogciniwe',deleteDocument:'Susa le dokhumenti nenkomba yayo? Izimpendulo zizohlala kodwa lo mthombo ngeke usatholakala.',deleteModel:'Susa ifayela lemodeli kusevisi? Izingxoxo zizogcinwa. Kuzodingeka ulande imodeli futhi ukuze uyisebenzise.',offlineLibrary:'Amadokhumenti akho agciniwe. Vula ulwazi ukuze ufake amafayela enkombeni futhi uwasebenzise ezimpendulweni.',sourceTruncated:'Ukubuka kufinyeziwe. Lona umbhalo okhishiwe, hhayi ifayela lokuqala.',timeout:'Isevisi ithatha isikhathi eside ukuphendula. Vuselela isimo esigciniwe ngaphambi kokuzama futhi.',downloads:'Okulandwayo',sourceMissing:'Umbhalo womthombo wale dokhumenti awutholakali.',disableKnowledge:'Vala ulwazi' }
} satisfies Record<import('./index').LocaleCode, Record<keyof typeof en,string>>;
export const workflowText = () => workflow[document.documentElement.lang as keyof typeof workflow] ?? en;
