import type { Messages } from '../types';
export const ar: Messages = {
  product: 'أوف غريد', privateWorkspace: 'مساحة عمل ذكاء اصطناعي خاصة',
  nav: { chat: 'المحادثة', knowledge: 'المعرفة', agents: 'الوكلاء', models: 'النماذج', activity: 'النشاط', settings: 'الإعدادات' },
  status: { ready: 'الخدمة المحلية جاهزة', offline: 'الخدمة غير متاحة', checking: 'جارٍ التحقق من الخدمة', noModel: 'لم يتم اختيار نموذج' },
  chat: { title: 'المحادثة', subtitle: 'اعمل باستخدام نموذج محلي ومعرفة موثوقة.', emptyTitle: 'ما الذي تود العمل عليه؟', emptyBody: 'تبقى محادثاتك ومستنداتك على هذا الجهاز.', placeholder: 'اسأل أو اكتب أو حلّل أو خطط…', send: 'إرسال', stop: 'إيقاف', knowledge: 'استخدام قاعدة المعرفة', model: 'النموذج', selectModel: 'اختر نموذجًا', you: 'أنت', assistant: 'أوف غريد' },
  knowledge: { title: 'المعرفة', subtitle: 'أدر المصادر التي يمكن للنماذج استرجاعها والاستشهاد بها.', add: 'إضافة مستند', empty: 'لم تتم فهرسة أي مستندات بعد.', chunks: 'مقاطع', disabled: 'استرجاع المعرفة غير مفعّل.', retained: 'تم حفظ المصدر', legacy: 'أعد الاستيراد للتحديث', reindex: 'إعادة الفهرسة', reindexing: 'جارٍ إعادة الفهرسة…' },
  agents: { title: 'الوكلاء', subtitle: 'شغّل مهام محكومة مع عرض الأدوات والنتائج.', task: 'المهمة', placeholder: 'صف النتيجة المطلوبة من الوكيل…', run: 'تشغيل المهمة', running: 'الوكيل يعمل…', result: 'النتيجة', approvalTitle: 'الموافقة مطلوبة', approvalBody: 'راجع الأداة والوسائط الدقيقة. تنطبق الموافقة على هذا الاستدعاء فقط.', approve: 'الموافقة على الاستدعاء', deny: 'رفض', denied: 'رفض المستخدم استدعاء الأداة.' },
  models: { title: 'النماذج', subtitle: 'أدر نماذج الاستدلال والتضمين المحلية.', available: 'متاحة', empty: 'لم يتم العثور على نماذج محلية.', local: 'نموذج محلي', embedding: 'تضمين' },
  activity: { title: 'النشاط', subtitle: 'حالة الخدمة وتفاصيل التشغيل.', uptime: 'مدة التشغيل', requests: 'الطلبات', currentModel: 'النموذج الحالي', version: 'الإصدار', runs: 'سجل تشغيل الوكلاء', noRuns: 'لم يتم تسجيل عمليات تشغيل للوكلاء.', selectRun: 'اختر عملية تشغيل لمراجعة تسلسل أحداثها.' },
  settings: { title: 'الإعدادات', subtitle: 'عناصر التحكم في التشغيل والسلامة والنشر المحلي.', service: 'الخدمة', version: 'الإصدار', inferenceSlots: 'فتحات الاستدلال', knowledge: 'المعرفة', enabled: 'مفعّل', disabled: 'معطّل', safety: 'التحكم في السلامة', computerUse: 'استخدام الكمبيوتر', available: 'برنامج تشغيل المنصة متاح', unavailable: 'لم يتم تثبيت برنامج تشغيل المنصة', stopped: 'إيقاف الطوارئ نشط', sessions: 'جلسات نشطة', emergencyStop: 'إيقاف الطوارئ', setup: 'إعداد مساحة العمل', showGuide: 'عرض دليل الإعداد' },
  onboarding: { title: 'مساحة الذكاء الاصطناعي الخاصة بك', body: 'تحقق من جاهزية الخدمة المحلية والنموذج. تبقى البيانات على هذا الجهاز ما لم تربط خدمة خارجية صراحةً.', service: 'الخدمة المحلية', models: 'النماذج المتاحة', privacy: 'الخصوصية الافتراضية', local: 'محلي فقط', continue: 'دخول مساحة العمل' },
  common: { refresh: 'تحديث', retry: 'حاول مجددًا', loading: 'جارٍ التحميل…', error: 'حدث خطأ ما', language: 'اللغة', localProcessing: 'معالجة محلية', runtime: 'وقت التشغيل', document: 'مستند' }
};
