import type { Messages } from '../types';
export const ar: Messages = {
  modelSearch: {"title":"البحث عن نماذج أخرى","hint":"ابحث في مستودعات GGUF العامة على Hugging Face. يُرسل البحث عبر الإنترنت؛ لا يحد هذا الكتالوج من حجم النماذج.","query":"اسم النموذج أو الناشر","search":"بحث","empty":"لا توجد مستودعات GGUF عامة مطابقة. جرّب اسماً آخر.","unavailable":"البحث أو قائمة الملفات غير متاحة. تحقق من الإنترنت وأذونات النموذج ثم أعد المحاولة.","choose":"اختيار الملفات","modelCard":"بطاقة النموذج والترخيص","file":"ملف GGUF / التكميم","noFiles":"لا توجد ملفات GGUF مستقلة.","unknownSize":"الحجم غير معروف","unsupported":"يتطلب ملفات مرافقة","compatibility":"تحقق من بطاقة النموذج والترخيص ودعم محرك التشغيل. حجم الملف لا يساوي استهلاك RAM/VRAM؛ يحتاج السياق إلى ذاكرة إضافية. الأوزان المقسمة وملفات الإسقاط ليست مستقلة. تظهر حتى 1000 مدخلة."},
  modelDownload: {"downloading":"جارٍ التنزيل","finalizing":"جارٍ تجهيز النموذج","complete":"جاهز","failed":"انقطع التنزيل","cancelled":"أُلغي","retained":"تم الاحتفاظ بالبيانات المنزلة. استأنف للمحاولة مجددًا دون البدء من الصفر."},
  history: {"searchChats":"البحث في المحادثات","searchTasks":"البحث في سجل المهام","clearChats":"حذف المحادثات المدرجة","clearTasks":"مسح المهام المنتهية","deleteTask":"حذف المهمة","confirmTitle":"حذف السجل؟","deleteChatsBody":"حذف {count} محادثات مدرجة ومسوداتها المحلية؟ لا يمكن التراجع عن ذلك هنا. تبقى النسخ الاحتياطية محفوظة.","deleteTasksBody":"إزالة {count} مهام منتهية من السجل؟ لا يمكن التراجع عن ذلك هنا. تبقى الملفات المنشأة وسجلات التدقيق والنسخ الاحتياطية محفوظة.","partialFailure":"تعذر حذف {count} عناصر. قد تكون نشطة أو غير متاحة. حدّث أو أعد المحاولة؛ لن تتكرر العناصر المحذوفة.","deleting":"جارٍ الحذف…","noMatches":"لا توجد نتائج مطابقة في السجل.","showMore":"عرض المزيد","protectedTasks":"يمكن حذف مهامك المنتهية فقط. أوقف العمل النشط وتحقق من النتائج المنقطعة أو غير المعروفة أولاً.","removed":"تم حذف {count} عناصر.","copyResult":"نسخ النتيجة","draftProtected":"احتفظ بالمسودة الحالية أو امسحها قبل إعادة استخدام مهمة.","reuseTask":"إعادة استخدام المهمة"},
  agentLive: {"live":"اتصال مباشر","reconnecting":"جارٍ إعادة الاتصال…","reconnectHint":"يجري استعادة الاتصال. تستمر المهمة على الخدمة؛ لا ترسلها مجددًا.","preparingTool":"جارٍ تجهيز استدعاء الأداة","tool":"جارٍ تشغيل الأداة","step":"الخطوة","elapsed":"الوقت المنقضي","lastUpdate":"آخر تقدم","showPreview":"معاينة الرد المباشر","provisional":"قيد التنفيذ — ليست إجابة مكتملة","incomplete":"رد غير مكتمل","previewLimit":"تم بلوغ حد المعاينة. ستظهر النتيجة الكاملة عند انتهاء المهمة."},
  chatStreaming: {"queued":"في انتظار الاستدلال","retrieving":"البحث في المعرفة","loading":"تحميل النموذج","processing":"تجهيز الرسالة","generating":"توليد الإجابة","saving":"حفظ المحادثة","cancelled":"تم الإيقاف. تم الاحتفاظ بالمسودة. أعد تحميل المحادثة قبل المحاولة مجدداً إذا بدأ الحفظ.","unsaved":"إجابة جزئية — لم يتم تأكيد الحفظ","options":"إعدادات الإجابة","profile":"ملف السياق","interactive":"تفاعلي","extended":"موسّع","responseLimit":"الحد الأقصى لرموز الإجابة","profileHint":"يستخدم الوضع التفاعلي سياقاً أصغر. يستخدم الموسّع سياق الخدمة وذاكرة أكثر. قد يتطلب التبديل إعادة تحميل النموذج؛ لن يُحذف السجل دون إشعار.","firstText":"أول نص","tokensPerSecond":"رمز/ث","contextTokens":"رموز السياق","limitReached":"تم بلوغ حد الرموز. اطلب المتابعة أو ارفع الحد."},
  recovery: { draftWarning: "تعذر حفظ المسودة على هذا الجهاز. أبقِ الصفحة مفتوحة حتى الإرسال.", reconcile: "تسجيل النتيجة المتحقق منها", verifyOutcome: "افحص هدف الأداة أولاً، ثم صف ما حدث فعلاً. لن تُشغّل الأداة مرة أخرى.", uncertain: "النتيجة غير معروفة", pending: "قيد الانتظار", running: "قيد التشغيل", waiting_for_approval: "بانتظار الموافقة", completed: "مكتمل", failed: "فشل", cancelled: "ملغى", interrupted: "متوقف" },
  shell: { work: 'العمل', library: 'المكتبة', system: 'النظام', appearance: 'المظهر', theme: 'السمة', systemTheme: 'النظام', darkTheme: 'داكن', lightTheme: 'فاتح', storage: 'التخزين المحلي', modelsPath: 'مجلد النماذج', dataPath: 'مجلد البيانات', quickActions: 'إجراءات سريعة', searchActions: 'ابحث في الصفحات والإجراءات…', noActions: 'لا توجد إجراءات مطابقة.' },
  knowledgeSetup: { title: 'إعداد استرجاع المعرفة', body: 'تحتاج قاعدة المعرفة إلى نموذج تضمين محلي لفهرسة مستنداتك والبحث فيها. يبقى الفهرس على هذا الجهاز.', model: 'نموذج التضمين', installEnable: 'تثبيت وتفعيل', enable: 'تفعيل المعرفة', preparing: 'جارٍ إعداد المعرفة…', active: 'نموذج التضمين النشط', openModels: 'فتح مدير النماذج', failed: 'فشل إعداد المعرفة' },
  agentRuntime: { style: 'أسلوب الاستدلال', react: 'موجّه بالأدوات', plan: 'خطط ونفّذ', reasoning: 'الاستدلال', tools: 'الأدوات المتاحة', enabled: 'مفعّلة', history: 'المهام الأخيرة', noTasks: 'لم يتم تشغيل مهام وكيل بعد.', connectors: 'اتصالات MCP', noConnectors: 'لا توجد خوادم MCP متصلة.', connectorName: 'اسم الاتصال', connectorURL: 'عنوان خادم MCP', test: 'اختبار الاتصال', connect: 'اتصال', testing: 'جارٍ الاختبار…', connecting: 'جارٍ الاتصال…', computer: 'استخدام الكمبيوتر', unavailable: 'برنامج التشغيل غير متاح', available: 'متاح', steps: 'خطوات التنفيذ', noTools: 'لا توجد أدوات مسجلة.', risk: 'المخاطر', externalProviders: 'الوكلاء الخارجيون', externalProvidersBody: 'اربط Hermes وOpenClaw عبر إضافات موفر OffGrid الأصلية.', providerPluginsTitle: 'إضافات موفر OffGrid الأصلية', noExternalProviders: 'لا تتوفر موفرات للوكلاء الخارجيين.', providerReady: 'جاهز', providerNeedsSetup: 'يحتاج إلى إعداد', generateSetup: 'إنشاء الإعداد', installPlugin: 'تثبيت الموفر', configuration: 'إعدادات الموفر', provider: 'الموفر', transport: 'بروتوكول النقل', model: 'النموذج', context: 'السياق', environment: 'متغيرات البيئة', verification: 'التحقق', notes: 'ملاحظات', copy: 'نسخ', copied: 'تم النسخ' },
  product: 'أوف غريد', privateWorkspace: 'مساحة عمل ذكاء اصطناعي خاصة',
  nav: { chat: 'المحادثة', knowledge: 'المعرفة', agents: 'الوكلاء', models: 'النماذج', activity: 'النشاط', settings: 'الإعدادات' },
  status: { ready: 'الخدمة المحلية جاهزة', offline: 'الخدمة غير متاحة', checking: 'جارٍ التحقق من الخدمة', noModel: 'لم يتم اختيار نموذج' },
  auth: { title: 'سجّل الدخول إلى مساحة عملك', body: 'تتطلب خدمة أوف غريد هذه المصادقة.', username: 'اسم المستخدم', password: 'كلمة المرور', signIn: 'تسجيل الدخول', signOut: 'تسجيل الخروج', localNote: 'تُرسل بيانات اعتمادك إلى خدمة أوف غريد هذه فقط.' },
  chat: { title: 'المحادثة', subtitle: 'اعمل باستخدام نموذج محلي ومعرفة موثوقة.', emptyTitle: 'ما الذي تود العمل عليه؟', emptyBody: 'تبقى محادثاتك ومستنداتك على هذا الجهاز.', placeholder: 'اسأل أو اكتب أو حلّل أو خطط…', send: 'إرسال', stop: 'إيقاف', knowledge: 'استخدام قاعدة المعرفة', model: 'النموذج', selectModel: 'اختر نموذجًا', you: 'أنت', assistant: 'أوف غريد', newChat: 'محادثة جديدة', conversations: 'المحادثات', noConversations: 'لا توجد محادثات محفوظة بعد.', deleteConversation: 'حذف المحادثة', showHistory: 'عرض المحادثات', closeHistory: 'إغلاق المحادثات', copy: 'نسخ', copied: 'تم النسخ', copyResponse: 'نسخ الرد', copyCode: 'نسخ الشفرة', enterHint: 'Enter للإرسال · Shift+Enter لسطر جديد' },
  knowledge: { title: 'المعرفة', subtitle: 'أدر المصادر التي يمكن للنماذج استرجاعها والاستشهاد بها.', add: 'إضافة مستند', empty: 'لم تتم فهرسة أي مستندات بعد.', chunks: 'مقاطع', disabled: 'استرجاع المعرفة غير مفعّل.', retained: 'تم حفظ المصدر', legacy: 'أعد الاستيراد للتحديث', reindex: 'إعادة الفهرسة', reindexing: 'جارٍ إعادة الفهرسة…' },
  agents: { title: 'الوكلاء', subtitle: 'شغّل مهام محكومة مع عرض الأدوات والنتائج.', task: 'المهمة', placeholder: 'صف النتيجة المطلوبة من الوكيل…', run: 'تشغيل المهمة', running: 'الوكيل يعمل…', result: 'النتيجة', approvalTitle: 'الموافقة مطلوبة', approvalBody: 'راجع الأداة والوسائط الدقيقة. تنطبق الموافقة على هذا الاستدعاء فقط.', approve: 'الموافقة على الاستدعاء', deny: 'رفض', denied: 'رفض المستخدم استدعاء الأداة.' },
  models: { title: 'النماذج', subtitle: 'أدر نماذج الاستدلال والتضمين المحلية.', available: 'متاحة', empty: 'لم يتم العثور على نماذج محلية.', local: 'نموذج محلي', embedding: 'تضمين', installed: 'مثبتة', catalog: 'الكتالوج المختار', discover: 'اكتشف النماذج', recommended: 'موصى به', download: 'تنزيل', resume: 'استئناف', cancel: 'إلغاء', delete: 'حذف', confirmDelete: 'تأكيد الحذف', verify: 'تحقق' },
  activity: { title: 'النشاط', subtitle: 'حالة الخدمة وتفاصيل التشغيل.', uptime: 'مدة التشغيل', requests: 'الطلبات', currentModel: 'النموذج الحالي', version: 'الإصدار', runs: 'سجل تشغيل الوكلاء', noRuns: 'لم يتم تسجيل عمليات تشغيل للوكلاء.', selectRun: 'اختر عملية تشغيل لمراجعة تسلسل أحداثها.' },
  settings: { title: 'الإعدادات', subtitle: 'عناصر التحكم في التشغيل والسلامة والنشر المحلي.', service: 'الخدمة', version: 'الإصدار', inferenceSlots: 'فتحات الاستدلال', knowledge: 'المعرفة', enabled: 'مفعّل', disabled: 'معطّل', safety: 'التحكم في السلامة', computerUse: 'استخدام الكمبيوتر', available: 'برنامج تشغيل المنصة متاح', unavailable: 'لم يتم تثبيت برنامج تشغيل المنصة', stopped: 'إيقاف الطوارئ نشط', sessions: 'جلسات نشطة', emergencyStop: 'إيقاف الطوارئ', setup: 'إعداد مساحة العمل', showGuide: 'عرض دليل الإعداد' },
  onboarding: { title: 'مساحة الذكاء الاصطناعي الخاصة بك', body: 'ثبّت نموذج محادثة محليًا، ثم احصل على رد فعلي لإكمال الإعداد. تبقى بياناتك على هذا الجهاز ما لم تربط خدمة خارجية صراحةً.', service: 'الخدمة المحلية', models: 'نماذج المحادثة', privacy: 'الخصوصية الافتراضية', local: 'محلي فقط', continue: 'دخول مساحة العمل', chooseModel: 'اختيار نموذج محادثة', startChat: 'بدء محادثتك الأولى', retryService: 'إعادة محاولة الاتصال', modelHint: 'نزّل نموذج محادثة للبدء.', firstReplyHint: 'يكتمل الإعداد بعد أول رد ناجح من النموذج.', close: 'إغلاق الدليل' },
  common: { refresh: 'تحديث', retry: 'حاول مجددًا', loading: 'جارٍ التحميل…', error: 'حدث خطأ ما', language: 'اللغة', localProcessing: 'معالجة محلية', runtime: 'وقت التشغيل', document: 'مستند' }
};
