import type { Messages } from '../types';

export const de: Messages = {
  shell: { work: 'Arbeit', library: 'Bibliothek', system: 'System', appearance: 'Darstellung', theme: 'Design', systemTheme: 'System', darkTheme: 'Dunkel', lightTheme: 'Hell', storage: 'Lokaler Speicher', modelsPath: 'Modellverzeichnis', dataPath: 'Datenverzeichnis', quickActions: 'Schnellaktionen', searchActions: 'Seiten und Aktionen durchsuchen…', noActions: 'Keine passenden Aktionen.' },
  knowledgeSetup: { title: 'Wissenssuche vorbereiten', body: 'Für die Indizierung und Suche in deinen Dokumenten wird ein lokales Embedding-Modell benötigt. Wähle ein Modell aus; OffGrid speichert den Index auf diesem Gerät.', model: 'Embedding-Modell', installEnable: 'Installieren und aktivieren', enable: 'Wissenssuche aktivieren', preparing: 'Wissenssuche wird vorbereitet…', active: 'Aktives Embedding-Modell', openModels: 'Modellverwaltung öffnen', failed: 'Einrichtung der Wissenssuche fehlgeschlagen' },
  agentRuntime: { style: 'Denkmodus', react: 'Werkzeuggestützt', plan: 'Planen und ausführen', reasoning: 'Schlussfolgerung', tools: 'Verfügbare Werkzeuge', enabled: 'aktiviert', history: 'Letzte Aufgaben', noTasks: 'Es wurden noch keine Agentenaufgaben ausgeführt.', connectors: 'MCP-Verbindungen', noConnectors: 'Es sind keine MCP-Server verbunden.', connectorName: 'Verbindungsname', connectorURL: 'MCP-Server-URL', test: 'Verbindung testen', connect: 'Verbinden', testing: 'Wird getestet…', connecting: 'Wird verbunden…', computer: 'Computersteuerung', unavailable: 'Treiber nicht verfügbar', available: 'Verfügbar', steps: 'Ausführungsschritte', noTools: 'Es sind keine Werkzeuge registriert.', risk: 'Risiko', externalProviders: 'Externe Agenten', externalProvidersBody: 'Verbinde Hermes und OpenClaw über offizielle OffGrid-Provider-Plugins.', providerPluginsTitle: 'Native OffGrid-Provider-Plugins', noExternalProviders: 'Es sind keine Provider für externe Agenten verfügbar.', providerReady: 'Bereit', providerNeedsSetup: 'Einrichtung erforderlich', generateSetup: 'Einrichtung erzeugen', installPlugin: 'Einrichtungsbefehl', configuration: 'Provider-Konfiguration', provider: 'Provider', transport: 'Transport', model: 'Modell', context: 'Kontext', environment: 'Umgebung', verification: 'Überprüfung', notes: 'Hinweise', copy: 'Kopieren', copied: 'Kopiert' },
  product: 'OffGrid', privateWorkspace: 'Privater KI-Arbeitsbereich',
  nav: { chat: 'Chat', knowledge: 'Wissen', agents: 'Agenten', models: 'Modelle', activity: 'Aktivität', settings: 'Einstellungen' },
  status: { ready: 'Lokaler Dienst ist bereit', offline: 'Dienst nicht verfügbar', checking: 'Dienst wird geprüft', noModel: 'Kein Modell ausgewählt' },
  auth: { title: 'Bei deinem Arbeitsbereich anmelden', body: 'Dieser OffGrid-Dienst erfordert eine Authentifizierung.', username: 'Benutzername', password: 'Passwort', signIn: 'Anmelden', signOut: 'Abmelden', localNote: 'Deine Anmeldedaten werden nur an diesen OffGrid-Dienst gesendet.' },
  chat: { title: 'Chat', subtitle: 'Arbeite mit einem lokalen Modell und vertrauenswürdigem Wissen.', emptyTitle: 'Woran möchtest du arbeiten?', emptyBody: 'Deine Unterhaltungen und Dokumente bleiben auf diesem Gerät.', placeholder: 'Fragen, entwerfen, analysieren oder planen…', send: 'Senden', stop: 'Stoppen', knowledge: 'Wissensdatenbank verwenden', model: 'Modell', selectModel: 'Modell auswählen', you: 'Du', assistant: 'OffGrid', newChat: 'Neuer Chat', conversations: 'Unterhaltungen', noConversations: 'Noch keine gespeicherten Unterhaltungen.', deleteConversation: 'Unterhaltung löschen', showHistory: 'Unterhaltungen anzeigen', closeHistory: 'Unterhaltungen schließen', copy: 'Kopieren', copied: 'Kopiert', copyResponse: 'Antwort kopieren', copyCode: 'Code kopieren', enterHint: 'Enter zum Senden · Shift+Enter für eine neue Zeile' },
  knowledge: { title: 'Wissen', subtitle: 'Verwalte die Quellen, die deine Modelle abrufen und zitieren können.', add: 'Dokument hinzufügen', empty: 'Es wurden noch keine Dokumente indiziert.', chunks: 'Abschnitte', disabled: 'Die Wissenssuche ist nicht aktiviert.', retained: 'Quelle beibehalten', legacy: 'Für Aktualisierung neu einlesen', reindex: 'Neu indizieren', reindexing: 'Wird neu indiziert…' },
  agents: { title: 'Agenten', subtitle: 'Führe kontrollierte Aufgaben mit sichtbaren Werkzeugaktivitäten und Ergebnissen aus.', task: 'Aufgabe', placeholder: 'Beschreibe das gewünschte Ergebnis für den Agenten…', run: 'Aufgabe ausführen', running: 'Agent arbeitet…', result: 'Ergebnis', approvalTitle: 'Genehmigung erforderlich', approvalBody: 'Prüfe das genaue Werkzeug und seine Argumente. Die Genehmigung gilt nur für diesen Aufruf.', approve: 'Diesen Aufruf genehmigen', deny: 'Ablehnen', denied: 'Werkzeugaufruf wurde vom Benutzer abgelehnt.' },
  models: { title: 'Modelle', subtitle: 'Verwalte lokale Inferenz- und Embedding-Modelle.', available: 'verfügbar', empty: 'Keine lokalen Modelle gefunden.', local: 'Lokales Modell', embedding: 'Embedding', installed: 'Installiert', catalog: 'Ausgewählter Katalog', discover: 'Modelle entdecken', recommended: 'Empfohlen', download: 'Herunterladen', resume: 'Fortsetzen', cancel: 'Abbrechen', delete: 'Löschen', confirmDelete: 'Löschen bestätigen', verify: 'Überprüfen' },
  activity: { title: 'Aktivität', subtitle: 'Dienststatus und Laufzeitdetails.', uptime: 'Laufzeit', requests: 'Anfragen', currentModel: 'Aktuelles Modell', version: 'Version', runs: 'Verlauf der Agentenausführungen', noRuns: 'Es wurden keine Agentenausführungen aufgezeichnet.', selectRun: 'Wähle eine Ausführung aus, um ihre dauerhafte Ereigniszeitleiste zu prüfen.' },
  settings: { title: 'Einstellungen', subtitle: 'Laufzeit-, Sicherheits- und lokale Bereitstellungseinstellungen.', service: 'Dienst', version: 'Version', inferenceSlots: 'Inferenzplätze', knowledge: 'Wissen', enabled: 'Aktiviert', disabled: 'Deaktiviert', safety: 'Sicherheitssteuerung', computerUse: 'Computersteuerung', available: 'Plattformtreiber verfügbar', unavailable: 'Kein Plattformtreiber installiert', stopped: 'Not-Aus aktiv', sessions: 'aktive Sitzungen', emergencyStop: 'Not-Aus', setup: 'Arbeitsbereich einrichten', showGuide: 'Einrichtungsanleitung anzeigen' },
  onboarding: { title: 'Dein privater KI-Arbeitsbereich', body: 'Richte ein lokales Chatmodell ein und erhalte anschließend eine echte Antwort, um die Einrichtung abzuschließen. Deine Daten bleiben auf diesem Gerät, sofern du nicht ausdrücklich einen externen Dienst verbindest.', service: 'Lokaler Dienst', models: 'Chatmodelle', privacy: 'Standard-Datenschutz', local: 'Nur lokal', continue: 'Arbeitsbereich öffnen', chooseModel: 'Chatmodell auswählen', startChat: 'Ersten Chat starten', retryService: 'Verbindung erneut versuchen', modelHint: 'Lade ein Chatmodell herunter, um loszulegen.', firstReplyHint: 'Die Einrichtung wird nach der ersten erfolgreichen Modellantwort abgeschlossen.', close: 'Anleitung schließen' },
  common: { refresh: 'Aktualisieren', retry: 'Erneut versuchen', loading: 'Wird geladen…', error: 'Etwas ist schiefgelaufen', language: 'Sprache', localProcessing: 'lokale Verarbeitung', runtime: 'Laufzeit', document: 'Dokument' }
};
