import type { Messages } from '../types';
export const en: Messages = {
  knowledgeSetup: { title: 'Prepare knowledge retrieval', body: 'Knowledge needs a local embedding model to index and search your documents. Choose one model; OffGrid will keep the index on this device.', model: 'Embedding model', installEnable: 'Install and enable', enable: 'Enable knowledge', preparing: 'Preparing knowledge…', active: 'Active embedding model', openModels: 'Open model manager', failed: 'Knowledge setup failed' },
  agentRuntime: { style: 'Reasoning style', react: 'Tool-guided', plan: 'Plan and execute', reasoning: 'Reasoning', tools: 'Available tools', enabled: 'enabled', history: 'Recent tasks', noTasks: 'No agent tasks have run yet.', connectors: 'MCP connections', noConnectors: 'No MCP servers are connected.', connectorName: 'Connection name', connectorURL: 'MCP server URL', test: 'Test connection', connect: 'Connect', testing: 'Testing…', connecting: 'Connecting…', computer: 'Computer use', unavailable: 'Driver unavailable', available: 'Available', steps: 'Execution steps', noTools: 'No tools are registered.', risk: 'risk', externalProviders: 'External agents', externalProvidersBody: 'Connect Hermes and OpenClaw through first-party OffGrid provider plugins.', providerPluginsTitle: 'Native OffGrid provider plugins', noExternalProviders: 'No external-agent providers are available.', providerReady: 'Ready', providerNeedsSetup: 'Needs setup', generateSetup: 'Generate setup', installPlugin: 'Setup command', configuration: 'Provider configuration', provider: 'Provider', transport: 'Transport', model: 'Model', context: 'Context', environment: 'Environment', verification: 'Verification', notes: 'Notes', copy: 'Copy', copied: 'Copied' },
  product: 'OffGrid', privateWorkspace: 'Private AI workspace',
  nav: { chat: 'Chat', knowledge: 'Knowledge', agents: 'Agents', models: 'Models', activity: 'Activity', settings: 'Settings' },
  status: { ready: 'Local service ready', offline: 'Service unavailable', checking: 'Checking service', noModel: 'No model selected' },
  auth: { title: 'Sign in to your workspace', body: 'Authentication is required by this OffGrid service.', username: 'Username', password: 'Password', signIn: 'Sign in', signOut: 'Sign out', localNote: 'Your credentials are sent only to this OffGrid service.' },
  chat: { title: 'Chat', subtitle: 'Work with a local model and trusted knowledge.', emptyTitle: 'What would you like to work on?', emptyBody: 'Your conversations and documents stay on this device.', placeholder: 'Ask, draft, analyze, or plan…', send: 'Send', stop: 'Stop', knowledge: 'Use knowledge base', model: 'Model', selectModel: 'Select a model', you: 'You', assistant: 'OffGrid', newChat: 'New chat', conversations: 'Conversations', noConversations: 'No saved conversations yet.', deleteConversation: 'Delete conversation' },
  knowledge: { title: 'Knowledge', subtitle: 'Curate the sources your models can retrieve and cite.', add: 'Add document', empty: 'No documents have been indexed yet.', chunks: 'chunks', disabled: 'Knowledge retrieval is not enabled.', retained: 'Source retained', legacy: 'Re-ingest to update', reindex: 'Reindex', reindexing: 'Reindexing…' },
  agents: { title: 'Agents', subtitle: 'Run governed tasks with visible tool activity and results.', task: 'Task', placeholder: 'Describe an outcome for the agent…', run: 'Run task', running: 'Agent is working…', result: 'Result', approvalTitle: 'Approval required', approvalBody: 'Review the exact tool and arguments. Approval applies only to this exact call.', approve: 'Approve exact call', deny: 'Deny', denied: 'Tool call denied by user.' },
  models: { title: 'Models', subtitle: 'Manage local inference and embedding models.', available: 'available', empty: 'No local models were found.', local: 'Local model', embedding: 'Embedding', installed: 'Installed', catalog: 'Curated catalog', discover: 'Discover models', recommended: 'Recommended', download: 'Download', resume: 'Resume', cancel: 'Cancel', delete: 'Delete', confirmDelete: 'Confirm delete', verify: 'Verify' },
  activity: { title: 'Activity', subtitle: 'Service health and runtime details.', uptime: 'Uptime', requests: 'Requests', currentModel: 'Current model', version: 'Version', runs: 'Agent run history', noRuns: 'No agent runs have been recorded.', selectRun: 'Select a run to inspect its durable event timeline.' },
  settings: { title: 'Settings', subtitle: 'Runtime, safety, and local deployment controls.', service: 'Service', version: 'Version', inferenceSlots: 'Inference slots', knowledge: 'Knowledge', enabled: 'Enabled', disabled: 'Disabled', safety: 'Safety control', computerUse: 'Computer use', available: 'Platform driver available', unavailable: 'No platform driver installed', stopped: 'Emergency stop active', sessions: 'active sessions', emergencyStop: 'Emergency stop', setup: 'Workspace setup', showGuide: 'Show setup guide' },
  onboarding: { title: 'Your private AI workspace', body: 'Check that the local service and a model are ready. Data stays on this device unless you explicitly connect an external service.', service: 'Local service', models: 'Available models', privacy: 'Default privacy', local: 'Local only', continue: 'Enter workspace' },
  common: { refresh: 'Refresh', retry: 'Try again', loading: 'Loading…', error: 'Something went wrong', language: 'Language', localProcessing: 'local processing', runtime: 'Runtime', document: 'document' }
};
