import type { Messages } from '../types';
export const en: Messages = {
  modelSearch: {"title":"Find more models","hint":"Search public GGUF repositories on Hugging Face. Your search goes online; model sizes are not limited by this catalog.","query":"Model name or publisher","search":"Search","empty":"No matching public GGUF repositories. Try a different name.","unavailable":"Search or file discovery is unavailable. Check internet access and model permissions, then retry.","choose":"Choose files","modelCard":"Model card and license","file":"GGUF file / quantization","noFiles":"No standalone GGUF files available.","unknownSize":"Size unknown","unsupported":"Requires companion files","compatibility":"Check the model card, license and runtime support before downloading. File size is not RAM/VRAM usage; context needs extra memory. Split weights and projectors are not standalone models. Lists show up to 1,000 repository entries."},
  modelDownload: {"downloading":"Downloading","finalizing":"Preparing model","complete":"Ready","failed":"Download interrupted","cancelled":"Cancelled","retained":"Downloaded data is kept. Resume to retry without starting over."},
  history: {"searchChats":"Search conversations","searchTasks":"Search task history","clearChats":"Delete listed chats","clearTasks":"Clear finished tasks","deleteTask":"Delete task","confirmTitle":"Delete history?","deleteChatsBody":"Delete {count} listed conversations and their local drafts? This cannot be undone here. Backups are not erased.","deleteTasksBody":"Remove {count} finished tasks from history? This cannot be undone here. Tool-created files, audit logs and backups are kept.","partialFailure":"{count} items could not be deleted. They may be busy or unavailable. Refresh or retry; deleted items will not be repeated.","deleting":"Deleting…","noMatches":"No matching history.","showMore":"Show more","protectedTasks":"Only your finished tasks can be deleted. Stop active work and resolve interrupted or unknown outcomes first.","removed":"Deleted {count} items.","copyResult":"Copy result","draftProtected":"Keep or clear your current draft before reusing a task.","reuseTask":"Reuse task"},
  agentLive: {"live":"Live connection","reconnecting":"Reconnecting…","reconnectHint":"The connection is recovering. The task continues on the service; do not submit it again.","preparingTool":"Preparing tool call","tool":"Running tool","step":"Step","elapsed":"Elapsed","lastUpdate":"Last progress","showPreview":"Live response preview","provisional":"In progress — not a completed answer","incomplete":"Incomplete response","previewLimit":"Preview limit reached. The complete result will appear when the task finishes."},
  chatStreaming: {"queued":"Waiting for inference","retrieving":"Searching knowledge","loading":"Loading model","processing":"Preparing prompt","generating":"Generating","saving":"Saving conversation","cancelled":"Stopped. Your draft is retained. Reload the conversation before retrying if saving had started.","unsaved":"Partial response — not confirmed saved","options":"Response settings","profile":"Context profile","interactive":"Interactive","extended":"Extended","responseLimit":"Maximum response tokens","profileHint":"Interactive uses a smaller context allocation. Extended uses the service context and more memory. Switching profiles may reload the model; history is never silently removed.","firstText":"First text","tokensPerSecond":"tokens/s","contextTokens":"context tokens","limitReached":"Response reached the token limit. Ask to continue or increase the response limit."},
  recovery: { draftWarning: "Draft could not be saved on this device. Keep this page open until sent.", reconcile: "Record verified outcome", verifyOutcome: "Inspect the tool's target first, then describe what actually happened. This does not rerun the tool.", uncertain: "Outcome unknown", pending: "Pending", running: "Running", waiting_for_approval: "Awaiting approval", completed: "Completed", failed: "Failed", cancelled: "Cancelled", interrupted: "Interrupted" },
  shell: { work: 'Work', library: 'Library', system: 'System', appearance: 'Appearance', theme: 'Theme', systemTheme: 'System', darkTheme: 'Dark', lightTheme: 'Light', storage: 'Local storage', modelsPath: 'Models directory', dataPath: 'Data directory', quickActions: 'Quick actions', searchActions: 'Search pages and actions…', noActions: 'No matching actions.' },
  knowledgeSetup: { title: 'Prepare knowledge retrieval', body: 'Knowledge needs a local embedding model to index and search your documents. Choose one model; OffGrid will keep the index on this device.', model: 'Embedding model', installEnable: 'Install and enable', enable: 'Enable knowledge', preparing: 'Preparing knowledge…', active: 'Active embedding model', openModels: 'Open model manager', failed: 'Knowledge setup failed' },
  agentRuntime: { style: 'Reasoning style', react: 'Tool-guided', plan: 'Plan and execute', reasoning: 'Reasoning', tools: 'Available tools', enabled: 'enabled', history: 'Recent tasks', noTasks: 'No agent tasks have run yet.', connectors: 'MCP connections', noConnectors: 'No MCP servers are connected.', connectorName: 'Connection name', connectorURL: 'MCP server URL', test: 'Test connection', connect: 'Connect', testing: 'Testing…', connecting: 'Connecting…', computer: 'Computer use', unavailable: 'Driver unavailable', available: 'Available', steps: 'Execution steps', noTools: 'No tools are registered.', risk: 'risk', externalProviders: 'External agents', externalProvidersBody: 'Connect Hermes and OpenClaw through first-party OffGrid provider plugins.', providerPluginsTitle: 'Native OffGrid provider plugins', noExternalProviders: 'No external-agent providers are available.', providerReady: 'Ready', providerNeedsSetup: 'Needs setup', generateSetup: 'Generate setup', installPlugin: 'Setup command', configuration: 'Provider configuration', provider: 'Provider', transport: 'Transport', model: 'Model', context: 'Context', environment: 'Environment', verification: 'Verification', notes: 'Notes', copy: 'Copy', copied: 'Copied' },
  product: 'OffGrid', privateWorkspace: 'Private AI workspace',
  nav: { chat: 'Chat', knowledge: 'Knowledge', agents: 'Agents', models: 'Models', activity: 'Activity', settings: 'Settings' },
  status: { ready: 'Local service ready', offline: 'Service unavailable', checking: 'Checking service', noModel: 'No model selected' },
  auth: { title: 'Sign in to your workspace', body: 'Authentication is required by this OffGrid service.', username: 'Username', password: 'Password', signIn: 'Sign in', signOut: 'Sign out', localNote: 'Your credentials are sent only to this OffGrid service.' },
  chat: { title: 'Chat', subtitle: 'Work with a local model and trusted knowledge.', emptyTitle: 'What would you like to work on?', emptyBody: 'Your conversations and documents stay on this device.', placeholder: 'Ask, draft, analyze, or plan…', send: 'Send', stop: 'Stop', knowledge: 'Use knowledge base', model: 'Model', selectModel: 'Select a model', you: 'You', assistant: 'OffGrid', newChat: 'New chat', conversations: 'Conversations', noConversations: 'No saved conversations yet.', deleteConversation: 'Delete conversation', showHistory: 'Show conversations', closeHistory: 'Close conversations', copy: 'Copy', copied: 'Copied', copyResponse: 'Copy response', copyCode: 'Copy code', enterHint: 'Enter to send · Shift+Enter for a new line' },
  knowledge: { title: 'Knowledge', subtitle: 'Curate the sources your models can retrieve and cite.', add: 'Add document', empty: 'No documents have been indexed yet.', chunks: 'chunks', disabled: 'Knowledge retrieval is not enabled.', retained: 'Source retained', legacy: 'Re-ingest to update', reindex: 'Reindex', reindexing: 'Reindexing…' },
  agents: { title: 'Agents', subtitle: 'Run governed tasks with visible tool activity and results.', task: 'Task', placeholder: 'Describe an outcome for the agent…', run: 'Run task', running: 'Agent is working…', result: 'Result', approvalTitle: 'Approval required', approvalBody: 'Review the exact tool and arguments. Approval applies only to this exact call.', approve: 'Approve exact call', deny: 'Deny', denied: 'Tool call denied by user.' },
  models: { title: 'Models', subtitle: 'Manage local inference and embedding models.', available: 'available', empty: 'No local models were found.', local: 'Local model', embedding: 'Embedding', installed: 'Installed', catalog: 'Curated catalog', discover: 'Discover models', recommended: 'Recommended', download: 'Download', resume: 'Resume', cancel: 'Cancel', delete: 'Delete', confirmDelete: 'Confirm delete', verify: 'Verify' },
  activity: { title: 'Activity', subtitle: 'Service health and runtime details.', uptime: 'Uptime', requests: 'Requests', currentModel: 'Current model', version: 'Version', runs: 'Agent run history', noRuns: 'No agent runs have been recorded.', selectRun: 'Select a run to inspect its durable event timeline.' },
  settings: { title: 'Settings', subtitle: 'Runtime, safety, and local deployment controls.', service: 'Service', version: 'Version', inferenceSlots: 'Inference slots', knowledge: 'Knowledge', enabled: 'Enabled', disabled: 'Disabled', safety: 'Safety control', computerUse: 'Computer use', available: 'Platform driver available', unavailable: 'No platform driver installed', stopped: 'Emergency stop active', sessions: 'active sessions', emergencyStop: 'Emergency stop', setup: 'Workspace setup', showGuide: 'Show setup guide' },
  onboarding: { title: 'Your private AI workspace', body: 'Set up a local chat model, then get a real reply to finish setup. Your data stays on this device unless you explicitly connect an external service.', service: 'Local service', models: 'Chat models', privacy: 'Default privacy', local: 'Local only', continue: 'Enter workspace', chooseModel: 'Choose a chat model', startChat: 'Start your first chat', retryService: 'Retry connection', modelHint: 'Download a chat model to begin working.', firstReplyHint: 'Setup finishes after your first successful model reply.', close: 'Close guide' },
  common: { refresh: 'Refresh', retry: 'Try again', loading: 'Loading…', error: 'Something went wrong', language: 'Language', localProcessing: 'local processing', runtime: 'Runtime', document: 'document' }
};
