import type { Messages } from '../types';
export const es: Messages = {
  product: 'OffGrid', privateWorkspace: 'Espacio de IA privado',
  nav: { chat: 'Chat', knowledge: 'Conocimiento', agents: 'Agentes', models: 'Modelos', activity: 'Actividad', settings: 'Ajustes' },
  status: { ready: 'Servicio local listo', offline: 'Servicio no disponible', checking: 'Comprobando el servicio', noModel: 'Ningún modelo seleccionado' },
  chat: { title: 'Chat', subtitle: 'Trabaja con un modelo local y conocimiento confiable.', emptyTitle: '¿En qué te gustaría trabajar?', emptyBody: 'Tus conversaciones y documentos permanecen en este dispositivo.', placeholder: 'Pregunta, redacta, analiza o planifica…', send: 'Enviar', stop: 'Detener', knowledge: 'Usar la base de conocimiento', model: 'Modelo', selectModel: 'Selecciona un modelo', you: 'Tú', assistant: 'OffGrid' },
  knowledge: { title: 'Conocimiento', subtitle: 'Gestiona las fuentes que los modelos pueden recuperar y citar.', add: 'Añadir documento', empty: 'Todavía no hay documentos indexados.', chunks: 'fragmentos', disabled: 'La recuperación de conocimiento no está activada.', retained: 'Fuente conservada', legacy: 'Vuelve a importar para actualizar', reindex: 'Reindexar', reindexing: 'Reindexando…' },
  agents: { title: 'Agentes', subtitle: 'Ejecuta tareas controladas con herramientas y resultados visibles.', task: 'Tarea', placeholder: 'Describe el resultado que debe lograr el agente…', run: 'Ejecutar tarea', running: 'El agente está trabajando…', result: 'Resultado', approvalTitle: 'Aprobación necesaria', approvalBody: 'Revisa la herramienta y los argumentos exactos. La aprobación solo se aplica a esta llamada.', approve: 'Aprobar llamada exacta', deny: 'Denegar', denied: 'Llamada de herramienta denegada por el usuario.' },
  models: { title: 'Modelos', subtitle: 'Gestiona modelos locales de inferencia y embeddings.', available: 'disponibles', empty: 'No se encontraron modelos locales.', local: 'Modelo local', embedding: 'Embedding' },
  activity: { title: 'Actividad', subtitle: 'Salud del servicio y detalles de ejecución.', uptime: 'Tiempo activo', requests: 'Solicitudes', currentModel: 'Modelo actual', version: 'Versión', runs: 'Historial de agentes', noRuns: 'No hay ejecuciones de agentes registradas.', selectRun: 'Selecciona una ejecución para revisar su cronología de eventos.' },
  settings: { title: 'Ajustes', subtitle: 'Controles de ejecución, seguridad y despliegue local.', service: 'Servicio', version: 'Versión', inferenceSlots: 'Ranuras de inferencia', knowledge: 'Conocimiento', enabled: 'Activado', disabled: 'Desactivado', safety: 'Control de seguridad', computerUse: 'Uso del ordenador', available: 'Controlador de plataforma disponible', unavailable: 'No hay controlador de plataforma instalado', stopped: 'Parada de emergencia activa', sessions: 'sesiones activas', emergencyStop: 'Parada de emergencia', setup: 'Configuración del espacio', showGuide: 'Mostrar guía de configuración' },
  onboarding: { title: 'Tu espacio privado de IA', body: 'Comprueba que el servicio local y un modelo estén listos. Los datos permanecen en este dispositivo salvo que conectes un servicio externo.', service: 'Servicio local', models: 'Modelos disponibles', privacy: 'Privacidad predeterminada', local: 'Solo local', continue: 'Entrar al espacio' },
  common: { refresh: 'Actualizar', retry: 'Reintentar', loading: 'Cargando…', error: 'Algo salió mal', language: 'Idioma', localProcessing: 'procesamiento local', runtime: 'Ejecución', document: 'documento' }
};
