import type { Messages } from '../types';
export const es: Messages = {
  knowledgeSetup: { title: 'Preparar la búsqueda de conocimiento', body: 'La base de conocimiento necesita un modelo de embeddings local para indexar y buscar documentos. El índice permanece en este dispositivo.', model: 'Modelo de embeddings', installEnable: 'Instalar y activar', enable: 'Activar conocimiento', preparing: 'Preparando conocimiento…', active: 'Modelo de embeddings activo', openModels: 'Abrir modelos', failed: 'Falló la configuración de conocimiento' },
  agentRuntime: { style: 'Estilo de razonamiento', react: 'Guiado por herramientas', plan: 'Planificar y ejecutar', reasoning: 'Razonamiento', tools: 'Herramientas disponibles', enabled: 'activadas', history: 'Tareas recientes', noTasks: 'Aún no se han ejecutado tareas.', connectors: 'Conexiones MCP', noConnectors: 'No hay servidores MCP conectados.', connectorName: 'Nombre de conexión', connectorURL: 'URL del servidor MCP', test: 'Probar', connect: 'Conectar', testing: 'Probando…', connecting: 'Conectando…', computer: 'Uso del ordenador', unavailable: 'Controlador no disponible', available: 'Disponible', steps: 'Pasos de ejecución', noTools: 'No hay herramientas registradas.', risk: 'riesgo', externalProviders: 'Agentes externos', externalProvidersBody: 'Conecta Hermes y OpenClaw mediante complementos de proveedor nativos de OffGrid.', providerPluginsTitle: 'Complementos nativos de proveedor OffGrid', noExternalProviders: 'No hay proveedores de agentes externos disponibles.', providerReady: 'Listo', providerNeedsSetup: 'Requiere configuración', generateSetup: 'Generar configuración', installPlugin: 'Instalar proveedor', configuration: 'Configuración del proveedor', provider: 'Proveedor', transport: 'Transporte', model: 'Modelo', context: 'Contexto', environment: 'Entorno', verification: 'Verificación', notes: 'Notas', copy: 'Copiar', copied: 'Copiado' },
  product: 'OffGrid', privateWorkspace: 'Espacio de IA privado',
  nav: { chat: 'Chat', knowledge: 'Conocimiento', agents: 'Agentes', models: 'Modelos', activity: 'Actividad', settings: 'Ajustes' },
  status: { ready: 'Servicio local listo', offline: 'Servicio no disponible', checking: 'Comprobando el servicio', noModel: 'Ningún modelo seleccionado' },
  auth: { title: 'Inicia sesión en tu espacio', body: 'Este servicio OffGrid requiere autenticación.', username: 'Usuario', password: 'Contraseña', signIn: 'Iniciar sesión', signOut: 'Cerrar sesión', localNote: 'Tus credenciales solo se envían a este servicio OffGrid.' },
  chat: { title: 'Chat', subtitle: 'Trabaja con un modelo local y conocimiento confiable.', emptyTitle: '¿En qué te gustaría trabajar?', emptyBody: 'Tus conversaciones y documentos permanecen en este dispositivo.', placeholder: 'Pregunta, redacta, analiza o planifica…', send: 'Enviar', stop: 'Detener', knowledge: 'Usar la base de conocimiento', model: 'Modelo', selectModel: 'Selecciona un modelo', you: 'Tú', assistant: 'OffGrid', newChat: 'Nuevo chat', conversations: 'Conversaciones', noConversations: 'Aún no hay conversaciones guardadas.', deleteConversation: 'Eliminar conversación' },
  knowledge: { title: 'Conocimiento', subtitle: 'Gestiona las fuentes que los modelos pueden recuperar y citar.', add: 'Añadir documento', empty: 'Todavía no hay documentos indexados.', chunks: 'fragmentos', disabled: 'La recuperación de conocimiento no está activada.', retained: 'Fuente conservada', legacy: 'Vuelve a importar para actualizar', reindex: 'Reindexar', reindexing: 'Reindexando…' },
  agents: { title: 'Agentes', subtitle: 'Ejecuta tareas controladas con herramientas y resultados visibles.', task: 'Tarea', placeholder: 'Describe el resultado que debe lograr el agente…', run: 'Ejecutar tarea', running: 'El agente está trabajando…', result: 'Resultado', approvalTitle: 'Aprobación necesaria', approvalBody: 'Revisa la herramienta y los argumentos exactos. La aprobación solo se aplica a esta llamada.', approve: 'Aprobar llamada exacta', deny: 'Denegar', denied: 'Llamada de herramienta denegada por el usuario.' },
  models: { title: 'Modelos', subtitle: 'Gestiona modelos locales de inferencia y embeddings.', available: 'disponibles', empty: 'No se encontraron modelos locales.', local: 'Modelo local', embedding: 'Embedding', installed: 'Instalados', catalog: 'Catálogo seleccionado', discover: 'Descubrir modelos', recommended: 'Recomendado', download: 'Descargar', resume: 'Reanudar', cancel: 'Cancelar', delete: 'Eliminar', confirmDelete: 'Confirmar', verify: 'Verificar' },
  activity: { title: 'Actividad', subtitle: 'Salud del servicio y detalles de ejecución.', uptime: 'Tiempo activo', requests: 'Solicitudes', currentModel: 'Modelo actual', version: 'Versión', runs: 'Historial de agentes', noRuns: 'No hay ejecuciones de agentes registradas.', selectRun: 'Selecciona una ejecución para revisar su cronología de eventos.' },
  settings: { title: 'Ajustes', subtitle: 'Controles de ejecución, seguridad y despliegue local.', service: 'Servicio', version: 'Versión', inferenceSlots: 'Ranuras de inferencia', knowledge: 'Conocimiento', enabled: 'Activado', disabled: 'Desactivado', safety: 'Control de seguridad', computerUse: 'Uso del ordenador', available: 'Controlador de plataforma disponible', unavailable: 'No hay controlador de plataforma instalado', stopped: 'Parada de emergencia activa', sessions: 'sesiones activas', emergencyStop: 'Parada de emergencia', setup: 'Configuración del espacio', showGuide: 'Mostrar guía de configuración' },
  onboarding: { title: 'Tu espacio privado de IA', body: 'Comprueba que el servicio local y un modelo estén listos. Los datos permanecen en este dispositivo salvo que conectes un servicio externo.', service: 'Servicio local', models: 'Modelos disponibles', privacy: 'Privacidad predeterminada', local: 'Solo local', continue: 'Entrar al espacio' },
  common: { refresh: 'Actualizar', retry: 'Reintentar', loading: 'Cargando…', error: 'Algo salió mal', language: 'Idioma', localProcessing: 'procesamiento local', runtime: 'Ejecución', document: 'documento' }
};
