import type { Messages } from '../types';
export const fr: Messages = {
  chatStreaming: {"queued":"En attente du moteur","retrieving":"Recherche dans les connaissances","loading":"Chargement du modèle","processing":"Préparation du message","generating":"Génération","saving":"Enregistrement","cancelled":"Arrêté. Votre brouillon est conservé. Rechargez la conversation avant de réessayer si l’enregistrement avait commencé.","unsaved":"Réponse partielle — enregistrement non confirmé","options":"Réglages de réponse","profile":"Profil de contexte","interactive":"Interactif","extended":"Étendu","responseLimit":"Nombre maximal de tokens","profileHint":"Interactif utilise moins de contexte. Étendu utilise le contexte du service et plus de mémoire. Changer de profil peut recharger le modèle ; l’historique n’est jamais supprimé silencieusement.","firstText":"Premier texte","tokensPerSecond":"tokens/s","contextTokens":"tokens de contexte","limitReached":"Limite de tokens atteinte. Demandez une suite ou augmentez la limite."},
  recovery: { draftWarning: "Le brouillon n’a pas pu être enregistré sur cet appareil. Gardez cette page ouverte jusqu’à l’envoi.", reconcile: "Enregistrer le résultat vérifié", verifyOutcome: "Vérifiez d’abord la cible de l’outil, puis décrivez ce qui s’est réellement passé. L’outil ne sera pas relancé.", uncertain: "Résultat inconnu", pending: "En attente", running: "En cours", waiting_for_approval: "Approbation requise", completed: "Terminé", failed: "Échec", cancelled: "Annulé", interrupted: "Interrompu" },
  shell: { work: 'Travail', library: 'Bibliothèque', system: 'Système', appearance: 'Apparence', theme: 'Thème', systemTheme: 'Système', darkTheme: 'Sombre', lightTheme: 'Clair', storage: 'Stockage local', modelsPath: 'Dossier des modèles', dataPath: 'Dossier des données', quickActions: 'Actions rapides', searchActions: 'Rechercher des pages et actions…', noActions: 'Aucune action correspondante.' },
  knowledgeSetup: { title: 'Préparer la recherche documentaire', body: 'La base de connaissances nécessite un modèle d’embedding local pour indexer et rechercher vos documents. L’index reste sur cet appareil.', model: 'Modèle d’embedding', installEnable: 'Installer et activer', enable: 'Activer les connaissances', preparing: 'Préparation des connaissances…', active: 'Modèle d’embedding actif', openModels: 'Ouvrir les modèles', failed: 'Échec de la configuration des connaissances' },
  agentRuntime: { style: 'Style de raisonnement', react: 'Guidé par les outils', plan: 'Planifier et exécuter', reasoning: 'Raisonnement', tools: 'Outils disponibles', enabled: 'activés', history: 'Tâches récentes', noTasks: 'Aucune tâche d’agent exécutée.', connectors: 'Connexions MCP', noConnectors: 'Aucun serveur MCP connecté.', connectorName: 'Nom de la connexion', connectorURL: 'URL du serveur MCP', test: 'Tester', connect: 'Connecter', testing: 'Test…', connecting: 'Connexion…', computer: 'Utilisation de l’ordinateur', unavailable: 'Pilote indisponible', available: 'Disponible', steps: 'Étapes d’exécution', noTools: 'Aucun outil enregistré.', risk: 'risque', externalProviders: 'Agents externes', externalProvidersBody: 'Connectez Hermes et OpenClaw avec les extensions de fournisseur OffGrid natives.', providerPluginsTitle: 'Extensions natives du fournisseur OffGrid', noExternalProviders: 'Aucun fournisseur d’agent externe disponible.', providerReady: 'Prêt', providerNeedsSetup: 'Configuration requise', generateSetup: 'Générer la configuration', installPlugin: 'Installer le fournisseur', configuration: 'Configuration du fournisseur', provider: 'Fournisseur', transport: 'Transport', model: 'Modèle', context: 'Contexte', environment: 'Environnement', verification: 'Vérification', notes: 'Notes', copy: 'Copier', copied: 'Copié' },
  product: 'OffGrid', privateWorkspace: 'Espace de travail IA privé',
  nav: { chat: 'Discussion', knowledge: 'Connaissances', agents: 'Agents', models: 'Modèles', activity: 'Activité', settings: 'Paramètres' },
  status: { ready: 'Service local prêt', offline: 'Service indisponible', checking: 'Vérification du service', noModel: 'Aucun modèle sélectionné' },
  auth: { title: 'Connectez-vous à votre espace', body: "L'authentification est requise par ce service OffGrid.", username: "Nom d'utilisateur", password: 'Mot de passe', signIn: 'Se connecter', signOut: 'Se déconnecter', localNote: 'Vos identifiants sont envoyés uniquement à ce service OffGrid.' },
  chat: { title: 'Discussion', subtitle: 'Travaillez avec un modèle local et des sources fiables.', emptyTitle: 'Sur quoi souhaitez-vous travailler ?', emptyBody: 'Vos conversations et documents restent sur cet appareil.', placeholder: 'Demandez, rédigez, analysez ou planifiez…', send: 'Envoyer', stop: 'Arrêter', knowledge: 'Utiliser la base de connaissances', model: 'Modèle', selectModel: 'Sélectionner un modèle', you: 'Vous', assistant: 'OffGrid', newChat: 'Nouvelle discussion', conversations: 'Discussions', noConversations: 'Aucune discussion enregistrée.', deleteConversation: 'Supprimer la discussion', showHistory: 'Afficher les discussions', closeHistory: 'Fermer les discussions', copy: 'Copier', copied: 'Copié', copyResponse: 'Copier la réponse', copyCode: 'Copier le code', enterHint: 'Entrée pour envoyer · Maj+Entrée pour une nouvelle ligne' },
  knowledge: { title: 'Connaissances', subtitle: 'Gérez les sources que les modèles peuvent rechercher et citer.', add: 'Ajouter un document', empty: "Aucun document n'a encore été indexé.", chunks: 'segments', disabled: "La recherche documentaire n'est pas activée.", retained: 'Source conservée', legacy: 'Réimporter pour mettre à jour', reindex: 'Réindexer', reindexing: 'Réindexation…' },
  agents: { title: 'Agents', subtitle: "Exécutez des tâches contrôlées avec l'activité des outils visible.", task: 'Tâche', placeholder: "Décrivez le résultat attendu de l'agent…", run: 'Lancer', running: "L'agent travaille…", result: 'Résultat', approvalTitle: 'Approbation requise', approvalBody: "Vérifiez l'outil et les arguments exacts. L'approbation ne vaut que pour cet appel.", approve: "Approuver l'appel exact", deny: 'Refuser', denied: "Appel d'outil refusé par l'utilisateur." },
  models: { title: 'Modèles', subtitle: "Gérez les modèles locaux d'inférence et d'embedding.", available: 'disponibles', empty: "Aucun modèle local n'a été trouvé.", local: 'Modèle local', embedding: 'Embedding', installed: 'Installés', catalog: 'Catalogue sélectionné', discover: 'Découvrir des modèles', recommended: 'Recommandé', download: 'Télécharger', resume: 'Reprendre', cancel: 'Annuler', delete: 'Supprimer', confirmDelete: 'Confirmer', verify: 'Vérifier' },
  activity: { title: 'Activité', subtitle: "État du service et détails d'exécution.", uptime: 'Disponibilité', requests: 'Requêtes', currentModel: 'Modèle actif', version: 'Version', runs: "Historique d'exécution des agents", noRuns: "Aucune exécution d'agent enregistrée.", selectRun: "Sélectionnez une exécution pour consulter sa chronologie d'événements." },
  settings: { title: 'Paramètres', subtitle: "Contrôles d'exécution, de sécurité et de déploiement local.", service: 'Service', version: 'Version', inferenceSlots: "Créneaux d'inférence", knowledge: 'Connaissances', enabled: 'Activé', disabled: 'Désactivé', safety: 'Contrôle de sécurité', computerUse: "Utilisation de l'ordinateur", available: 'Pilote de plateforme disponible', unavailable: 'Aucun pilote de plateforme installé', stopped: "Arrêt d'urgence actif", sessions: 'sessions actives', emergencyStop: "Arrêt d'urgence", setup: "Configuration de l'espace", showGuide: 'Afficher le guide' },
  onboarding: { title: 'Votre espace IA privé', body: 'Installez un modèle de discussion local, puis obtenez une vraie réponse pour terminer la configuration. Vos données restent sur cet appareil sauf connexion explicite à un service externe.', service: 'Service local', models: 'Modèles de discussion', privacy: 'Confidentialité par défaut', local: 'Local uniquement', continue: "Entrer dans l'espace", chooseModel: 'Choisir un modèle', startChat: 'Commencer votre première discussion', retryService: 'Réessayer la connexion', modelHint: 'Téléchargez un modèle de discussion pour commencer.', firstReplyHint: 'La configuration se termine après la première réponse du modèle.', close: 'Fermer le guide' },
  common: { refresh: 'Actualiser', retry: 'Réessayer', loading: 'Chargement…', error: 'Une erreur est survenue', language: 'Langue', localProcessing: 'traitement local', runtime: 'Exécution', document: 'document' }
};
