import type { Messages } from '../types';
export const fr: Messages = {
  product: 'OffGrid', privateWorkspace: 'Espace de travail IA privé',
  nav: { chat: 'Discussion', knowledge: 'Connaissances', agents: 'Agents', models: 'Modèles', activity: 'Activité', settings: 'Paramètres' },
  status: { ready: 'Service local prêt', offline: 'Service indisponible', checking: 'Vérification du service', noModel: 'Aucun modèle sélectionné' },
  chat: { title: 'Discussion', subtitle: 'Travaillez avec un modèle local et des sources fiables.', emptyTitle: 'Sur quoi souhaitez-vous travailler ?', emptyBody: 'Vos conversations et documents restent sur cet appareil.', placeholder: 'Demandez, rédigez, analysez ou planifiez…', send: 'Envoyer', stop: 'Arrêter', knowledge: 'Utiliser la base de connaissances', model: 'Modèle', selectModel: 'Sélectionner un modèle', you: 'Vous', assistant: 'OffGrid' },
  knowledge: { title: 'Connaissances', subtitle: 'Gérez les sources que les modèles peuvent rechercher et citer.', add: 'Ajouter un document', empty: "Aucun document n'a encore été indexé.", chunks: 'segments', disabled: "La recherche documentaire n'est pas activée.", retained: 'Source conservée', legacy: 'Réimporter pour mettre à jour', reindex: 'Réindexer', reindexing: 'Réindexation…' },
  agents: { title: 'Agents', subtitle: "Exécutez des tâches contrôlées avec l'activité des outils visible.", task: 'Tâche', placeholder: "Décrivez le résultat attendu de l'agent…", run: 'Lancer', running: "L'agent travaille…", result: 'Résultat', approvalTitle: 'Approbation requise', approvalBody: "Vérifiez l'outil et les arguments exacts. L'approbation ne vaut que pour cet appel.", approve: "Approuver l'appel exact", deny: 'Refuser', denied: "Appel d'outil refusé par l'utilisateur." },
  models: { title: 'Modèles', subtitle: "Gérez les modèles locaux d'inférence et d'embedding.", available: 'disponibles', empty: "Aucun modèle local n'a été trouvé.", local: 'Modèle local', embedding: 'Embedding' },
  activity: { title: 'Activité', subtitle: "État du service et détails d'exécution.", uptime: 'Disponibilité', requests: 'Requêtes', currentModel: 'Modèle actif', version: 'Version', runs: "Historique d'exécution des agents", noRuns: "Aucune exécution d'agent enregistrée.", selectRun: "Sélectionnez une exécution pour consulter sa chronologie d'événements." },
  settings: { title: 'Paramètres', subtitle: "Contrôles d'exécution, de sécurité et de déploiement local.", service: 'Service', version: 'Version', inferenceSlots: "Créneaux d'inférence", knowledge: 'Connaissances', enabled: 'Activé', disabled: 'Désactivé', safety: 'Contrôle de sécurité', computerUse: "Utilisation de l'ordinateur", available: 'Pilote de plateforme disponible', unavailable: 'Aucun pilote de plateforme installé', stopped: "Arrêt d'urgence actif", sessions: 'sessions actives', emergencyStop: "Arrêt d'urgence", setup: "Configuration de l'espace", showGuide: 'Afficher le guide' },
  onboarding: { title: 'Votre espace IA privé', body: 'Vérifiez que le service local et un modèle sont prêts. Les données restent sur cet appareil sauf connexion explicite à un service externe.', service: 'Service local', models: 'Modèles disponibles', privacy: 'Confidentialité par défaut', local: 'Local uniquement', continue: "Entrer dans l'espace" },
  common: { refresh: 'Actualiser', retry: 'Réessayer', loading: 'Chargement…', error: 'Une erreur est survenue', language: 'Langue', localProcessing: 'traitement local', runtime: 'Exécution', document: 'document' }
};
