import type { Messages } from '../types';

export const nd: Messages = {
  modelSearch: {"title":"Dinga amanye amamodeli","hint":"Dinga ama-GGUF asesidlangalaleni ku-Hugging Face. Ukudinga kusebenzisa i-inthanethi; ikhathalogu le ayikhawuli ubukhulu bemodeli.","query":"Ibizo lemodeli kumbe umshicileli","search":"Dinga","empty":"Akulamamodeli e-GGUF asesidlangalaleni ahambelanayo. Zama elinye ibizo.","unavailable":"Ukudinga kumbe uluhlu lwamafayela alutholakali. Hlola i-inthanethi lemvumo zemodeli, uphinde uzame.","choose":"Khetha amafayela","modelCard":"Ulwazi lwemodeli lelayisensi","file":"Ifayela le-GGUF / quantization","noFiles":"Akulamafayela e-GGUF azimeleyo.","unknownSize":"Ubukhulu abaziwa","unsupported":"Kudinga amanye amafayela","compatibility":"Hlola ulwazi, ilayisensi lokusekelwa yinjini. Ubukhulu befayela abulingani lokusetshenziswa kwe-RAM/VRAM; i-context idinga inkumbulo eyengeziweyo. Amafayela ahlukanisiweyo lama-projector kawazimeli. Kuboniswa okufika ku-1,000."},
  modelDownload: {"downloading":"Kuyalandwa","finalizing":"Kulungiswa imodeli","complete":"Isilungile","failed":"Ukulanda kuphazamisekile","cancelled":"Kukhanseliwe","retained":"Okulandiweyo kugciniwe. Qhubeka uzame futhi."},
  history: {"searchChats":"Dinga izingxoxo","searchTasks":"Dinga imbali yemisebenzi","clearChats":"Susa izingxoxo ezisohlwini","clearTasks":"Sula imisebenzi ephelileyo","deleteTask":"Susa umsebenzi","confirmTitle":"Sula imbali?","deleteChatsBody":"Susa izingxoxo ezingu-{count} ezisohlwini kanye lemibhalo yazo engakaqedwa? Lokhu akubuyiselwa lapha. Amakhophi okulondoloza azasala.","deleteTasksBody":"Susa imisebenzi ephelileyo engu-{count} embalini? Lokhu akubuyiselwa lapha. Amafayela adaliweyo, amarekhodi okuhlola lamakhophi okulondoloza azasala.","partialFailure":"Izinto ezingu-{count} azisuswanga. Zingabe zisasebenza kumbe zingatholakali. Vuselela kumbe uzame futhi; ezisusiweyo kaziphindwa.","deleting":"Kuyasuswa…","noMatches":"Akulambali ehambelanayo.","showMore":"Tshengisa okunye","protectedTasks":"Ungasusa imisebenzi yakho ephelileyo kuphela. Misa esasebenzayo njalo uqale uhlole imiphumela ephazamisekileyo kumbe engaziwayo.","removed":"Kususwe izinto ezingu-{count}.","copyResult":"Kopa umphumela","draftProtected":"Gcina kumbe usule umbhalo ongakaqedwa ngaphambi kokusebenzisa umsebenzi futhi.","reuseTask":"Sebenzisa umsebenzi futhi"},
  agentLive: {"live":"Kuxhunyiwe","reconnecting":"Kuxhunywa futhi…","reconnectHint":"Ukuxhumana kuyabuyiselwa. Umsebenzi uyaqhubeka kusevisi; ungawuthumeli futhi.","preparingTool":"Kulungiselelwa ukusebenzisa ithuluzi","tool":"Kusetshenziswa ithuluzi","step":"Isinyathelo","elapsed":"Isikhathi esidlulileyo","lastUpdate":"Intuthuko yokucina","showPreview":"Bonisa impendulo ibhalwa","provisional":"Kuyaqhubeka — impendulo ayikapheli","incomplete":"Impendulo engaphelelanga","previewLimit":"Umkhawulo wokubonisa usufinyelelwe. Umphumela opheleleyo uzabonakala umsebenzi usuphelile."},
  chatStreaming: {"queued":"Kulindwe impendulo","retrieving":"Kudingwa ulwazi","loading":"Kufakwa imodeli","processing":"Kulungiswa umlayezo","generating":"Kwakhiwa impendulo","saving":"Kugcinwa ingxoxo","cancelled":"Kumisiwe. Umbhalo wakho usagciniwe. Vula ingxoxo kutsha ungakazami futhi nxa ukugcina bekuqalile.","unsaved":"Impendulo engaphelelanga — ukugcinwa akuqinisekiswanga","options":"Izilungiselelo zempendulo","profile":"Uhlobo lomongo","interactive":"Okokuxoxisana","extended":"Okunwetshiweyo","responseLimit":"Amathokheni amanengi empendulo","profileHint":"Okokuxoxisana kusebenzisa umongo omncane. Okunwetshiweyo kusebenzisa umongo wesevisi lenkumbulo enengi. Ukutshintsha kungalayitsha imodeli kutsha; imbali ayisuswa kungaziswanga.","firstText":"Umbhalo wokuqala","tokensPerSecond":"amathokheni/s","contextTokens":"amathokheni omongo","limitReached":"Umkhawulo wamathokheni usufinyelelwe. Cela ukuqhubeka kumbe wandise umkhawulo."},
  recovery: { draftWarning: "Okusalungiswa akugcinwanga kudivayisi le. Tshiya ikhasi livuliwe uze uthumele.", reconcile: "Gcina umphumela ohloliweyo", verifyOutcome: "Qala uhlole okwenziwe lithuluzi, ubusuchaza okwenzakeleyo. Ithuluzi alisoqalwa futhi.", uncertain: "Umphumela awaziwa", pending: "Kulindile", running: "Kuyasebenza", waiting_for_approval: "Kulinde imvumo", completed: "Kuphelile", failed: "Kwehlulekile", cancelled: "Kucitshiwe", interrupted: "Kuphazamisekile" },
  shell: { work: 'Umsebenzi', library: 'Umtapo', system: 'Uhlelo', appearance: 'Ukubonakala', theme: 'Itimu', systemTheme: 'Uhlelo', darkTheme: 'Mnyama', lightTheme: 'Khanya', storage: 'Ukugcinwa kwendawo', modelsPath: 'Ifolda yamamodeli', dataPath: 'Ifolda yedatha', quickActions: 'Izenzo eziphuthumayo', searchActions: 'Dinga amakhasi lezenzo…', noActions: 'Akukho zenzo ezihambelanayo.' },
  knowledgeSetup: { title: 'Lungisa ukudinga ulwazi', body: 'Ulwazi ludinga imodeli ye-embedding yendawo ukuze luhlele njalo ludinge amadokhumenti akho. Khetha imodeli eyodwa; i-OffGrid izagcina i-index kule idivayisi.', model: 'Imodeli ye-embedding', installEnable: 'Faka njalo uvule', enable: 'Vula ulwazi', preparing: 'Ulwazi luyalungiswa…', active: 'Imodeli ye-embedding esebenzayo', openModels: 'Vula umphathi wamamodeli', failed: 'Ukulungiswa kolwazi kwehlulekile' },
  agentRuntime: { style: 'Indlela yokucabanga', react: 'Ukuqondiswa ngamathuluzi', plan: 'Hlela njalo wenze', reasoning: 'Ukucabanga', tools: 'Amathuluzi akhona', enabled: 'avuliwe', history: 'Imisebenzi yakamuva', noTasks: 'Akukho misebenzi yama-ejenti eseyenziwe.', connectors: 'Ukuxhumana kwe-MCP', noConnectors: 'Akukho maseva e-MCP axhunyiweyo.', connectorName: 'Ibizo lokuxhumana', connectorURL: 'I-URL yesiphakeli se-MCP', test: 'Hlola ukuxhumana', connect: 'Xhuma', testing: 'Kuyahlolwa…', connecting: 'Kuyaxhunywa…', computer: 'Ukusebenzisa ikhompiyutha', unavailable: 'I-driver ayikho', available: 'Kukhona', steps: 'Amanyathelo okwenza', noTools: 'Akukho mathuluzi abhalisiweyo.', risk: 'ingozi', externalProviders: 'Ama-ejenti angaphandle', externalProvidersBody: 'Xhuma i-Hermes le-OpenClaw ngamapulagini asemthethweni e-OffGrid.', providerPluginsTitle: 'Amapulagini e-provider e-OffGrid', noExternalProviders: 'Akukho ma-provider ama-ejenti angaphandle akhona.', providerReady: 'Kulungele', providerNeedsSetup: 'Kudinga ukulungiswa', generateSetup: 'Yenza i-setup', installPlugin: 'Umlayo we-setup', configuration: 'Ukulungiswa kwe-provider', provider: 'I-provider', transport: 'Indlela yokuthutha', model: 'Imodeli', context: 'I-context', environment: 'Indawo', verification: 'Ukuqinisekisa', notes: 'Amanothi', copy: 'Kopisha', copied: 'Kukotshiwe' },
  product: 'OffGrid', privateWorkspace: 'Indawo yokusebenzela ye-AI eyimfihlo',
  nav: { chat: 'Ingxoxo', knowledge: 'Ulwazi', agents: 'Ama-ejenti', models: 'Amamodeli', activity: 'Imisebenzi', settings: 'Izilungiselelo' },
  status: { ready: 'Isevisi yendawo isilungele', offline: 'Isevisi ayitholakali', checking: 'Kuhlolwa isevisi', noModel: 'Akukhethwanga modeli' },
  auth: { title: 'Ngena endaweni yakho yokusebenzela', body: 'Isevisi le ye-OffGrid idinga ukuqinisekiswa komsebenzisi.', username: 'Ibizo lomsebenzisi', password: 'Iphasiwedi', signIn: 'Ngena', signOut: 'Phuma', localNote: 'Imininingwane yakho yokungena ithunyelwa kule isevisi ye-OffGrid kuphela.' },
  chat: { title: 'Ingxoxo', subtitle: 'Sebenza ngemodeli yendawo lolwazi oluthembekileyo.', emptyTitle: 'Ufuna ukusebenza ngani?', emptyBody: 'Izingxoxo lamadokhumenti akho kuhlala kule idivayisi.', placeholder: 'Buza, bhala, hlaziya, kumbe uhlele…', send: 'Thumela', stop: 'Misa', knowledge: 'Sebenzisa isizinda solwazi', model: 'Imodeli', selectModel: 'Khetha imodeli', you: 'Wena', assistant: 'OffGrid', newChat: 'Ingxoxo entsha', conversations: 'Izingxoxo', noConversations: 'Akukho zingxoxo ezigciniweyo.', deleteConversation: 'Susa ingxoxo', showHistory: 'Tshengisa izingxoxo', closeHistory: 'Vala izingxoxo', copy: 'Kopisha', copied: 'Kukotshiwe', copyResponse: 'Kopisha impendulo', copyCode: 'Kopisha ikhodi', enterHint: 'Enter ukuthumela · Shift+Enter ukuqala umugqa omutsha' },
  knowledge: { title: 'Ulwazi', subtitle: 'Hlela imithombo amamodeli akho angayidinga njalo ayicaphune.', add: 'Faka idokhumenti', empty: 'Akukho madokhumenti asefakwe ku-index.', chunks: 'iziqephu', disabled: 'Ukudinga ulwazi akuvuliwanga.', retained: 'Umthombo ugciniwe', legacy: 'Faka futhi ukuze ubuyekeze', reindex: 'Faka ku-index futhi', reindexing: 'Kufakwa ku-index futhi…' },
  agents: { title: 'Ama-ejenti', subtitle: 'Yenza imisebenzi elawulwayo ubone amathuluzi asebenzayo lemiphumela.', task: 'Umsebenzi', placeholder: 'Chaza umphumela ofuna i-ejenti iwufinyelele…', run: 'Qalisa umsebenzi', running: 'I-ejenti iyasebenza…', result: 'Umphumela', approvalTitle: 'Imvumo iyadingeka', approvalBody: 'Hlola ithuluzi lemininingwane yalo eqondileyo. Imvumo isebenza kulokhu kubiza kuphela.', approve: 'Vumela lokhu kubiza', deny: 'Yala', denied: 'Ukubizwa kwethuluzi kwaliwe ngumsebenzisi.' },
  models: { title: 'Amamodeli', subtitle: 'Phatha amamodeli endawo e-inference le-embedding.', available: 'akhona', empty: 'Akukho mamodeli endawo atholakeleyo.', local: 'Imodeli yendawo', embedding: 'Embedding', installed: 'Afakiweyo', catalog: 'Ikhathalogi ekhethiweyo', discover: 'Dinga amamodeli', recommended: 'Kuyanconywa', download: 'Dawuniloda', resume: 'Qhubeka', cancel: 'Khansela', delete: 'Susa', confirmDelete: 'Qinisekisa ukususa', verify: 'Qinisekisa' },
  activity: { title: 'Imisebenzi', subtitle: 'Impilakahle yesevisi lemininingwane ye-runtime.', uptime: 'Isikhathi isebenza', requests: 'Izicelo', currentModel: 'Imodeli esebenzayo', version: 'Inguqulo', runs: 'Imbali yemisebenzi yama-ejenti', noRuns: 'Akukho misebenzi yama-ejenti ebhaliweyo.', selectRun: 'Khetha umsebenzi ukuze ubone umugqa wesikhathi wezenzakalo zawo.' },
  settings: { title: 'Izilungiselelo', subtitle: 'I-runtime, ukuphepha, lokulawula ukufakwa kwendawo.', service: 'Isevisi', version: 'Inguqulo', inferenceSlots: 'Izikhala ze-inference', knowledge: 'Ulwazi', enabled: 'Kuvuliwe', disabled: 'Kuvaliwe', safety: 'Ukulawula ukuphepha', computerUse: 'Ukusebenzisa ikhompiyutha', available: 'I-driver yepulatifomu ikhona', unavailable: 'Akukho driver yepulatifomu efakiweyo', stopped: 'Ukumisa okuphuthumayo kuyasebenza', sessions: 'amasetshini asebenzayo', emergencyStop: 'Misa ngokuphangisa', setup: 'Ukulungisa indawo yokusebenzela', showGuide: 'Tshengisa umhlahlandlela' },
  onboarding: { title: 'Indawo yakho ye-AI eyimfihlo', body: 'Lungisa imodeli yengxoxo yendawo, ubusuthola impendulo yangempela ukuze uqede i-setup. Idatha yakho ihlala kule idivayisi ngaphandle nxa uxhuma isevisi yangaphandle.', service: 'Isevisi yendawo', models: 'Amamodeli engxoxo', privacy: 'Ubumfihlo obujwayelekileyo', local: 'Okwendawo kuphela', continue: 'Ngena endaweni yokusebenzela', chooseModel: 'Khetha imodeli yengxoxo', startChat: 'Qala ingxoxo yakho yokuqala', retryService: 'Zama ukuxhuma futhi', modelHint: 'Dawuniloda imodeli yengxoxo ukuze uqale ukusebenza.', firstReplyHint: 'I-setup iphela ngemva kwempendulo yokuqala ephumelelayo.', close: 'Vala umhlahlandlela' },
  common: { refresh: 'Vuselela', retry: 'Zama futhi', loading: 'Kuyalayisha…', error: 'Kukhona okungahambanga kuhle', language: 'Ulimi', localProcessing: 'ukucubungula kwendawo', runtime: 'I-runtime', document: 'idokhumenti' }
};
