import type { Messages } from '../types';

export const nd: Messages = {
  shell: { work: 'Umsebenzi', library: 'Umtapo', system: 'Uhlelo', appearance: 'Ukubonakala', theme: 'Itimu', systemTheme: 'Uhlelo', darkTheme: 'Mnyama', lightTheme: 'Khanya', storage: 'Ukugcinwa kwendawo', modelsPath: 'Ifolda yamamodeli', dataPath: 'Ifolda yedatha', quickActions: 'Izenzo eziphuthumayo', searchActions: 'Dinga amakhasi lezenzo…', noActions: 'Akukho zenzo ezihambelanayo.' },
  knowledgeSetup: { title: 'Lungisa ukudinga ulwazi', body: 'Ulwazi ludinga imodeli ye-embedding yendawo ukuze luhlele njalo ludinge amadokhumenti akho. Khetha imodeli eyodwa; i-OffGrid izagcina i-index kule idivayisi.', model: 'Imodeli ye-embedding', installEnable: 'Faka njalo uvule', enable: 'Vula ulwazi', preparing: 'Ulwazi luyalungiswa…', active: 'Imodeli ye-embedding esebenzayo', openModels: 'Vula umphathi wamamodeli', failed: 'Ukulungiswa kolwazi kwehlulekile' },
  agentRuntime: { style: 'Indlela yokucabanga', react: 'Ukuqondiswa ngamathuluzi', plan: 'Hlela njalo wenze', reasoning: 'Ukucabanga', tools: 'Amathuluzi akhona', enabled: 'avuliwe', history: 'Imisebenzi yakamuva', noTasks: 'Akukho misebenzi yama-ejenti eseyenziwe.', connectors: 'Ukuxhumana kwe-MCP', noConnectors: 'Akukho maseva e-MCP axhunyiweyo.', connectorName: 'Ibizo lokuxhumana', connectorURL: 'I-URL yesiphakeli se-MCP', test: 'Hlola ukuxhumana', connect: 'Xhuma', testing: 'Kuyahlolwa…', connecting: 'Kuyaxhunywa…', computer: 'Ukusebenzisa ikhompiyutha', unavailable: 'I-driver ayikho', available: 'Kukhona', steps: 'Amanyathelo okwenza', noTools: 'Akukho mathuluzi abhalisiweyo.', risk: 'ingozi', externalProviders: 'Ama-ejenti angaphandle', externalProvidersBody: 'Xhuma i-Hermes le-OpenClaw ngamapulagini asemthethweni e-OffGrid.', providerPluginsTitle: 'Amapulagini e-provider e-OffGrid', noExternalProviders: 'Akukho ma-provider ama-ejenti angaphandle akhona.', providerReady: 'Kulungele', providerNeedsSetup: 'Kudinga ukulungiswa', generateSetup: 'Yenza i-setup', installPlugin: 'Umlayo we-setup', configuration: 'Ukulungiswa kwe-provider', provider: 'I-provider', transport: 'Indlela yokuthutha', model: 'Imodeli', context: 'I-context', environment: 'Indawo', verification: 'Ukuqinisekisa', notes: 'Amanothi', copy: 'Kopisha', copied: 'Kukotshiwe' },
  product: 'OffGrid', privateWorkspace: 'Indawo yokusebenzela ye-AI eyimfihlo',
  nav: { chat: 'Ingxoxo', knowledge: 'Ulwazi', agents: 'Ama-ejenti', models: 'Amamodeli', activity: 'Imisebenzi', settings: 'Izilungiselelo' },
  status: { ready: 'Isevisi yendawo isilungele', offline: 'Isevisi ayitholakali', checking: 'Kuhlolwa isevisi', noModel: 'Akukhethwanga modeli' },
  auth: { title: 'Ngena endaweni yakho yokusebenzela', body: 'Isevisi le ye-OffGrid idinga ukuqinisekiswa komsebenzisi.', username: 'Ibizo lomsebenzisi', password: 'Iphasiwedi', signIn: 'Ngena', signOut: 'Phuma', localNote: 'Imininingwane yakho yokungena ithunyelwa kule isevisi ye-OffGrid kuphela.' },
  chat: { title: 'Ingxoxo', subtitle: 'Sebenza ngemodeli yendawo lolwazi oluthembekileyo.', emptyTitle: 'Ufuna ukusebenza ngani?', emptyBody: 'Izingxoxo lamadokhumenti akho kuhlala kule idivayisi.', placeholder: 'Buza, bhala, hlaziya, kumbe uhlele…', send: 'Thumela', stop: 'Misa', knowledge: 'Sebenzisa isizinda solwazi', model: 'Imodeli', selectModel: 'Khetha imodeli', you: 'Wena', assistant: 'OffGrid', newChat: 'Ingxoxo entsha', conversations: 'Izingxoxo', noConversations: 'Akukho zingxoxo ezigciniweyo.', deleteConversation: 'Susa ingxoxo', showHistory: 'Tshengisa izingxoxo', closeHistory: 'Vala izingxoxo', copy: 'Kopisha', copied: 'Kukotshiwe', copyResponse: 'Kopisha impendulo', copyCode: 'Kopisha ikhodi', enterHint: 'Enter ukuthumela · Shift+Enter ukuqala umugqa omutsha' },
  knowledge: { title: 'Ulwazi', subtitle: 'Hlela imithombo amamodeli akho angayidinga njalo ayicaphune.', add: 'Faka idokhumenti', empty: 'Akukho madokhumenti asefakwe ku-index.', chunks: 'iziqephu', disabled: 'Ukudinga ulwazi akuvuliwanga.', retained: 'Umthombo ugciniwe', legacy: 'Faka futhi ukuze ubuyekeze', reindex: 'Faka ku-index futhi', reindexing: 'Kufakwa ku-index futhi…' },
  agents: { title: 'Ama-ejenti', subtitle: 'Yenza imisebenzi elawulwayo ubone amathuluzi asebenzayo lemiphumela.', task: 'Umsebenzi', placeholder: 'Chaza umphumela ofuna i-ejenti iwufinyelele…', run: 'Qalisa umsebenzi', running: 'I-ejenti iyasebenza…', result: 'Umphumela', approvalTitle: 'Imvumo iyadingeka', approvalBody: 'Hlola ithuluzi lemininingwane yalo eqondileyo. Imvumo isebenza kulokhu kubiza kuphela.', approve: 'Vumela lokhu kubiza', deny: 'Yala', denied: 'Ukubizwa kwethuluzi kwaliwe ngumsebenzisi.' },
  models: { title: 'Amamodeli', subtitle: 'Phatha amamodeli endawo e-inference le-embedding.', available: 'akhona', empty: 'Akukho mamodeli endawo atholakeleyo.', local: 'Imodeli yendawo', embedding: 'Embedding', installed: 'Afakiweyo', catalog: 'Ikhathalogi ekhethiweyo', discover: 'Dinga amamodeli', recommended: 'Kuyanconywa', download: 'Dawuniloda', resume: 'Qhubeka', cancel: 'Khansela', delete: 'Susa', confirmDelete: 'Qinisekisa ukususa', verify: 'Qinisekisa' },
  activity: { title: 'Imisebenzi', subtitle: 'Impilakahle yesevisi lemininingwane ye-runtime.', uptime: 'Isikhathi isebenza', requests: 'Izicelo', currentModel: 'Imodeli esebenzayo', version: 'Inguqulo', runs: 'Imbali yemisebenzi yama-ejenti', noRuns: 'Akukho misebenzi yama-ejenti ebhaliweyo.', selectRun: 'Khetha umsebenzi ukuze ubone umugqa wesikhathi wezenzakalo zawo.' },
  settings: { title: 'Izilungiselelo', subtitle: 'I-runtime, ukuphepha, lokulawula ukufakwa kwendawo.', service: 'Isevisi', version: 'Inguqulo', inferenceSlots: 'Izikhala ze-inference', knowledge: 'Ulwazi', enabled: 'Kuvuliwe', disabled: 'Kuvaliwe', safety: 'Ukulawula ukuphepha', computerUse: 'Ukusebenzisa ikhompiyutha', available: 'I-driver yepulatifomu ikhona', unavailable: 'Akukho driver yepulatifomu efakiweyo', stopped: 'Ukumisa okuphuthumayo kuyasebenza', sessions: 'amasetshini asebenzayo', emergencyStop: 'Misa ngokuphangisa', setup: 'Ukulungisa indawo yokusebenzela', showGuide: 'Tshengisa umhlahlandlela' },
  onboarding: { title: 'Indawo yakho ye-AI eyimfihlo', body: 'Lungisa imodeli yengxoxo yendawo, ubusuthola impendulo yangempela ukuze uqede i-setup. Idatha yakho ihlala kule idivayisi ngaphandle nxa uxhuma isevisi yangaphandle.', service: 'Isevisi yendawo', models: 'Amamodeli engxoxo', privacy: 'Ubumfihlo obujwayelekileyo', local: 'Okwendawo kuphela', continue: 'Ngena endaweni yokusebenzela', chooseModel: 'Khetha imodeli yengxoxo', startChat: 'Qala ingxoxo yakho yokuqala', retryService: 'Zama ukuxhuma futhi', modelHint: 'Dawuniloda imodeli yengxoxo ukuze uqale ukusebenza.', firstReplyHint: 'I-setup iphela ngemva kwempendulo yokuqala ephumelelayo.', close: 'Vala umhlahlandlela' },
  common: { refresh: 'Vuselela', retry: 'Zama futhi', loading: 'Kuyalayisha…', error: 'Kukhona okungahambanga kuhle', language: 'Ulimi', localProcessing: 'ukucubungula kwendawo', runtime: 'I-runtime', document: 'idokhumenti' }
};
