import type { Messages } from '../types';

export const sn: Messages = {
  history: {"searchChats":"Tsvaga hurukuro","searchTasks":"Tsvaga nhoroondo yemabasa","clearChats":"Dzima hurukuro dzakarongwa","clearTasks":"Dzima mabasa apera","deleteTask":"Dzima basa","confirmTitle":"Dzima nhoroondo?","deleteChatsBody":"Dzima hurukuro {count} dzakarongwa nemadhirafuti adzo emuno? Izvi hazvidzorerwe pano. Makopi ekuchengetedza acharamba aripo.","deleteTasksBody":"Bvisa mabasa {count} apera munhoroondo? Izvi hazvidzorerwe pano. Mafaira akagadzirwa, marekodhi ekuongorora nemakopi ekuchengetedza zvinoramba zviripo.","partialFailure":"Zvinhu {count} hazvina kudzimwa. Zvingave zvichiri kushanda kana zvisingawanikwi. Vandudza kana edza zvakare; zvadzimwa hazvidzokororwi.","deleting":"Kudzima…","noMatches":"Hapana nhoroondo inoenderana.","showMore":"Ratidza zvimwe","protectedTasks":"Mabasa ako apera chete ndiwo anogona kudzimwa. Misa ari kushanda uye tanga waongorora mhedzisiro yakakanganiswa kana isingazivikanwi.","removed":"Zvinhu {count} zvadzimwa.","copyResult":"Kopa mhedzisiro","draftProtected":"Chengeta kana kudzima dhirafuti razvino usati washandisazve basa.","reuseTask":"Shandisazve basa"},
  agentLive: {"live":"Yakabatana","reconnecting":"Iri kubatanidza zvakare…","reconnectHint":"Kubatanidza kuri kugadziriswa. Basa riri kuenderera paservisi; usaritumire zvakare.","preparingTool":"Kugadzirira kushandisa chishandiso","tool":"Kushandisa chishandiso","step":"Danho","elapsed":"Nguva yapfuura","lastUpdate":"Kufambira mberi kwekupedzisira","showPreview":"Ratidza mhinduro ichinyorwa","provisional":"Basa richiri kuitwa — mhinduro haisati yapera","incomplete":"Mhinduro isina kupedzwa","previewLimit":"Muganhu wekuratidza wasvikwa. Mhedzisiro yose ichaonekwa kana basa rapera."},
  chatStreaming: {"queued":"Kumirira kugadzirwa kwemhinduro","retrieving":"Kutsvaga ruzivo","loading":"Kuisa modhi mundangariro","processing":"Kugadzirira meseji","generating":"Kugadzira mhinduro","saving":"Kuchengetedza hurukuro","cancelled":"Yamiswa. Gwaro rako richiripo. Vhura hurukuro patsva usati waedza zvakare kana kuchengetedza kwanga kwatanga.","unsaved":"Mhinduro isina kupera — kuchengetedzwa hakuna kusimbiswa","options":"Zvirongwa zvemhinduro","profile":"Rudzi rwemamiriro","interactive":"Yekukurukurirana","extended":"Yakawedzerwa","responseLimit":"Matokeni akawanda emhinduro","profileHint":"Yekukurukurirana inoshandisa mamiriro madiki. Yakawedzerwa inoshandisa mamiriro eseji uye ndangariro zhinji. Kuchinja kunogona kuisazve modhi; nhoroondo haibviswi pasina kukuzivisa.","firstText":"Mashoko ekutanga","tokensPerSecond":"matokeni/s","contextTokens":"matokeni emamiriro","limitReached":"Muganhu wematokeni wasvikwa. Kumbira kuenderera kana wedzera muganhu."},
  recovery: { draftWarning: "Chinyorwa hachina kukwanisa kuchengetwa pamudziyo uyu. Siya peji iri rakavhurika kusvikira watumira.", reconcile: "Chengeta mhedzisiro yaongororwa", verifyOutcome: "Tanga waongorora zvakaitwa neturusi, wozotsanangura zvakaitika chaizvo. Turusi harizomhanyiswi zvakare.", uncertain: "Mhedzisiro haizivikanwi", pending: "Zvakamirira", running: "Zviri kuitwa", waiting_for_approval: "Zvakamirira mvumo", completed: "Zvapedzwa", failed: "Zvakundikana", cancelled: "Zvakanzurwa", interrupted: "Zvakavhiringidzwa" },
  shell: { work: 'Basa', library: 'Raibhurari', system: 'Sisitimu', appearance: 'Chitarisiko', theme: 'Dingindira', systemTheme: 'Sisitimu', darkTheme: 'Rima', lightTheme: 'Chiedza', storage: 'Kuchengetwa kwemuno', modelsPath: 'Dhairekitori remamodeli', dataPath: 'Dhairekitori redata', quickActions: 'Zviito zvinokurumidza', searchActions: 'Tsvaga mapeji nezviito…', noActions: 'Hapana zviito zvinoenderana.' },
  knowledgeSetup: { title: 'Gadzirira kutsvaga ruzivo', body: 'Ruzivo runoda modeli yeembedding yemuno kuti iise index uye itsvage magwaro ako. Sarudza modeli imwe; OffGrid ichachengeta index pamudziyo uyu.', model: 'Modeli yeembedding', installEnable: 'Isa uye batidza', enable: 'Batidza ruzivo', preparing: 'Ruzivo rwuri kugadzirirwa…', active: 'Modeli yeembedding iri kushanda', openModels: 'Vhura maneja wemamodeli', failed: 'Kugadzira ruzivo kwakundikana' },
  agentRuntime: { style: 'Maitiro ekufunga', react: 'Kutungamirirwa nematurusi', plan: 'Ronga uye ita', reasoning: 'Kufunga', tools: 'Maturusi aripo', enabled: 'akabatidzwa', history: 'Mabasa achangopfuura', noTasks: 'Hapana mabasa emaajenti ati aitwa.', connectors: 'Kubatana kweMCP', noConnectors: 'Hapana maseva eMCP akabatana.', connectorName: 'Zita rekubatana', connectorURL: 'URL yeserver yeMCP', test: 'Edza kubatana', connect: 'Batanidza', testing: 'Kuyedza…', connecting: 'Kubatanidza…', computer: 'Kushandisa kombiyuta', unavailable: 'Driver haisipo', available: 'Iripo', steps: 'Matanho ekuita', noTools: 'Hapana maturusi akanyoreswa.', risk: 'njodzi', externalProviders: 'Maajenti ekunze', externalProvidersBody: 'Batanidza Hermes neOpenClaw uchishandisa mapulagini eOffGrid epamutemo.', providerPluginsTitle: 'Mapulagini eprovider eOffGrid', noExternalProviders: 'Hapana maprovider emaajenti ekunze aripo.', providerReady: 'Yagadzirira', providerNeedsSetup: 'Inoda kugadziriswa', generateSetup: 'Gadzira setup', installPlugin: 'Murairo wesetup', configuration: 'Kugadziriswa kweprovider', provider: 'Provider', transport: 'Nzira yekutakura', model: 'Modeli', context: 'Context', environment: 'Nzvimbo', verification: 'Kuongorora', notes: 'Zvinyorwa', copy: 'Kopa', copied: 'Zvakopwa' },
  product: 'OffGrid', privateWorkspace: 'Nzvimbo yebasa yeAI yakavanzika',
  nav: { chat: 'Hurukuro', knowledge: 'Ruzivo', agents: 'Maajenti', models: 'Mamodheru', activity: 'Zviitiko', settings: 'Zvirongwa' },
  status: { ready: 'Sevhisi yemuno yagadzirira', offline: 'Sevhisi haisi kuwanikwa', checking: 'Kutarisa sevhisi', noModel: 'Hapana modeli yakasarudzwa' },
  auth: { title: 'Pinda munzvimbo yako yebasa', body: 'Sevhisi iyi yeOffGrid inoda kusimbiswa kwemushandisi.', username: 'Zita remushandisi', password: 'Pasiwedhi', signIn: 'Pinda', signOut: 'Buda', localNote: 'Mashoko ako ekupinda anotumirwa kusevhisi iyi yeOffGrid chete.' },
  chat: { title: 'Hurukuro', subtitle: 'Shanda nemodeli yemuno uye ruzivo rwaunovimba narwo.', emptyTitle: 'Ungada kushanda pachii?', emptyBody: 'Hurukuro nemagwaro ako zvinoramba zviri pamudziyo uyu.', placeholder: 'Bvunza, nyora, ongorora, kana kuronga…', send: 'Tumira', stop: 'Misa', knowledge: 'Shandisa dura reruzivo', model: 'Modeli', selectModel: 'Sarudza modeli', you: 'Iwe', assistant: 'OffGrid', newChat: 'Hurukuro itsva', conversations: 'Hurukuro', noConversations: 'Hapana hurukuro dzakachengetwa.', deleteConversation: 'Dzima hurukuro', showHistory: 'Ratidza hurukuro', closeHistory: 'Vhara hurukuro', copy: 'Kopa', copied: 'Zvakopwa', copyResponse: 'Kopa mhinduro', copyCode: 'Kopa code', enterHint: 'Enter kutumira · Shift+Enter kutanga mutsetse mutsva' },
  knowledge: { title: 'Ruzivo', subtitle: 'Ronga masosi anogona kutsvagwa nekudomwa nemamodeli ako.', add: 'Wedzera gwaro', empty: 'Hapana magwaro ati aiswa muindex.', chunks: 'zvikamu', disabled: 'Kutsvaga ruzivo hakuna kubatidzwa.', retained: 'Sosi yachengetwa', legacy: 'Isa zvakare kuti uvandudze', reindex: 'Isa muindex zvakare', reindexing: 'Kuisazve muindex…' },
  agents: { title: 'Maajenti', subtitle: 'Ita mabasa anodzorwa, uchiona maturusi ari kushandiswa nemigumisiro.', task: 'Basa', placeholder: 'Tsanangura mhedzisiro yaunoda kuti ajenti iwane…', run: 'Ita basa', running: 'Ajenti iri kushanda…', result: 'Mhedzisiro', approvalTitle: 'Mvumo inodiwa', approvalBody: 'Ongorora turusi nemaparamita acho chaiwo. Mvumo inoshanda pakufona uku chete.', approve: 'Bvumira kufona uku', deny: 'Ramba', denied: 'Kufona kweturusi kwarambwa nemushandisi.' },
  models: { title: 'Mamodheru', subtitle: 'Tonga mamodeli emuno einference neembedding.', available: 'aripo', empty: 'Hapana mamodeli emuno awanikwa.', local: 'Modeli yemuno', embedding: 'Embedding', installed: 'Akaiswa', catalog: 'Katalogi yakasarudzwa', discover: 'Tsvaga mamodeli', recommended: 'Inokurudzirwa', download: 'Dhaunirodha', resume: 'Enderera', cancel: 'Kanzura', delete: 'Dzima', confirmDelete: 'Simbisa kudzima', verify: 'Ongorora' },
  activity: { title: 'Zviitiko', subtitle: 'Hutano hwesevhisi nemashoko eruntime.', uptime: 'Nguva ichimhanya', requests: 'Zvikumbiro', currentModel: 'Modeli irikushanda', version: 'Vhezheni', runs: 'Nhoroondo yemabasa emaajenti', noRuns: 'Hapana mabasa emaajenti akanyorwa.', selectRun: 'Sarudza basa kuti uone nhoroondo yezviitiko zvaro.' },
  settings: { title: 'Zvirongwa', subtitle: 'Runtime, kuchengeteka, uye kudzora kuiswa kwemuno.', service: 'Sevhisi', version: 'Vhezheni', inferenceSlots: 'Nzvimbo dzeinference', knowledge: 'Ruzivo', enabled: 'Yakabatidzwa', disabled: 'Yakadzimwa', safety: 'Kudzora kuchengeteka', computerUse: 'Kushandisa kombiyuta', available: 'Driver yepuratifomu iripo', unavailable: 'Hapana driver yepuratifomu yakaiswa', stopped: 'Kumiswa kwechimbichimbi kuri kushanda', sessions: 'masesheni ari kushanda', emergencyStop: 'Misa nechimbichimbi', setup: 'Kugadzira nzvimbo yebasa', showGuide: 'Ratidza gwara resetup' },
  onboarding: { title: 'Nzvimbo yako yakavanzika yeAI', body: 'Gadzira modeli yemuno yekukurukura, wobva wawana mhinduro chaiyo kuti upedze setup. Data yako inoramba pamudziyo uyu kunze kwekunge wabatanidza sevhisi yekunze.', service: 'Sevhisi yemuno', models: 'Mamodheru ehurukuro', privacy: 'Kuvanzika kwekutanga', local: 'Yemuno chete', continue: 'Pinda munzvimbo yebasa', chooseModel: 'Sarudza modeli yehurukuro', startChat: 'Tanga hurukuro yako yekutanga', retryService: 'Edzazve kubatana', modelHint: 'Dhaunirodha modeli yehurukuro kuti utange kushanda.', firstReplyHint: 'Setup inopera mushure memhinduro yekutanga yakabudirira.', close: 'Vhara gwara' },
  common: { refresh: 'Vandudza', retry: 'Edza zvakare', loading: 'Kurodha…', error: 'Pane chakanganisika', language: 'Mutauro', localProcessing: 'kugadzirisa kwemuno', runtime: 'Runtime', document: 'gwaro' }
};
