import type { Messages } from '../types';
export const sw: Messages = {
  modelSearch: {"title":"Tafuta modeli zaidi","hint":"Tafuta hazina za GGUF za umma kwenye Hugging Face. Utafutaji hutumia intaneti; katalogi hii haizuii ukubwa wa modeli.","query":"Jina la modeli au mchapishaji","search":"Tafuta","empty":"Hakuna hazina za GGUF za umma zinazolingana. Jaribu jina lingine.","unavailable":"Utafutaji au orodha ya faili haipatikani. Angalia intaneti na ruhusa za modeli, kisha ujaribu tena.","choose":"Chagua faili","modelCard":"Maelezo ya modeli na leseni","file":"Faili ya GGUF / quantization","noFiles":"Hakuna faili za GGUF zinazojitegemea.","unknownSize":"Ukubwa haujulikani","unsupported":"Inahitaji faili za ziada","compatibility":"Angalia maelezo, leseni na usaidizi wa injini. Ukubwa wa faili si matumizi ya RAM/VRAM; muktadha unahitaji kumbukumbu zaidi. Faili zilizogawanywa na projectors hazijitegemei. Huonyesha hadi rekodi 1,000."},
  modelDownload: {"downloading":"Inapakua","finalizing":"Inaandaa modeli","complete":"Tayari","failed":"Upakuaji umekatizwa","cancelled":"Imeghairiwa","retained":"Data iliyopakuliwa imehifadhiwa. Endelea ili ujaribu tena."},
  history: {"searchChats":"Tafuta mazungumzo","searchTasks":"Tafuta historia ya kazi","clearChats":"Futa mazungumzo yaliyoorodheshwa","clearTasks":"Futa kazi zinazoweza kufutwa","deleteTask":"Futa kazi","confirmTitle":"Futa historia?","deleteChatsBody":"Futa mazungumzo {count} yaliyoorodheshwa na rasimu zake za ndani? Huwezi kutengua hapa. Nakala rudufu zitabaki.","deleteTasksBody":"Uondoe kazi {count} zilizochaguliwa kwenye historia? Hili haliwezi kutenduliwa hapa. Faili zilizoundwa, kumbukumbu za ukaguzi na nakala rudufu zinahifadhiwa.","partialFailure":"Vipengee {count} havikuweza kufutwa. Huenda vinaendelea au havipatikani. Onyesha upya au jaribu tena; vilivyofutwa havitarudiwa.","deleting":"Inafuta…","noMatches":"Hakuna historia inayolingana.","showMore":"Onyesha zaidi","protectedTasks":"Kazi zilizokamilika na zilizokatizwa bila hali ya kurejesha zinaweza kufutwa. Kazi zinazoendelea, zinazoweza kuendelezwa na matokeo ya zana yasiyothibitishwa zinalindwa.","removed":"Vipengee {count} vimefutwa.","copyResult":"Nakili matokeo","draftProtected":"Hifadhi au futa rasimu ya sasa kabla ya kutumia kazi tena.","reuseTask":"Tumia kazi tena"},
  agentLive: {"live":"Muunganisho wa moja kwa moja","reconnecting":"Inaunganisha tena…","reconnectHint":"Muunganisho unarejeshwa. Kazi inaendelea kwenye huduma; usiitume tena.","preparingTool":"Inaandaa kutumia zana","tool":"Inaendesha zana","step":"Hatua","elapsed":"Muda uliopita","lastUpdate":"Maendeleo ya mwisho","showPreview":"Onyesho la jibu moja kwa moja","provisional":"Inaendelea — jibu halijakamilika","incomplete":"Jibu halijakamilika","previewLimit":"Kikomo cha onyesho kimefikiwa. Matokeo kamili yataonekana kazi ikikamilika."},
  chatStreaming: {"queued":"Inasubiri uchakataji","retrieving":"Inatafuta maarifa","loading":"Inapakia modeli","processing":"Inaandaa ujumbe","generating":"Inazalisha jibu","saving":"Inahifadhi mazungumzo","cancelled":"Imesimamishwa. Rasimu yako imehifadhiwa. Pakia mazungumzo upya kabla ya kujaribu tena ikiwa uhifadhi ulikuwa umeanza.","unsaved":"Jibu la sehemu — uhifadhi haujathibitishwa","options":"Mipangilio ya majibu","profile":"Wasifu wa muktadha","interactive":"Shirikishi","extended":"Iliyopanuliwa","responseLimit":"Tokeni za juu za jibu","profileHint":"Shirikishi hutumia muktadha mdogo. Iliyopanuliwa hutumia muktadha wa huduma na kumbukumbu zaidi. Kubadilisha kunaweza kupakia modeli upya; historia haiondolewi kimya kimya.","firstText":"Maandishi ya kwanza","tokensPerSecond":"tokeni/s","contextTokens":"tokeni za muktadha","limitReached":"Kikomo cha tokeni kimefikiwa. Omba kuendelea au ongeza kikomo."},
  recovery: { draftWarning: "Rasimu haikuweza kuhifadhiwa kwenye kifaa hiki. Acha ukurasa wazi hadi utume.", reconcile: "Hifadhi matokeo yaliyothibitishwa", verifyOutcome: "Kagua kwanza lengo la zana, kisha eleza kilichotokea. Hii haitarudia kuendesha zana.", uncertain: "Matokeo hayajulikani", pending: "Inasubiri", running: "Inaendeshwa", waiting_for_approval: "Inasubiri idhini", completed: "Imekamilika", failed: "Imeshindwa", cancelled: "Imeghairiwa", interrupted: "Imekatizwa" },
  shell: { work: 'Kazi', library: 'Maktaba', system: 'Mfumo', appearance: 'Muonekano', theme: 'Mandhari', systemTheme: 'Mfumo', darkTheme: 'Giza', lightTheme: 'Angavu', storage: 'Hifadhi ya ndani', modelsPath: 'Saraka ya miundo', dataPath: 'Saraka ya data', quickActions: 'Vitendo vya haraka', searchActions: 'Tafuta kurasa na vitendo…', noActions: 'Hakuna vitendo vinavyolingana.' },
  knowledgeSetup: { title: 'Andaa utafutaji wa maarifa', body: 'Hazina ya maarifa inahitaji muundo wa ndani wa embedding ili kupanga na kutafuta nyaraka. Fahirisi hubaki kwenye kifaa hiki.', model: 'Muundo wa embedding', installEnable: 'Sakinisha na uwashe', enable: 'Washa maarifa', preparing: 'Inaandaa maarifa…', active: 'Muundo wa embedding unaotumika', openModels: 'Fungua miundo', failed: 'Usanidi wa maarifa umeshindwa' },
  agentRuntime: { style: 'Mtindo wa kufikiri', react: 'Kuongozwa na zana', plan: 'Panga na utekeleze', reasoning: 'Kufikiri', tools: 'Zana zinazopatikana', enabled: 'zimewashwa', history: 'Kazi za hivi karibuni', noTasks: 'Hakuna kazi za wakala bado.', connectors: 'Miunganisho ya MCP', noConnectors: 'Hakuna seva za MCP zilizounganishwa.', connectorName: 'Jina la muunganisho', connectorURL: 'URL ya seva ya MCP', test: 'Jaribu', connect: 'Unganisha', testing: 'Inajaribu…', connecting: 'Inaunganisha…', computer: 'Matumizi ya kompyuta', unavailable: 'Kiendeshaji hakipatikani', available: 'Inapatikana', steps: 'Hatua za utekelezaji', noTools: 'Hakuna zana zilizosajiliwa.', risk: 'hatari', externalProviders: 'Mawakala wa nje', externalProvidersBody: 'Unganisha Hermes na OpenClaw kupitia programu-jalizi asilia za mtoa huduma wa OffGrid.', providerPluginsTitle: 'Programu-jalizi asilia za mtoa huduma wa OffGrid', noExternalProviders: 'Hakuna watoa huduma wa mawakala wa nje.', providerReady: 'Tayari', providerNeedsSetup: 'Inahitaji usanidi', generateSetup: 'Tengeneza usanidi', installPlugin: 'Sakinisha mtoa huduma', configuration: 'Usanidi wa mtoa huduma', provider: 'Mtoa huduma', transport: 'Itifaki', model: 'Muundo', context: 'Muktadha', environment: 'Mazingira', verification: 'Uthibitishaji', notes: 'Vidokezo', copy: 'Nakili', copied: 'Imenakiliwa' },
  product: 'OffGrid', privateWorkspace: 'Sehemu binafsi ya kazi ya AI',
  nav: { chat: 'Mazungumzo', knowledge: 'Maarifa', agents: 'Mawakala', models: 'Miundo', activity: 'Shughuli', settings: 'Mipangilio' },
  status: { ready: 'Huduma ya ndani iko tayari', offline: 'Huduma haipatikani', checking: 'Inakagua huduma', noModel: 'Hakuna muundo uliochaguliwa' },
  auth: { title: 'Ingia kwenye sehemu yako', body: 'Huduma hii ya OffGrid inahitaji uthibitishaji.', username: 'Jina la mtumiaji', password: 'Nenosiri', signIn: 'Ingia', signOut: 'Toka', localNote: 'Taarifa zako zinatumwa kwa huduma hii ya OffGrid pekee.' },
  chat: { title: 'Mazungumzo', subtitle: 'Fanya kazi na muundo wa ndani na maarifa yanayoaminika.', emptyTitle: 'Ungependa kufanya nini?', emptyBody: 'Mazungumzo na nyaraka zako hubaki kwenye kifaa hiki.', placeholder: 'Uliza, andika, chambua au panga…', send: 'Tuma', stop: 'Simamisha', knowledge: 'Tumia hazina ya maarifa', model: 'Muundo', selectModel: 'Chagua muundo', you: 'Wewe', assistant: 'OffGrid', newChat: 'Mazungumzo mapya', conversations: 'Mazungumzo', noConversations: 'Hakuna mazungumzo yaliyohifadhiwa.', deleteConversation: 'Futa mazungumzo', showHistory: 'Onyesha mazungumzo', closeHistory: 'Funga mazungumzo', copy: 'Nakili', copied: 'Imenakiliwa', copyResponse: 'Nakili jibu', copyCode: 'Nakili msimbo', enterHint: 'Enter kutuma · Shift+Enter kwa mstari mpya' },
  knowledge: { title: 'Maarifa', subtitle: 'Simamia vyanzo ambavyo miundo inaweza kutafuta na kunukuu.', add: 'Ongeza waraka', empty: 'Hakuna nyaraka zilizoorodheshwa bado.', chunks: 'vipande', disabled: 'Utafutaji wa maarifa haujawashwa.', retained: 'Chanzo kimehifadhiwa', legacy: 'Ingiza tena ili kusasisha', reindex: 'Panga upya', reindexing: 'Inapanga upya…' },
  agents: { title: 'Mawakala', subtitle: 'Endesha kazi zinazosimamiwa huku zana na matokeo yakionekana.', task: 'Kazi', placeholder: 'Eleza matokeo unayotaka wakala afikie…', run: 'Endesha kazi', running: 'Wakala anafanya kazi…', result: 'Matokeo', approvalTitle: 'Idhini inahitajika', approvalBody: 'Kagua zana na hoja kamili. Idhini inatumika kwa mwito huu pekee.', approve: 'Idhinisha mwito huu', deny: 'Kataa', denied: 'Mwito wa zana umekataliwa na mtumiaji.' },
  models: { title: 'Miundo', subtitle: 'Simamia miundo ya ndani ya utabiri na embedding.', available: 'inapatikana', empty: 'Hakuna miundo ya ndani iliyopatikana.', local: 'Muundo wa ndani', embedding: 'Embedding', installed: 'Iliyosakinishwa', catalog: 'Orodha iliyochaguliwa', discover: 'Gundua miundo', recommended: 'Inapendekezwa', download: 'Pakua', resume: 'Endelea', cancel: 'Ghairi', delete: 'Futa', confirmDelete: 'Thibitisha kufuta', verify: 'Hakiki' },
  activity: { title: 'Shughuli', subtitle: 'Afya ya huduma na maelezo ya uendeshaji.', uptime: 'Muda wa kazi', requests: 'Maombi', currentModel: 'Muundo wa sasa', version: 'Toleo', runs: 'Historia ya uendeshaji wa mawakala', noRuns: 'Hakuna uendeshaji wa wakala uliorekodiwa.', selectRun: 'Chagua uendeshaji ili kuona mfululizo wa matukio.' },
  settings: { title: 'Mipangilio', subtitle: 'Vidhibiti vya uendeshaji, usalama na usambazaji wa ndani.', service: 'Huduma', version: 'Toleo', inferenceSlots: 'Nafasi za utabiri', knowledge: 'Maarifa', enabled: 'Imewashwa', disabled: 'Imezimwa', safety: 'Udhibiti wa usalama', computerUse: 'Matumizi ya kompyuta', available: 'Kiendeshaji cha mfumo kinapatikana', unavailable: 'Hakuna kiendeshaji cha mfumo kilichosakinishwa', stopped: 'Kusimamisha kwa dharura kumewashwa', sessions: 'vipindi hai', emergencyStop: 'Simamisha kwa dharura', setup: 'Usanidi wa sehemu', showGuide: 'Onyesha mwongozo' },
  onboarding: { title: 'Sehemu yako binafsi ya AI', body: 'Sakinisha muundo wa mazungumzo wa ndani, kisha upate jibu halisi ili kukamilisha usanidi. Data yako hubaki kwenye kifaa hiki isipokuwa uunganishe huduma ya nje.', service: 'Huduma ya ndani', models: 'Miundo ya mazungumzo', privacy: 'Faragha chaguomsingi', local: 'Ndani pekee', continue: 'Ingia kwenye sehemu', chooseModel: 'Chagua muundo wa mazungumzo', startChat: 'Anza mazungumzo yako ya kwanza', retryService: 'Jaribu kuunganisha tena', modelHint: 'Pakua muundo wa mazungumzo ili kuanza.', firstReplyHint: 'Usanidi hukamilika baada ya jibu la kwanza kutoka kwa muundo.', close: 'Funga mwongozo' },
  common: { refresh: 'Onyesha upya', retry: 'Jaribu tena', loading: 'Inapakia…', error: 'Hitilafu imetokea', language: 'Lugha', localProcessing: 'uchakataji wa ndani', runtime: 'Uendeshaji', document: 'waraka' }
};
