import type { Messages } from '../types';
export const sw: Messages = {
  product: 'OffGrid', privateWorkspace: 'Sehemu binafsi ya kazi ya AI',
  nav: { chat: 'Mazungumzo', knowledge: 'Maarifa', agents: 'Mawakala', models: 'Miundo', activity: 'Shughuli', settings: 'Mipangilio' },
  status: { ready: 'Huduma ya ndani iko tayari', offline: 'Huduma haipatikani', checking: 'Inakagua huduma', noModel: 'Hakuna muundo uliochaguliwa' },
  auth: { title: 'Ingia kwenye sehemu yako', body: 'Huduma hii ya OffGrid inahitaji uthibitishaji.', username: 'Jina la mtumiaji', password: 'Nenosiri', signIn: 'Ingia', signOut: 'Toka', localNote: 'Taarifa zako zinatumwa kwa huduma hii ya OffGrid pekee.' },
  chat: { title: 'Mazungumzo', subtitle: 'Fanya kazi na muundo wa ndani na maarifa yanayoaminika.', emptyTitle: 'Ungependa kufanya nini?', emptyBody: 'Mazungumzo na nyaraka zako hubaki kwenye kifaa hiki.', placeholder: 'Uliza, andika, chambua au panga…', send: 'Tuma', stop: 'Simamisha', knowledge: 'Tumia hazina ya maarifa', model: 'Muundo', selectModel: 'Chagua muundo', you: 'Wewe', assistant: 'OffGrid', newChat: 'Mazungumzo mapya', conversations: 'Mazungumzo', noConversations: 'Hakuna mazungumzo yaliyohifadhiwa.', deleteConversation: 'Futa mazungumzo' },
  knowledge: { title: 'Maarifa', subtitle: 'Simamia vyanzo ambavyo miundo inaweza kutafuta na kunukuu.', add: 'Ongeza waraka', empty: 'Hakuna nyaraka zilizoorodheshwa bado.', chunks: 'vipande', disabled: 'Utafutaji wa maarifa haujawashwa.', retained: 'Chanzo kimehifadhiwa', legacy: 'Ingiza tena ili kusasisha', reindex: 'Panga upya', reindexing: 'Inapanga upya…' },
  agents: { title: 'Mawakala', subtitle: 'Endesha kazi zinazosimamiwa huku zana na matokeo yakionekana.', task: 'Kazi', placeholder: 'Eleza matokeo unayotaka wakala afikie…', run: 'Endesha kazi', running: 'Wakala anafanya kazi…', result: 'Matokeo', approvalTitle: 'Idhini inahitajika', approvalBody: 'Kagua zana na hoja kamili. Idhini inatumika kwa mwito huu pekee.', approve: 'Idhinisha mwito huu', deny: 'Kataa', denied: 'Mwito wa zana umekataliwa na mtumiaji.' },
  models: { title: 'Miundo', subtitle: 'Simamia miundo ya ndani ya utabiri na embedding.', available: 'inapatikana', empty: 'Hakuna miundo ya ndani iliyopatikana.', local: 'Muundo wa ndani', embedding: 'Embedding', installed: 'Iliyosakinishwa', catalog: 'Orodha iliyochaguliwa', discover: 'Gundua miundo', recommended: 'Inapendekezwa', download: 'Pakua', resume: 'Endelea', cancel: 'Ghairi', delete: 'Futa', confirmDelete: 'Thibitisha kufuta', verify: 'Hakiki' },
  activity: { title: 'Shughuli', subtitle: 'Afya ya huduma na maelezo ya uendeshaji.', uptime: 'Muda wa kazi', requests: 'Maombi', currentModel: 'Muundo wa sasa', version: 'Toleo', runs: 'Historia ya uendeshaji wa mawakala', noRuns: 'Hakuna uendeshaji wa wakala uliorekodiwa.', selectRun: 'Chagua uendeshaji ili kuona mfululizo wa matukio.' },
  settings: { title: 'Mipangilio', subtitle: 'Vidhibiti vya uendeshaji, usalama na usambazaji wa ndani.', service: 'Huduma', version: 'Toleo', inferenceSlots: 'Nafasi za utabiri', knowledge: 'Maarifa', enabled: 'Imewashwa', disabled: 'Imezimwa', safety: 'Udhibiti wa usalama', computerUse: 'Matumizi ya kompyuta', available: 'Kiendeshaji cha mfumo kinapatikana', unavailable: 'Hakuna kiendeshaji cha mfumo kilichosakinishwa', stopped: 'Kusimamisha kwa dharura kumewashwa', sessions: 'vipindi hai', emergencyStop: 'Simamisha kwa dharura', setup: 'Usanidi wa sehemu', showGuide: 'Onyesha mwongozo' },
  onboarding: { title: 'Sehemu yako binafsi ya AI', body: 'Hakikisha huduma ya ndani na muundo viko tayari. Data hubaki kwenye kifaa hiki isipokuwa uunganishe huduma ya nje.', service: 'Huduma ya ndani', models: 'Miundo inayopatikana', privacy: 'Faragha chaguomsingi', local: 'Ndani pekee', continue: 'Ingia kwenye sehemu' },
  common: { refresh: 'Onyesha upya', retry: 'Jaribu tena', loading: 'Inapakia…', error: 'Hitilafu imetokea', language: 'Lugha', localProcessing: 'uchakataji wa ndani', runtime: 'Uendeshaji', document: 'waraka' }
};
