import type { Messages } from '../types';

export const zu: Messages = {
  chatStreaming: {"queued":"Kulindwe impendulo","retrieving":"Kuseshwa ulwazi","loading":"Kulayishwa imodeli","processing":"Kulungiswa umlayezo","generating":"Kwakhiwa impendulo","saving":"Kugcinwa ingxoxo","cancelled":"Kumisiwe. Umbhalo wakho usagciniwe. Layisha ingxoxo kabusha ngaphambi kokuzama futhi uma ukugcina bekuqalile.","unsaved":"Impendulo engaphelele — ukugcinwa akuqinisekisiwe","options":"Izilungiselelo zempendulo","profile":"Uhlobo lomongo","interactive":"Okokuxoxisana","extended":"Okunwetshiwe","responseLimit":"Amathokheni aphezulu empendulo","profileHint":"Okokuxoxisana kusebenzisa umongo omncane. Okunwetshiwe kusebenzisa umongo wesevisi nenkumbulo eningi. Ukushintsha kungalayisha imodeli kabusha; umlando awususwa ngaphandle kokwazisa.","firstText":"Umbhalo wokuqala","tokensPerSecond":"amathokheni/s","contextTokens":"amathokheni omongo","limitReached":"Umkhawulo wamathokheni ufinyelelwe. Cela ukuqhubeka noma wandise umkhawulo."},
  recovery: { draftWarning: "Okusalungiswa akugcinwanga kule divayisi. Shiya ikhasi livuliwe uze uthumele.", reconcile: "Gcina umphumela oqinisekisiwe", verifyOutcome: "Qala uhlole okwenziwe yithuluzi, bese uchaza okwenzekile. Ithuluzi ngeke liqaliswe futhi.", uncertain: "Umphumela awaziwa", pending: "Kulindile", running: "Kuyasebenza", waiting_for_approval: "Kulinde imvume", completed: "Kuqediwe", failed: "Kuhlulekile", cancelled: "Kukhanseliwe", interrupted: "Kuphazamisekile" },
  shell: { work: 'Umsebenzi', library: 'Umtapo', system: 'Uhlelo', appearance: 'Ukubukeka', theme: 'Itimu', systemTheme: 'Uhlelo', darkTheme: 'Okumnyama', lightTheme: 'Okukhanyayo', storage: 'Isitoreji sendawo', modelsPath: 'Ifolda yamamodeli', dataPath: 'Ifolda yedatha', quickActions: 'Izenzo ezisheshayo', searchActions: 'Sesha amakhasi nezenzo…', noActions: 'Azikho izenzo ezifanayo.' },
  knowledgeSetup: { title: 'Lungiselela ukusesha ulwazi', body: 'Ulwazi ludinga imodeli ye-embedding yasendaweni ukuze luhlele futhi luseshe amadokhumenti akho. Khetha imodeli eyodwa; i-OffGrid izogcina i-index kule divayisi.', model: 'Imodeli ye-embedding', installEnable: 'Faka bese uvula', enable: 'Vula ulwazi', preparing: 'Ulwazi luyalungiselelwa…', active: 'Imodeli ye-embedding esebenzayo', openModels: 'Vula umphathi wamamodeli', failed: 'Ukulungiselela ulwazi kwehlulekile' },
  agentRuntime: { style: 'Indlela yokucabanga', react: 'Ukuqondiswa ngamathuluzi', plan: 'Hlela bese wenza', reasoning: 'Ukucabanga', tools: 'Amathuluzi atholakalayo', enabled: 'avuliwe', history: 'Imisebenzi yakamuva', noTasks: 'Ayikho imisebenzi yama-ejenti eseyenziwe.', connectors: 'Ukuxhumana kwe-MCP', noConnectors: 'Awekho amaseva e-MCP axhunyiwe.', connectorName: 'Igama lokuxhumana', connectorURL: 'I-URL yeseva ye-MCP', test: 'Hlola ukuxhumana', connect: 'Xhuma', testing: 'Kuyahlolwa…', connecting: 'Kuyaxhunywa…', computer: 'Ukusebenzisa ikhompyutha', unavailable: 'I-driver ayitholakali', available: 'Kuyatholakala', steps: 'Izinyathelo zokwenza', noTools: 'Awekho amathuluzi abhalisiwe.', risk: 'ingozi', externalProviders: 'Ama-ejenti angaphandle', externalProvidersBody: 'Xhuma i-Hermes ne-OpenClaw ngamapulagini e-OffGrid asemthethweni.', providerPluginsTitle: 'Amapulagini e-provider e-OffGrid', noExternalProviders: 'Awekho ama-provider ama-ejenti angaphandle atholakalayo.', providerReady: 'Isilungele', providerNeedsSetup: 'Idinga ukulungiswa', generateSetup: 'Yakha i-setup', installPlugin: 'Umyalo we-setup', configuration: 'Ukulungiswa kwe-provider', provider: 'I-provider', transport: 'Indlela yokuthutha', model: 'Imodeli', context: 'I-context', environment: 'Indawo', verification: 'Ukuqinisekisa', notes: 'Amanothi', copy: 'Kopisha', copied: 'Kukopishiwe' },
  product: 'OffGrid', privateWorkspace: 'Indawo yokusebenzela ye-AI eyimfihlo',
  nav: { chat: 'Ingxoxo', knowledge: 'Ulwazi', agents: 'Ama-ejenti', models: 'Amamodeli', activity: 'Umsebenzi', settings: 'Izilungiselelo' },
  status: { ready: 'Isevisi yasendaweni isilungele', offline: 'Isevisi ayitholakali', checking: 'Kuhlolwa isevisi', noModel: 'Ayikho imodeli ekhethiwe' },
  auth: { title: 'Ngena endaweni yakho yokusebenzela', body: 'Le sevisi ye-OffGrid idinga ukuqinisekiswa komsebenzisi.', username: 'Igama lomsebenzisi', password: 'Iphasiwedi', signIn: 'Ngena', signOut: 'Phuma', localNote: 'Imininingwane yakho yokungena ithunyelwa kule sevisi ye-OffGrid kuphela.' },
  chat: { title: 'Ingxoxo', subtitle: 'Sebenza ngemodeli yasendaweni nolwazi oluthembekile.', emptyTitle: 'Ungathanda ukusebenza ngani?', emptyBody: 'Izingxoxo namadokhumenti akho kuhlala kule divayisi.', placeholder: 'Buza, bhala, hlaziya, noma uhlele…', send: 'Thumela', stop: 'Misa', knowledge: 'Sebenzisa isizinda solwazi', model: 'Imodeli', selectModel: 'Khetha imodeli', you: 'Wena', assistant: 'OffGrid', newChat: 'Ingxoxo entsha', conversations: 'Izingxoxo', noConversations: 'Azikho izingxoxo ezigciniwe.', deleteConversation: 'Susa ingxoxo', showHistory: 'Bonisa izingxoxo', closeHistory: 'Vala izingxoxo', copy: 'Kopisha', copied: 'Kukopishiwe', copyResponse: 'Kopisha impendulo', copyCode: 'Kopisha ikhodi', enterHint: 'Enter ukuthumela · Shift+Enter ukuqala umugqa omusha' },
  knowledge: { title: 'Ulwazi', subtitle: 'Hlela imithombo amamodeli akho angayisesha futhi ayicaphune.', add: 'Engeza idokhumenti', empty: 'Awekho amadokhumenti asefakwe ku-index.', chunks: 'izingxenye', disabled: 'Ukusesha ulwazi akuvuliwe.', retained: 'Umthombo ugciniwe', legacy: 'Faka futhi ukuze ubuyekeze', reindex: 'Faka ku-index futhi', reindexing: 'Kufakwa ku-index futhi…' },
  agents: { title: 'Ama-ejenti', subtitle: 'Qalisa imisebenzi elawulwayo ubone amathuluzi asebenzayo nemiphumela.', task: 'Umsebenzi', placeholder: 'Chaza umphumela ofuna i-ejenti iwufinyelele…', run: 'Qalisa umsebenzi', running: 'I-ejenti iyasebenza…', result: 'Umphumela', approvalTitle: 'Imvume iyadingeka', approvalBody: 'Hlola ithuluzi nemininingwane yalo ngqo. Imvume isebenza kulokhu kubiza kuphela.', approve: 'Vumela lokhu kubiza', deny: 'Nqaba', denied: 'Ukubizwa kwethuluzi kunqatshwe ngumsebenzisi.' },
  models: { title: 'Amamodeli', subtitle: 'Phatha amamodeli asendaweni e-inference ne-embedding.', available: 'atholakalayo', empty: 'Awekho amamodeli asendaweni atholakele.', local: 'Imodeli yasendaweni', embedding: 'Embedding', installed: 'Afakiwe', catalog: 'Ikhathalogi ekhethiwe', discover: 'Thola amamodeli', recommended: 'Kunconyiwe', download: 'Landa', resume: 'Qhubeka', cancel: 'Khansela', delete: 'Susa', confirmDelete: 'Qinisekisa ukususa', verify: 'Qinisekisa' },
  activity: { title: 'Umsebenzi', subtitle: 'Isimo sesevisi nemininingwane ye-runtime.', uptime: 'Isikhathi sokusebenza', requests: 'Izicelo', currentModel: 'Imodeli esebenzayo', version: 'Inguqulo', runs: 'Umlando wemisebenzi yama-ejenti', noRuns: 'Ayikho imisebenzi yama-ejenti erekhodiwe.', selectRun: 'Khetha umsebenzi ukuze ubone umugqa wesikhathi wezenzakalo zawo.' },
  settings: { title: 'Izilungiselelo', subtitle: 'I-runtime, ukuphepha, nokulawula ukufakwa kwasendaweni.', service: 'Isevisi', version: 'Inguqulo', inferenceSlots: 'Izikhala ze-inference', knowledge: 'Ulwazi', enabled: 'Kuvuliwe', disabled: 'Kuvaliwe', safety: 'Ukulawula ukuphepha', computerUse: 'Ukusebenzisa ikhompyutha', available: 'I-driver yepulatifomu iyatholakala', unavailable: 'Ayikho i-driver yepulatifomu efakiwe', stopped: 'Ukumisa okuphuthumayo kuyasebenza', sessions: 'amasikhathi asebenzayo', emergencyStop: 'Misa ngokuphuthumayo', setup: 'Ukulungisa indawo yokusebenzela', showGuide: 'Bonisa umhlahlandlela' },
  onboarding: { title: 'Indawo yakho ye-AI eyimfihlo', body: 'Lungisa imodeli yengxoxo yasendaweni, bese uthola impendulo yangempela ukuze uqede i-setup. Idatha yakho ihlala kule divayisi ngaphandle uma uxhuma isevisi yangaphandle.', service: 'Isevisi yasendaweni', models: 'Amamodeli engxoxo', privacy: 'Ubumfihlo obujwayelekile', local: 'Okwasendaweni kuphela', continue: 'Ngena endaweni yokusebenzela', chooseModel: 'Khetha imodeli yengxoxo', startChat: 'Qala ingxoxo yakho yokuqala', retryService: 'Zama ukuxhuma futhi', modelHint: 'Landa imodeli yengxoxo ukuze uqale ukusebenza.', firstReplyHint: 'I-setup iphela ngemva kwempendulo yokuqala ephumelelayo.', close: 'Vala umhlahlandlela' },
  common: { refresh: 'Vuselela', retry: 'Zama futhi', loading: 'Kuyalayisha…', error: 'Kukhona okungahambanga kahle', language: 'Ulimi', localProcessing: 'ukucubungula kwasendaweni', runtime: 'I-runtime', document: 'idokhumenti' }
};
